### PR TITLE
Bugfix. NPE in indentation rule(#555)

### LINKED ISSUE #555: NPE in IndentationRule (during autofix)
## Describe the bug
```kotlin
fun foo() {
    val diktatExtension = project.extensions.create(DIKTAT_EXTENSION, DiktatExtension::class.java)
    diktatExtension.inputs = project.fileTree("src").apply {
        include("**/*.kt")
    }
    diktatExtension.reporter = PlainReporter(System.out)
}
```
yields
```
Caused by: java.lang.IllegalStateException: whiteSpace.prevSibling must not be null
	at org.cqfn.diktat.ruleset.utils.indentation.AssignmentOperatorChecker.checkNode(Checkers.kt:55) ~[diktat-rules-0.1.4.jar:na]
	at org.cqfn.diktat.ruleset.rules.files.IndentationRule.visitWhiteSpace(IndentationRule.kt:174) ~[diktat-rules-0.1.4.jar:na]
	at org.cqfn.diktat.ruleset.rules.files.IndentationRule.access$visitWhiteSpace(IndentationRule.kt:57) ~[diktat-rules-0.1.4.jar:na]
	at org.cqfn.diktat.ruleset.rules.files.IndentationRule$checkIndentation$1.invoke(IndentationRule.kt:156) ~[diktat-rules-0.1.4.jar:na]
	at org.cqfn.diktat.ruleset.rules.files.IndentationRule$checkIndentation$1.invoke(IndentationRule.kt:57) ~[diktat-rules-0.1.4.jar:na]
```

## Environment information
* diktat version: 0.1.4 (same for 0.1.5)

### PR DESCRIPTION
**Pull request by aktsay6**
This PR fixes NPE in Indentation Rule

This pull request closes #555

### CODE REVIEW

**Comment by aktsay6** [comment]
Guess fix for `apply` in this case is not right. See Example4Expected.kt. Should we open an issue on it? @petertrr

**Review by petertrr — APPROVED** [review]
lgtm

File: diktat-rules/src/test/resources/test/chapter6/compact_initialization/ApplyWithValueArgumentExpected.kt [hunk 1]
```diff
@@ -9,4 +9,12 @@ httpClient.doRequest()
 
 fun setDefaultUrl(httpClient: HttpClient) {
     httpClient.url = "http://example.com"
+}
+
+fun foo() {
```
Comment (akuleshov7) [inline diktat-rules/src/test/resources/test/chapter6/compact_initialization/ApplyWithValueArgumentExpected.kt:14]: I would add `check` tests too
