### PR TITLE
Rule 6.1.6 abstract classes should have at least one abstract method

### LINKED ISSUE #442: Rule 6.1.6: Abstract class should have at least one abstract method
Abstract classes are used to force a developer to implement some of its parts in its inheritors.
In case when abstract class has no abstract methods - then it was set `abstract` incorrectly and can be converted to a normal class.
Bad example:
```kotlin
abstract class NotAbstract {
    fun foo() {}
    
    fun test() {}
}
```

Good example:
```kotlin
abstract class NotAbstract {
    abstract fun foo()
    
    fun test() {}
}

// OR
class NotAbstract {
    fun foo() {}
    
    fun test() {}
}
```

### PR DESCRIPTION
**Pull request by aktsay6**
### What's done:
  * Rule logic made
  * Added fix and warn tests

This pull request closes #442 

## Actions checklist
* [X] Implemented Rule, added Warnings
* [X] Added tests on checks
* [X] Added tests on fixers
* [X] Updated diktat-analysis.yml
* [X] Updated available-rules.md

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt [hunk 1]
```diff
@@ -119,6 +119,7 @@ enum class Warnings(private val canBeAutoCorrected: Boolean, private val warn: S
     // ======== chapter 6 ========
     USE_DATA_CLASS(false, "this class can be converted to a data class"),
     WRONG_NAME_OF_VARIABLE_INSIDE_ACCESSOR(false, "Use `field` keyword instead of property name inside property accessors"),
+    CLASS_SHOULD_NOT_BE_ABSTRACT(true, "class should not be abstract"),
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt:122]:
```suggestion
    CLASS_SHOULD_NOT_BE_ABSTRACT(true, "class should not be abstract, because it has no abstract functions"),
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+        if (node.elementType == CLASS) {
+            val classBody = node.getFirstChildWithType(CLASS_BODY) ?: return
+
+            if (checkAbstractModifier(node)) {
+                handleAbstractClass(classBody, node)
+            }
+        }
+    }
+
+    private fun checkAbstractModifier(node: ASTNode): Boolean =
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt:40]:
```suggestion
    private fun hasAbstractModifier(node: ASTNode): Boolean =
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+
+    @Suppress("UnsafeCallOnNullableType")
+    private fun handleAbstractClass(node: ASTNode, classNode: ASTNode) {
+        val functions = node.getAllChildrenWithType(FUN)
+
+        val identifier = classNode.getFirstChildWithType(IDENTIFIER)!!.text
+
+        if (functions.isNotEmpty() && functions.none { checkAbstractModifier(it) }) {
+            CLASS_SHOULD_NOT_BE_ABSTRACT.warnAndFix(configRule, emitWarn, isFixMode, identifier, node.startOffset, node) {
+                classNode.removeChild(classNode.getFirstChildWithType(MODIFIER_LIST)!!)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt:51]: But there may be other modifiers other than `abstract`...

**Review by petertrr — CHANGES_REQUESTED** [review]
Please add test with other class modifiers

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt [hunk 4]
```diff
@@ -46,11 +46,19 @@ class AbstractClassesRule(private val configRule: List<RulesConfig>) : Rule("abs
...
-        if (functions.isNotEmpty() && functions.none { checkAbstractModifier(it) }) {
+        if (functions.isNotEmpty() && functions.none { hasAbstractModifier(it) }) {
             CLASS_SHOULD_NOT_BE_ABSTRACT.warnAndFix(configRule, emitWarn, isFixMode, identifier, node.startOffset, node) {
-                classNode.removeChild(classNode.getFirstChildWithType(MODIFIER_LIST)!!)
-                if (classNode.firstChildNode.isWhiteSpace()) {
-                    classNode.removeChild(classNode.firstChildNode)
+                val modList = classNode.getFirstChildWithType(MODIFIER_LIST)!!
+                if (modList.getChildren(null).size > 1) {
+                    modList.removeChild(modList.getFirstChildWithType(ABSTRACT_KEYWORD)!!)
+                    if (modList.firstChildNode.isWhiteSpace()) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt:54]: If `abstract` is not the first modifier, you need to remove different node with space

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/test/resources/test/paragraph6/abstract_classes/ShouldRemoveAbstractKeywordTest.kt [hunk 5]
```diff
@@ -8,6 +8,10 @@ abstract class Some() {
     abstract inner class Any {
         fun func(){}
     }
+
+    inner abstract class Second {
```
Comment (petertrr) [inline diktat-rules/src/test/resources/test/paragraph6/abstract_classes/ShouldRemoveAbstractKeywordTest.kt:12]: `@Annotated abstract inner`?)

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+                if (modList.getChildren(null).size > 1) {
+                    val abstractKeyword = modList.getFirstChildWithType(ABSTRACT_KEYWORD)!!
+
+                    // we are deleting one keyword, so we need to delete extra space
+                    val spaceInModifiers = if (abstractKeyword == modList.lastChildNode) {
+                        modList.treeNext
+                    } else {
+                        abstractKeyword.treeNext
+                    }
+                    modList.removeChild(modList.getFirstChildWithType(ABSTRACT_KEYWORD)!!)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt:62]:
```suggestion
                    modList.removeChild(abstractKeyword)
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+                    if (spaceInModifiers != null && spaceInModifiers.isWhiteSpace()) {
+                        modList.removeChild(spaceInModifiers)
+                    }
+                } else {
+                    classNode.removeChild(modList)
+                    if (classNode.firstChildNode.isWhiteSpace()) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt:68]: Just to be safe - I would suggest to check and remove `modList.treeNext` here. For example, KDoc before class will probably be the first child node, because it usually goes before modifiers.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+
+        if (functions.isNotEmpty() && functions.none { hasAbstractModifier(it) }) {
+            CLASS_SHOULD_NOT_BE_ABSTRACT.warnAndFix(configRule, emitWarn, isFixMode, identifier, node.startOffset, node) {
+                val modList = classNode.getFirstChildWithType(MODIFIER_LIST)!!
+                if (modList.getChildren(null).size > 1) {
+                    val abstractKeyword = modList.getFirstChildWithType(ABSTRACT_KEYWORD)!!
+
+                    // we are deleting one keyword, so we need to delete extra space
+                    val spaceInModifiers = if (abstractKeyword == modList.lastChildNode) {
+                        modList.treeNext
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/AbstractClassesRule.kt:58]: I think more correct is to remove `abstractKeyword.treePrev`. This way we keep white space node on the same level of AST with modifier list and class identifier.

**Review by petertrr — CHANGES_REQUESTED** [review]

**Review by petertrr — APPROVED** [review]
lgtm
