### PR TITLE
Wrong braces with comments

### LINKED ISSUE #483: When braces are added to if and there is a comment on the same line, brace is added to the comment
## Describe the bug
```kotlin
fun foo() {
    if (condition) // comment
        foo()
}
```
is corrected into
```kotlin
fun foo() {
    if (condition)  // comment {
        foo()
    }
}
```

## Environment information
* diktat version: 0.1.3

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
    Fixed bug
closes #483

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt [hunk 1]
```diff
@@ -51,6 +54,11 @@ import org.jetbrains.kotlin.psi.KtTryExpression
  * - braces around `else`/`catch`/`finally`/`while` (in `do-while` loop)
  */
 class BlockStructureBraces(private val configRules: List<RulesConfig>) : Rule("block-structure") {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt:56]: Are you moving comments when the brace is not yet added, or are you moving them after? Because in the latter case it means that for some time the AST is not entirely valid. Is brace added in this rule too?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt (hunk 1 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt:56]: This rule checks spaces near braces, if there aren't braces - this rule won't work.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt [hunk 2]
```diff
@@ -178,6 +186,15 @@ class BlockStructureBraces(private val configRules: List<RulesConfig>) : Rule("b
                 if (braceSpace == null || braceSpace.elementType != WHITE_SPACE) {
                     node.addChild(PsiWhiteSpaceImpl(" "), nodeBefore)
                 } else {
+                    if (braceSpace.treePrev.elementType in COMMENT_TYPE) {
+                        val commentBefore = braceSpace.treePrev
+                        if (commentBefore.treePrev.elementType == WHITE_SPACE){
+                            commentBefore.treeParent.removeChild(commentBefore.treePrev)
+                        }
+                        commentBefore.treeParent.removeChild(commentBefore)
+                        node.treeParent.addChild(commentBefore, node)
```
[the remark this answers is not in the document]
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt:195]: Not sure, I compared tree after fix and it was correct

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt:53]: Yes, but the issue originated from the case where the braces have been by the rule (another rule?). Does that mean that after braces are added and until comments are moved, the tree is in invalid state?

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt:53]: Right, so the issue is not because `BracesInConditionalsAndLoopsRule` inserts a brace in a wrong place, but because `BlockStructureBraces` moves it incorrectly. OK then

Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt:53]: `BracesInConditionalsAndLoopsRule` correct put braces. `BlockStructure Braces` incorrect fix spaces between braces and comment

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt (hunk 2 above)
[the remark this answers is not in the document]
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/BlockStructureBraces.kt:188]: I think it's better to have `clone()`, there could be some problems without it.

**Review by petertrr — APPROVED** [review]
lgtm
