### PR TITLE
Type alias wrong trigger

### LINKED ISSUE #317: False-positive in TYPE_ALIAS inspection
`typealias RulesConfigReaderBase = JsonResourceConfigReader<List<RulesConfig>>`
causes
```
[INFO]    [ktlint] ...\diktat-common\src\main\kotlin\org\cqfn\diktat\common\config\rules\RulesConfigReader.kt:46:35: [TYPE_ALIAS] variable's type is too complex and should be replaced with typealias: too long type reference (cannot be auto-corrected)
```

Value assigned to a typealias shouldn't be checked on complexity.

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
   Added checker for property and fun
  closes #317

### CODE REVIEW

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/TypeAliasRuleWarnTest.kt [hunk 1]
```diff
@@ -74,4 +74,17 @@ class TypeAliasRuleWarnTest : LintTestBase(::TypeAliasRule) {
                 rulesConfigList = rulesConfigListShortType
         )
     }
+
+    @Test
+    @Tag(WarningNames.TYPE_ALIAS)
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/TypeAliasRuleWarnTest.kt:79]: Please also add test with typalias declaration

Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/TypeAliasRuleWarnTest.kt:79]: Please also add test with typealias declaration

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/TypeAliasRule.kt [hunk 2]
```diff
@@ -30,7 +32,7 @@ class TypeAliasRule(private val configRules: List<RulesConfig>) : Rule("type-ali
         emitWarn = emit
         isFixMode = autoCorrect
 
-        if (node.elementType == TYPE_REFERENCE) {
+        if (node.elementType == TYPE_REFERENCE && (node.treeParent.elementType == FUN || node.treeParent.elementType == PROPERTY)) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/TypeAliasRule.kt:35]: I think it's better to add exclusions and not inclusions: for example, this rule should check types of function parameters, which are not direct ancestors of FUN node. I think you can just check if this node is not from supertype list.

**Review by petertrr — APPROVED** [review]
