### PR TITLE
Boolean expressions rule: Remove inline comments from boolean condition while parsing

### LINKED ISSUE #959: Boolean conditions: strange logging
Diktat version:     implementation("org.cqfn.diktat:diktat-gradle-plugin:1.0.0-rc.1")
Running via gradle script.

```
 if (doubleQuoteIsClosed && singleQuoteIsClosed) {
                // FixMe: isLetterOrDigit is not supported in Kotlin 1.4, but 1.5 is not compiling right now
                if (!setOf('_', '-', '.', '"', '\'').contains(ch) && !ch.isLetterOrDigit())
                    throw TomlParsingException(
                        "Not able to parse the key: [$rawContent] as it contains invalid symbols." +
                                " In case you would like to use special symbols - use quotes.",
                        lineNo
                    )
            }
```
```
line 2:0 no viable alternative at character '/'
line 2:1 no viable alternative at character '/'
line 2:8 no viable alternative at character ':'
line 2:10 mismatched input 'isLetterOrDigit' expecting RPAREN
line 2:54 no viable alternative at character '.'
line 2:56 no viable alternative at character ','
line 2:63 no viable alternative at character '.'
```

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Changed logic
* Added tests

This pull request closes #959

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BooleanExpressionsRule.kt [hunk 1]
```diff
@@ -142,6 +144,13 @@ class BooleanExpressionsRule(configRules: List<RulesConfig>) : DiktatRule(
             operationReferenceText == "&&" || operationReferenceText == "||"
         }
 
+    private fun ASTNode.textWithoutComments() = findAllNodesWithCondition(withSelf = false, condition = {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BooleanExpressionsRule.kt:147]: why do you need to mention arguments explicitly?

**Review by akuleshov7 — APPROVED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BooleanExpressionsRule.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BooleanExpressionsRule.kt:147]: Because we somehow have `condition` as first argument and `withSelf` as second. I wanted to have usual lambda syntax withput parentheses, but apparently you can't use it even with named arguments. I guess I can just change the function's signature

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BooleanExpressionsRule.kt]: Fixed
