### PR TITLE
Fix of #86 - correct check for method names with Boolean return type

### LINKED ISSUE #86: False positive triggering of FUNCTION_BOOLEAN_PREFIX
```
[INFO]    [ktlint] C:\Users\pwx5333130\Documents\diKTat\diktat-rules\src\main\kotlin\org\cqfn\diktat\ruleset\rules\kdoc\KdocFormatting.kt:298:25: [17] functions that return the value of Boolean type should have <is> or <has> prefix: hasEmptyLineAfter
```
```
[INFO]    [ktlint] C:\Users\pwx5333130\Documents\diKTat\diktat-rules\src\main\kotlin\org\cqfn\diktat\ruleset\utils\FunctonASTNodeUtils.kt:21:13: [17] functions that return the value of Boolean type should have <is> or <has> prefix: hasParametersKDoc
```

```
[INFO]    [ktlint] C:\Users\pwx5333130\Documents\diKTat\diktat-rules\src\main\kotlin\org\cqfn\diktat\ruleset\utils\KDocUtils.kt:20:23: [17] functions that return the value of Boolean type should have <is> or <has> prefix: hasKnownKDocTag
```

```
[INFO]    [ktlint] C:\Users\pwx5333130\Documents\diKTat\diktat-rules\src\main\kotlin\org\cqfn\diktat\ruleset\utils\StringUtils.kt:23:12: [17] functions that return the value of Boolean type should have <is> or <has> prefix: isASCIILettersAndDigits
```

Probably because this is an extension function.

### PR DESCRIPTION
**Pull request by petertrr**
This fixes #86. Actually, there was a flaw in logic not covered with tests, so that issue was only a consequence.

### What's done:
* Fixes bug logic
* Added tests

### CODE REVIEW

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt [hunk 1]
```diff
@@ -310,5 +310,32 @@ class IdentifierNamingWarnTest {
         )
     }
 
+    @Test
+    fun `FUNCTION_BOOLEAN_PREFIX - positive example`() {
```
Comment (akuleshov7) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/IdentifierNamingWarnTest.kt:314]: please add this tests to documentation
