### PR TITLE
Recommendation 4.3.1 avoid nullable types

### LINKED ISSUE #294: Recommendation 4.3.1: avoid declaration of variables of nullable types, especially of types from Kotlin stdlib.
To avoid NullPointerException and help compiler checks to prevent NPE try to avoid usage of nullable types (with "?" symbol).
Not recommended:
```kotlin 
val a: Int? = 0
```

Recommended:
```kotlin 
val a: Int = 0
```

Nevertheless, if you use Java libraries extensively you'll have to use nullable types and enrich your code with '!!' and '?' symbols.
But at least for Kotlin stdlib (declared in [official documentation](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/)) avoid using nullable types. 
Try to use initializers for empty collections. For example: if you want to initialise list instead of using `null` use `emptyList()`.

Not recommended:
```kotlin 
val a: List<Int>? = null 
```

Recommended:
```kotlin 
val a: List<Int> = emptyList() 
```

### PR DESCRIPTION
**Pull request by kentr0w**
## Actions checklist
* [x] Implemented Rule, added Warnings
* [x] Added tests on checks
* [ ] Added tests on fixers
* [ ] Updated diktat-analysis.yml
* [ ] Updated available-rules.md
* [x] closes #294 

## Fixme
    Add fix logic

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+        val reference = node.findChildByType(TYPE_REFERENCE)!!.findChildByType(NULLABLE_TYPE)!!.findChildByType(USER_TYPE)?.findChildByType(REFERENCE_EXPRESSION)
+                ?: return
+
+        when (reference.text) {
+            "Int", "Short", "Byte" -> replaceValue(node, INTEGER_CONSTANT, INTEGER_LITERAL, "0")
+            "Double", "Float" -> replaceValue(node, FLOAT_CONSTANT, FLOAT_LITERAL, "0.0")
+            "Long" -> replaceValue(node, INTEGER_CONSTANT, INTEGER_LITERAL, "0L")
+            "Char" -> replaceValue(node, CHARACTER_CONSTANT, CHARACTER_LITERAL, "\'\'")
+            "String" -> replaceValueForString(node)
+            "List" -> replaceValueByText(node, "emptyList()")
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:64]: these are all types you know in Kotlin? :)

Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:64]: No) I haven't finished yet

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:64]: You can open pull request as draft: all CI checks will still be performed, but it will be explicitly marked as not ready for review

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+        isFixMode = autoCorrect
+        emitWarn = emit
+
+        if (node.elementType == PROPERTY)
+            checkProperty(node)
+    }
+
+    private fun checkProperty(node: ASTNode) {
+        if (node.hasChildOfType(VAL_KEYWORD) && node.hasChildOfType(EQ) && node.hasChildOfType(TYPE_REFERENCE) && node.hasChildOfType(NULL)) {
+            NULLABLE_PROPERTY_TYPE.warnAndFix(configRules, emitWarn, isFixMode, "initialize explicitly", node.findChildByType(NULL)!!.startOffset) {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:48]: I am pretty sure this your fixes will break Java to Kotlin compatibility. 
What if someone will use a function from Java that will return type that can be null (I forgot how is it called in Kotlin)

Comment (akuleshov7) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:48]: They are called nullable or not https://kotlinlang.org/docs/reference/java-interop.html#notation-for-platform-types

Comment (akuleshov7) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt]: got it, you check only assigned vals with null

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+        if (node.hasChildOfType(VAL_KEYWORD) && node.hasChildOfType(EQ) && node.hasChildOfType(TYPE_REFERENCE) && node.hasChildOfType(NULL)) {
+            val fixedParam = isFixable(node)
+            NULLABLE_PROPERTY_TYPE.warnAndFix(configRules, emitWarn, isFixMode, "initialize explicitly",
+                    node.findChildByType(NULL)!!.startOffset, node, fixedParam != null) {
+                if (fixedParam != null) findSubstitution(node, fixedParam)
+            }
+        }
+    }
+
+    private fun isFixable(node: ASTNode): FixedParam? {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:58]: You shouldn't start method names with `is` if their result is not boolean.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+    private fun findFixableParam(node: ASTNode): FixedParam? {
+        val reference = node.findChildByType(TYPE_REFERENCE)!!.findChildByType(NULLABLE_TYPE)!!.findChildByType(USER_TYPE)?.findChildByType(REFERENCE_EXPRESSION)
+                ?: return null
+        return when (reference.text) {
+            "Boolean" -> FixedParam(BOOLEAN_CONSTANT, TRUE_KEYWORD, "true")
+            "Int", "Short", "Byte" -> FixedParam(INTEGER_CONSTANT, INTEGER_LITERAL, "0")
+            "Double" -> FixedParam(FLOAT_CONSTANT, FLOAT_LITERAL, "0.0")
+            "Float" -> FixedParam(FLOAT_CONSTANT, FLOAT_LITERAL, "0.0F")
+            "Long" -> FixedParam(INTEGER_CONSTANT, INTEGER_LITERAL, "0L")
+            "Char" -> FixedParam(CHARACTER_CONSTANT, CHARACTER_LITERAL, "\'\'")
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:74]: There is no such thing as empty character literal in kotlin

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt [hunk 5]
```diff
@@ -0,0 +1,136 @@
...
+        else
+            replaceValueByText(node, fixedParam.textNode)
+    }
+
+    @Suppress("UnsafeCallOnNullableType")
+    private fun replaceValueByText(node: ASTNode, nodeText: String) {
+        val newNode = KotlinParser().createNode(nodeText)
+        if (newNode.elementType == CALL_EXPRESSION) {
+            node.addChild(newNode, node.findChildByType(NULL))
+            node.removeChild(node.findChildByType(NULL)!!)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:114]:
```suggestion
            node.replaceChild(newNode, node.findChildByType(NULL))
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt [hunk 6]
```diff
@@ -0,0 +1,136 @@
...
+    @Suppress("UnsafeCallOnNullableType")
+    private fun replaceValueForString(node: ASTNode) {
+        val value = CompositeElement(STRING_TEMPLATE)
+        node.addChild(value, node.findChildByType(NULL)!!)
+        node.removeChild(node.findChildByType(NULL)!!)
+        value.addChild(LeafPsiElement(OPEN_QUOTE, ""))
+        value.addChild(LeafPsiElement(CLOSING_QUOTE, ""))
+    }
+
+    data class FixedParam(val insertConstantType: IElementType?, val insertType: IElementType?, val textNode: String, val isString: Boolean = false)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:135]:
```suggestion
    private data class FixedParam(val insertConstantType: IElementType?, val insertType: IElementType?, val textNode: String, val isString: Boolean = false)
```

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:135]: Also, why is second property called `insertConstantType`? As far as I can tell from code it is type of a composite element which will be inserted into code, isn't it?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt [hunk 7]
```diff
@@ -0,0 +1,136 @@
...
+
+    @Suppress("UnsafeCallOnNullableType")
+    private fun checkProperty(node: ASTNode) {
+        if (node.hasChildOfType(VAL_KEYWORD) && node.hasChildOfType(EQ) && node.hasChildOfType(TYPE_REFERENCE)) {
+            if (!node.hasChildOfType(NULL) && node.findChildByType(TYPE_REFERENCE)!!.findAllNodesWithSpecificType(QUEST).isNotEmpty()) {
+                NULLABLE_PROPERTY_TYPE.warn(configRules, emitWarn, isFixMode, "don't use nullable type",
+                        node.findChildByType(TYPE_REFERENCE)!!.startOffset, node)
+            } else if (node.hasChildOfType(NULL)) {
+                val fixedParam = findFixableParam(node)
+                NULLABLE_PROPERTY_TYPE.warnAndFix(configRules, emitWarn, isFixMode, "initialize explicitly",
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:59]:
```suggestion
                NULLABLE_PROPERTY_TYPE.warnAndFix(configRules, emitWarn, isFixMode, "avoid initialization with null",
```

File: diktat-rules/src/test/resources/test/paragraph3/nullable/NullPrimitiveTest.kt [hunk 8]
```diff
@@ -0,0 +1,10 @@
+package test.paragraph3.nullable
+
+class A {
+    val a: Int? = null
```
Comment (petertrr) [inline diktat-rules/src/test/resources/test/paragraph3/nullable/NullPrimitiveTest.kt:4]: I think we also should change type to non-nullable here?

**Review by petertrr — CHANGES_REQUESTED** [review]

**Review by petertrr — CHANGES_REQUESTED** [review]
Take a look at snapshot check:
`[INFO]    [ktlint] /home/runner/work/diKTat/diKTat/diktat-common/src/test/kotlin/org/cqfn/diktat/test/ConfigReaderTest.kt:10:30: [NULLABLE_PROPERTY_TYPE] try to avoid use of nullable types: don't use nullable type (cannot be auto-corrected)`
You should check assigned value before issuing a warning. You absolutely shouldn't suggest to change type if right hand side expression returns nullable value.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt [hunk 9]
```diff
@@ -0,0 +1,140 @@
...
+        emitWarn = emit
+
+        if (node.elementType == PROPERTY)
+            checkProperty(node)
+    }
+
+    @Suppress("UnsafeCallOnNullableType")
+    private fun checkProperty(node: ASTNode) {
+        if (node.hasChildOfType(VAL_KEYWORD) && node.hasChildOfType(EQ) && node.hasChildOfType(TYPE_REFERENCE)) {
+            if (!node.hasChildOfType(NULL) && node.findChildByType(TYPE_REFERENCE)!!.findAllNodesWithSpecificType(QUEST).isNotEmpty() &&
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:54]:
```suggestion
            if (!node.hasChildOfType(NULL) && node.findChildByType(TYPE_REFERENCE)!!.findChildByType(QUEST) != null &&
```
In order to not trigger on types like `List<Int?>`

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt [hunk 10]
```diff
@@ -0,0 +1,140 @@
...
+                    !node.hasChildOfType(DOT_QUALIFIED_EXPRESSION) && !node.hasChildOfType(CALL_EXPRESSION)) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:55]: I think that when property is initialized with some collection factory method like `emptyList()` and has nullable type, we still should change type to non-nullable.

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt (hunk 9 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:60]: But element of type `QUEST` isn't child of `TYPE_REFERENCE`

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:60]: OK, I mean that you should check only `?` on top-level type reference, while `findAllNodesWithSpecificType` can give you more nested nodes

Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt]: I misunderstood your comment)  Сorrected

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt [hunk 11]
```diff
@@ -46,15 +50,21 @@ class NullableTypeRule(private val configRules: List<RulesConfig>) : Rule("nulla
...
-            if (!node.hasChildOfType(NULL) && node.findChildByType(TYPE_REFERENCE)!!.findAllNodesWithSpecificType(QUEST).isNotEmpty() &&
-                    !node.hasChildOfType(DOT_QUALIFIED_EXPRESSION) && !node.hasChildOfType(CALL_EXPRESSION)) {
-                NULLABLE_PROPERTY_TYPE.warn(configRules, emitWarn, isFixMode, "don't use nullable type",
-                        node.findChildByType(TYPE_REFERENCE)!!.startOffset, node)
+            val typeReferenceNode = node.findChildByType(TYPE_REFERENCE)!!
+            if (!node.hasChildOfType(NULL) &&
+                    !node.hasChildOfType(DOT_QUALIFIED_EXPRESSION) &&
+                    typeReferenceNode.hasChildOfType(NULLABLE_TYPE) &&
+                    typeReferenceNode.findChildByType(NULLABLE_TYPE)!!.hasChildOfType(QUEST)) {
+                if (node.findChildByType(CALL_EXPRESSION)?.findChildByType(REFERENCE_EXPRESSION)?.text ?: "emptyList" in allowExpression) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:64]: `?: "emptyList"`? Why?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt [hunk 12]
```diff
@@ -0,0 +1,151 @@
...
+    private fun findFixableParam(node: ASTNode): FixedParam? {
+        val reference = node.findChildByType(TYPE_REFERENCE)!!.findChildByType(NULLABLE_TYPE)!!.findChildByType(USER_TYPE)?.findChildByType(REFERENCE_EXPRESSION)
+                ?: return null
+        return when (reference.text) {
+            "Boolean" -> FixedParam(BOOLEAN_CONSTANT, TRUE_KEYWORD, "true")
+            "Int", "Short", "Byte" -> FixedParam(INTEGER_CONSTANT, INTEGER_LITERAL, "0")
+            "Double" -> FixedParam(FLOAT_CONSTANT, FLOAT_LITERAL, "0.0")
+            "Float" -> FixedParam(FLOAT_CONSTANT, FLOAT_LITERAL, "0.0F")
+            "Long" -> FixedParam(INTEGER_CONSTANT, INTEGER_LITERAL, "0L")
+            "Char" -> FixedParam(CHARACTER_CONSTANT, CHARACTER_LITERAL, "")
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NullableTypeRule.kt:89]: Does this mean you will try to assign empty string into a `Char` property? You could use something like `Char.MIN_VALUE` here instead.

File: info/available-rules.md [hunk 13]
```diff
@@ -77,5 +77,6 @@
 |    3 |      3.2 | WRONG_MULTIPLE_MODIFIERS_ORDER          | Check: if multiple modifiers sequence is in the wrong order                                                                                                                  | yes | -                         | - |
 |    3 |      3.14.2 | STRING_TEMPLATE_CURLY_BRACES               | Check: warns if there is redundant curly braces in string template<br> Fix: deletes curly braces                 | yes | - | + |
 |    3 |    3.14.2  | STRING_TEMPLATE_QUOTES                      | Check: warns if there are redundant quotes in string template<br> Fix: deletes quotes and $ symbol                   | yes | - | + |
+|    4 |     4.3.1| NULLABLE_PROPERTY_TYPE                  | Check: if initialize val by null                                                                                                                                             | yes | -                         | - |
```
Comment (petertrr) [inline info/available-rules.md:80]:
```suggestion
|    4 |     4.3.1| NULLABLE_PROPERTY_TYPE                  | Check: warns if immutable property is initialized with null or if immutable property can have non-nullable type instead of nullable<br>Fix: suggests initial value instead of null or changes immutable property type                    | yes | -                         | - |
```

**Review by petertrr — APPROVED** [review]
Please change initial value for Char, apart from this LGTM

**Review by petertrr — CHANGES_REQUESTED** [review]
Wait, I found this:
`[INFO]    [ktlint] /home/runner/work/diKTat/diKTat/diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/IdentifierNaming.kt:258:29: [NULLABLE_PROPERTY_TYPE] try to avoid use of nullable types: don't use nullable type (cannot be auto-corrected)`
and this:
`[INFO]    [ktlint] /home/runner/work/diKTat/diKTat/diktat-rules/src/test/kotlin/org/cqfn/diktat/util/DiktatRuleSetProvider4Test.kt:20:34: [NULLABLE_PROPERTY_TYPE] try to avoid use of nullable types: don't use nullable type (cannot be auto-corrected)`

Both warnings are clearly false-positive

**Review by petertrr — APPROVED** [review]
