### PR TITLE
Rule 5.1.1

### LINKED ISSUE #335: Rule 5.1.1 Avoid too long functions, no more than 30 lines (non-empty, non-comment)
The function should be able to be displayed on one screen and only implement one certain logic. Too long function often means that the function is too complicated and can be split or be more primitive.

Exception: Some functions that implement complex algorithms may exceed 30 lines due to the aggregation and comprehensiveness. Linter warnings for such functions can be suppressed.

Even if a long function works very well right now, once someone else modifies it, new problems or bugs may appear due to the complex logic. It is recommended to split such functions into several separated functions that are shorter and easier to manage, so that others can read and modify the code properly.

### PR DESCRIPTION
**Pull request by kentr0w**
## Actions checklist
* [x] Implemented Rule, added Warnings
* [x] Added tests on checks
* [] Added tests on fixers
* [x] Updated diktat-analysis.yml
* [x] Updated available-rules.md
* [x] closes #335

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+        val configuration = FunctionLengthConfiguration(
+                configRules.getRuleConfig(TOO_LONG_FUNCTION)?.configuration ?: mapOf()
+        )
+
+        if (node.elementType == FUN)
+            checkFun(node.copyElement(), configuration.maxFunctionLength)
+    }
+
+    private fun checkFun(node: ASTNode, maxFunctionLength: Long) {
+        node.findAllNodesWithSpecificTypes(FUNCTION_ALLOW_COMMENT).forEach { it.treeParent.removeChild(it) }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt:42]: But this will permanently damage AST, won't it?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+        val functionText = node.text.replace("(?m)^[ \\t]*\\r?\\n".toRegex(), "")
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt:43]: I think after you remove comments you can just filter `lines()`

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 3]
```diff
@@ -266,6 +266,16 @@ fun ASTNode.findAllNodesWithSpecificType(elementType: IElementType, withSelf: Bo
     }
 }
 
+/**
+ * This method performs tree traversal and returns all nodes with specific element types
+ */
+fun ASTNode.findAllNodesWithSpecificTypes(elementTypes: List<IElementType>, withSelf: Boolean = true): List<ASTNode> {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:272]: I though we already have such method?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt (hunk 1 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt:42]: No, because I passed a copy of the node

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+        if (node.elementType == FUN)
+            checkFun(node.copyElement(), configuration.maxFunctionLength)
+    }
+
+    private fun checkFun(node: ASTNode, maxFunctionLength: Long) {
+        node.findAllNodesWithCondition({it.elementType in FUNCTION_ALLOW_COMMENT }).forEach { it.treeParent.removeChild(it) }
+        val functionText = node.text.lines().filter { it.isNotBlank() }
+        if (functionText.size > maxFunctionLength)
+            TOO_LONG_FUNCTION.warn(configRules,emitWarn, isFixMode,
+                    "max length is $maxFunctionLength, but you have ${functionText.size}", node.startOffset, node)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt:47]: Take a look at snapshot run: all offsets from your warning point to 1:1. I think it's because you take offset of copied node.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt [hunk 5]
```diff
@@ -17,6 +17,8 @@ val KOTLIN = KtTokens.KEYWORDS.types.map { line -> line.toString() }
 
 val loggerPropertyRegex = "(log|LOG|logger)".toRegex()
 
+fun String.isNotBlankAndEmpty() = isNotEmpty() && isNotBlank()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt:20]: This is not needed any more?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+                       emit: (offset: Int, errorMessage: String, canBeAutoCorrected: Boolean) -> Unit) {
+        emitWarn = emit
+        isFixMode = autoCorrect
+
+        val configuration = FunctionLengthConfiguration(
+                configRules.getRuleConfig(TOO_LONG_FUNCTION)?.configuration ?: mapOf()
+        )
+
+        if (node.elementType == FUN) {
+            val copyNode = if (configuration.isIncludeHeader) node.copyElement() else (node.psi as KtFunction).bodyExpression!!.node
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt:41]: Abstract functions don't have body, will they be correctly handled by this rule?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+            checkFun(copyNode, configuration.maxFunctionLength, node.startOffset)
+        }
+    }
+
+    private fun checkFun(node: ASTNode, maxFunctionLength: Long, startOffset: Int) {
+        node.findAllNodesWithCondition({ it.elementType in FUNCTION_ALLOW_COMMENT }).forEach { it.treeParent.removeChild(it) }
+        val functionText = node.text.lines().filter { it.isNotBlank() }
+        if (functionText.size > maxFunctionLength)
+            TOO_LONG_FUNCTION.warn(configRules, emitWarn, isFixMode,
+                    "max length is $maxFunctionLength, but you have ${functionText.size}", startOffset, node)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt:51]: If you pass copy of the node here, will suppress from higher level still be working?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt (hunk 7 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt:52]: Yes, I added a test

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt (hunk 6 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt]: No, fixed

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/FunctionLengthWarnTest.kt [hunk 8]
```diff
@@ -124,6 +124,31 @@ class FunctionLengthWarnTest : LintTestBase(::FunctionLength) {
...
+    @Test
+    @Tag(WarningNames.TOO_LONG_FUNCTION)
+    fun `check suppress`() {
+        lintMethod(
+                """
+                    |class A() {
+                    |   val x = 10
+                    |   val y  = 11
+                    |   
+                    |   @Suppress("TOO_LONG_FUNCTION")
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/FunctionLengthWarnTest.kt:136]: What if suppress is on class of file level?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt (hunk 7 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt:52]: I mean suppress not on a function, but on higher levels. Our algorithm checks if any parents of this node have suppress and annotation on a class should suppress inspection everywhere in this class

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/FunctionLengthWarnTest.kt (hunk 8 above)
Comment (kentr0w) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/FunctionLengthWarnTest.kt]: Now it works

File: diktat-analysis.yml [hunk 9]
```diff
@@ -280,4 +280,10 @@
...
   enabled: true
-  configuration: {}
\ No newline at end of file
+  configuration: {}
+# Checks that function length isn't too long
+- name: TOO_LONG_FUNCTION
+  enabled: true
+  configuration:
+    maxFunctionLength: "30" # max length of function
+    isIncludeHeader: "true" # count function's header
```
Comment (petertrr) [inline diktat-analysis.yml:289]:
```suggestion
    isIncludeHeader: "false" # count function's header
```
For our own code check let's be consistent to setup that we already have.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt [hunk 10]
```diff
@@ -0,0 +1,60 @@
...
+        )
+
+        if (node.elementType == FUN) {
+            checkFun(node, configuration)
+        }
+    }
+
+    private fun checkFun(node: ASTNode, configuration: FunctionLengthConfiguration) {
+        val copyNode = if (configuration.isIncludeHeader) node.copyElement()
+        else (node.psi as KtFunction).bodyExpression?.node ?: return
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/FunctionLength.kt:47]:
```suggestion
        val copyNode = if (configuration.isIncludeHeader) {
            node.copyElement()
        } else {
            (node.psi as KtFunction).bodyExpression?.node ?: return
        }
```

**Review by petertrr — APPROVED** [review]
LGTM
