### PR TITLE
Bugfix. FP of LOCAL_VARIABLE_EARLY_DECLARATION with other variables and a loop

### LINKED ISSUE #581: FP of LOCAL_VARIABLE_EARLY_DECLARATION with other variables and a loop
## Describe the bug
```kotlin
    private fun collectAllExtensionFunctions(node: ASTNode): SimilarSignatures {
        val extensionFunctionList = node.findAllNodesWithSpecificType(FUN).filter { it.hasChildOfType(TYPE_REFERENCE) && it.hasChildOfType(DOT) }
        val distinctFunctionSignatures = mutableMapOf<FunctionSignature, ASTNode>()  // maps function signatures on node it is used by
        val extensionFunctionsPairs = mutableListOf<Pair<ExtensionFunction, ExtensionFunction>>()  // pairs extension functions with same signature

        extensionFunctionList.forEach { func ->
            val functionName = (func.psi as KtNamedFunction).name!!
            // List<String> is used to show param names in warning
            val params = (func.getFirstChildWithType(VALUE_PARAMETER_LIST)!!.psi as KtParameterList).parameters.map { it.name!! }
            val returnType = func.findChildAfter(COLON, TYPE_REFERENCE)?.text
            val className = func.findChildBefore(DOT, TYPE_REFERENCE)!!.text
            val signature = FunctionSignature(functionName, params, returnType)

            if (distinctFunctionSignatures.contains(signature)) {
                val secondFuncClassName = distinctFunctionSignatures[signature]!!.findChildBefore(DOT, TYPE_REFERENCE)!!.text
                extensionFunctionsPairs.add(Pair(
                    ExtensionFunction(secondFuncClassName, signature, distinctFunctionSignatures[signature]!!),
                    ExtensionFunction(className, signature, func)))
            } else {
                distinctFunctionSignatures[signature] = func
            }
        }

        return extensionFunctionsPairs
    }
```
=>
```
ExtensionFunctionsSameNameRule.kt:82:9: [LOCAL_VARIABLE_EARLY_DECLARATION] local variables should be declared close to the line where they are first used: <distinctFunctionSignatures> is declared on line <82> and is used for the first time on line <85>
```

## Environment information
* diktat version: 0.1.5

### PR DESCRIPTION
**Pull request by aktsay6**
### What's done:
 * Fixed bugs
 * Added tests
 
This pull request closes #581

### CODE REVIEW

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LocalVariablesWarnTest.kt [hunk 1]
```diff
@@ -483,9 +483,7 @@ class LocalVariablesWarnTest : LintTestBase(::LocalVariablesRule) {
                     |        foo(a, b, c)
                     |    }
                     |}
-                """.trimMargin(),
-            LintError(2, 5, ruleId, "${LOCAL_VARIABLE_EARLY_DECLARATION.warnText()} ${warnMessage("a", 2, 6)}", false),
-            LintError(3, 5, ruleId, "${LOCAL_VARIABLE_EARLY_DECLARATION.warnText()} ${warnMessage("b", 3, 6)}", false)
+                """.trimMargin()
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LocalVariablesWarnTest.kt:486]: Please change this test's name too

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LocalVariablesWarnTest.kt [hunk 2]
```diff
@@ -573,4 +571,36 @@ class LocalVariablesWarnTest : LintTestBase(::LocalVariablesRule) {
                 """.trimMargin()
         )
     }
+
+    @Test
+    @Tag(WarningNames.LOCAL_VARIABLE_EARLY_DECLARATION)
+    fun `should not trigger on space after last val`() {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LocalVariablesWarnTest.kt:577]: You should definitely make this example smaller, leaving only the part that is essential to reproduce the error.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt [hunk 3]
```diff
@@ -94,12 +96,28 @@ class LocalVariablesRule(private val configRules: List<RulesConfig>) : Rule("loc
...
+        }
+
         // need to check that properties are declared consecutively with only maybe empty lines
         properties
             .sortedBy { it.node.getLineNumber() }
-            .zip(properties.size - 1 downTo 0)
-            .forEach { (property, offset) ->
-                checkLineNumbers(property, statement.node.getLineNumber(), offset)
+            .let { it as MutableList }
+            .zip(((properties.size - 1) downTo 0).map { it + numLinesAfterLastProp })
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt:114]:
```suggestion
            .zip(
                (properties.size - 1 downTo 0).map { it + numLinesAfterLastProp }
            )
```
While compliant with code style, for me it's not very readable in one line.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt [hunk 4]
```diff
@@ -94,12 +96,28 @@ class LocalVariablesRule(private val configRules: List<RulesConfig>) : Rule("loc
...
+            0
+        }
+
         // need to check that properties are declared consecutively with only maybe empty lines
         properties
             .sortedBy { it.node.getLineNumber() }
-            .zip(properties.size - 1 downTo 0)
-            .forEach { (property, offset) ->
-                checkLineNumbers(property, statement.node.getLineNumber(), offset)
+            .let { it as MutableList }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt:113]:
```suggestion
            .let { it.toMutableList() }
```
Also, why is it needed?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt [hunk 5]
```diff
@@ -94,12 +96,28 @@ class LocalVariablesRule(private val configRules: List<RulesConfig>) : Rule("loc
...
+        val numLinesAfterLastProp = if (properties.last().node.treeNext.elementType == WHITE_SPACE) {
+            // minus one is needed to except \n after property
+            properties
+                    .last()
+                    .node
+                    .treeNext
+                    .numNewLines() - 1
+        } else {
+            0
+        }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt:108]:
```suggestion
        val numLinesAfterLastProp =
            properties
                    .last()
                    .node
                    .treeNext
                    .takeIf { it.elementType == WHITE_SPACE }
                    ?.let {
                        // minus one is needed to except \n after property
                        it.numNewLines() - 1 
                    }
                    ?: 0
```
Personally, I'd rewrite it like this, to avoid getting same node two times.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt [hunk 6]
```diff
@@ -94,12 +96,28 @@ class LocalVariablesRule(private val configRules: List<RulesConfig>) : Rule("loc
...
-            .zip(properties.size - 1 downTo 0)
-            .forEach { (property, offset) ->
-                checkLineNumbers(property, statement.node.getLineNumber(), offset)
+            .let { it as MutableList }
+            .zip(((properties.size - 1) downTo 0).map { it + numLinesAfterLastProp })
+            .forEachIndexed { index, (property, offset) ->
+                if (index != properties.lastIndex) {
+                    checkLineNumbers(property, statement.node.getLineNumber(), offset)
+                } else {
+                    checkLineNumbers(property, statement.node.getLineNumber(), 0)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/identifiers/LocalVariablesRule.kt:119]: So, you increase offset by number of empty lines after the last property, which sort of makes sense. But then you ignore this adjustment for this last property. What exactly is going on here? Please add some more comments in code.

**Review by petertrr — CHANGES_REQUESTED** [review]
We also have several suppressed `LOCAL_VARIABLE_EARLY_DECLARATION` in our code, please find the ones that will be fixed by your change and un-suppress them

**Review by petertrr — APPROVED** [review]
LGTM
