### PR TITLE
Rule 5.1.2: Avoid deep nesting of function code blocks

### LINKED ISSUE #336: Rule 5.1.2 Avoid deep nesting of function code blocks. It should be limited to 4 levels
The nesting depth of the code block of a function is the depth of mutual inclusion between the code control blocks in the function (for example: if, for, while, when, etc.). Each level of nesting will increase the mental effort when reading code, because you need to maintain a current "stack" in your mind (for example, entering conditional statements, entering loops, etc.). Exception: The nesting levels of lambda expressions, local classes, and anonymous classes in functions are calculated based on the innermost function, and the nesting levels of enclosing methods are not accumulated. To avoid a confusion of code readers functional decomposition should be done. This will help reader to switch between context.

### PR DESCRIPTION
**Pull request by kentr0w**
## Actions checklist
* [x] Implemented Rule, added Warnings
* [x] Added tests on checks
* [ ] Added tests on fixers
* [x] Updated diktat-analysis.yml
* [x] Updated available-rules.md
* [x] closes #336

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+                IF -> Pair(it.findChildByType(THEN)?.findChildByType(BLOCK), it.findChildByType(ELSE)?.findChildByType(BLOCK))
+                WHEN -> Pair(it, null)
+                WHEN_ENTRY -> Pair(it.findChildByType(BLOCK), null)
+                FUN -> Pair(it.findChildByType(BLOCK), null)
+                else -> Pair(it.findChildByType(BODY)?.findChildByType(BLOCK), null)
+            }.let { pair ->
+                pair.let {
+                    pair.first?.let { it1 -> result.add(it1) }
+                    pair.second?.let { it2 -> result.add(it2) }
+                }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:85]:
```suggestion
            }.let { pair ->
                    pair.first?.let { result.add(it) }
                    pair.second?.let { result.add(it) }
```

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+    }
+
+    private fun findBlocks(node: ASTNode): List<ASTNode> {
+        val result = mutableListOf<ASTNode>()
+        node.getChildren(null).forEach { childNode ->
+            when (childNode.elementType) {
+                IF -> Pair(childNode.findChildByType(THEN)?.findChildByType(BLOCK),
+                        (childNode.findChildByType(ELSE)?.findChildByType(BLOCK)
+                                ?: if(childNode.findChildByType(ELSE)?.findChildByType(IF) != null)
+                                    childNode.findChildByType(ELSE) else null))
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:90]:
```suggestion
                                ?: childNode.findChildByType(ELSE)?.takeIf { it.findChildByType(IF) != null })
```
just to reduce amount of conditional operators

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+                WHEN -> Pair(childNode, null)
+                WHEN_ENTRY -> Pair(childNode.findChildByType(BLOCK), null)
+                FUN -> Pair(childNode.findChildByType(BLOCK), null)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:93]: I think `TRY` also has similar structure to `IF`

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/NestedFunctionBlockWarnTest.kt [hunk 4]
```diff
@@ -0,0 +1,187 @@
...
+import generated.WarningNames
+import org.cqfn.diktat.common.config.rules.RulesConfig
+import org.cqfn.diktat.ruleset.rules.DIKTAT_RULE_SET_ID
+import org.cqfn.diktat.ruleset.constants.Warnings.NESTED_BLOCK
+import org.cqfn.diktat.ruleset.rules.NestedFunctionBlock
+import org.cqfn.diktat.util.LintTestBase
+import org.junit.jupiter.api.Tag
+import org.junit.jupiter.api.Test
+
+class NestedFunctionBlockWarnTest : LintTestBase(::NestedFunctionBlock) {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter5/NestedFunctionBlockWarnTest.kt:13]: Please add examples when functions are declared inside a class

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+
+    override fun visit(node: ASTNode,
+                       autoCorrect: Boolean,
+                       emit: (offset: Int, errorMessage: String, canBeAutoCorrected: Boolean) -> Unit) {
+        emitWarn = emit
+        isFixMode = autoCorrect
+
+        when (node.elementType) {
+            FUN, FUNCTION_LITERAL -> handleFunForNestedBlocks(node, configuration.maxNestedBlockQuantity)
+            CLASS, OBJECT_DECLARATION -> handleLocalCLassForNestedBlocks(node, configuration.maxNestedBlockQuantity)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:50]: Won't you check functions declared inside a class twice?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt [hunk 6]
```diff
@@ -0,0 +1,106 @@
...
+import org.cqfn.diktat.common.config.rules.getRuleConfig
+import org.cqfn.diktat.ruleset.constants.Warnings.NESTED_BLOCK
+import org.jetbrains.kotlin.com.intellij.lang.ASTNode
+import org.jetbrains.kotlin.com.intellij.psi.tree.TokenSet
+import org.jetbrains.kotlin.psi.KtClass
+
+/**
+ * Rule 5.1.2 Nested blokcs
+ */
+class NestedFunctionBlock(private val configRules: List<RulesConfig>) : Rule("nested-block") {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:29]: Maybe instead of finding blocks inside specific constructions, you could find all `BLOCK`s inside a function and then for each of them count number of `BLOCK` parents until this function? Or will such or similar generic approach lose some specificity?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt (hunk 5 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:50]: No, because in `handleLocalCLassForNestedBlocks ` I check whether it is a local class.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt (hunk 6 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:23]: Yes, it looks better. Have already changed it.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+import org.jetbrains.kotlin.psi.psiUtil.parents
+
+/**
+ * Rule 5.1.2 Nested blokcs
+ */
+class NestedFunctionBlock(private val configRules: List<RulesConfig>) : Rule("nested-block") {
+
+    companion object {
+        private const val MAX_NESTED_BLOCK_COUNT = 4L
+        private val NULLIFICATION_TYPE = listOf(CLASS, FUN, OBJECT_DECLARATION, FUNCTION_LITERAL)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:27]:
```suggestion
        /**
         * Nodes of these types reset counter of nested blocks
         */
        private val NULLIFICATION_TYPE = listOf(CLASS, FUN, OBJECT_DECLARATION, FUNCTION_LITERAL)
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+                       emit: (offset: Int, errorMessage: String, canBeAutoCorrected: Boolean) -> Unit) {
+        emitWarn = emit
+        isFixMode = autoCorrect
+
+        if (node.elementType in NULLIFICATION_TYPE)
+            countNestedBlocks(node, configuration.maxNestedBlockQuantity)
+    }
+
+    private fun countNestedBlocks(node: ASTNode, maxNestedBlockCount: Long) {
+        if (node.elementType == CLASS && !(node.psi as KtClass).isLocal) return
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:48]: Is this line still needed?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+        node.findAllNodesWithSpecificType(LBRACE).reversed().forEach { blockNode ->
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:49]:
```suggestion
        node.findAllNodesWithSpecificType(LBRACE).reversed().forEach { lbraceNode ->
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt [hunk 10]
```diff
@@ -0,0 +1,67 @@
...
+            val blockParent = blockNode
+                    .parents()
+                    .takeWhile { it != node }
+                    .takeIf { parentList -> parentList.map { it.elementType }.none { it in NULLIFICATION_TYPE } }
+                    ?.count { it.hasChildOfType(LBRACE) }
+                    ?: return
+            if (blockParent > maxNestedBlockCount) {
+                NESTED_BLOCK.warn(configRules, emitWarn, isFixMode, node.findChildByType(IDENTIFIER)?.text ?: node.text,
+                        node.startOffset, node)
+                return
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:59]: Why do you return from here? Can there be several invalid blocks inside, e.g., the same class?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt (hunk 10 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NestedFunctionBlock.kt:59]: Yes, I had a tests.

**Review by petertrr — APPROVED** [review]
