### PR TITLE
Copyright as code

### LINKED ISSUE #738: Copyright added from default config causes COMMENTED_OUT_CODE trigger
## Describe the bug
* Run diktat 0.3.0 with default config on file without copyright
* ???
* ~Profit~

## Environment information
* diktat version: 0.3.0

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
* [ ] Fixed bug
* [ ] Added test
* [ ] Added comment
* [ ] closes #738

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt [hunk 1]
```diff
@@ -70,8 +73,19 @@ class CommentsRule(private val configRules: List<RulesConfig>) : Rule("comments"
                         offset to ktPsiFactory.createImportDirective(ImportPath.fromString(text.substringAfter("$importKeyword "))).node
                     text.contains(packageKeyword) ->
                         offset to ktPsiFactory.createPackageDirective(FqName(text.substringAfter("$packageKeyword "))).node
-                    else ->
-                        offset to ktPsiFactory.createBlockCodeFragment(text, null).node
+                    else -> {
+                        var newNode = ktPsiFactory.createBlockCodeFragment(text, null).node
+                        val isPossibleError = newNode.findChildByType(BLOCK)!!.firstChildNode.elementType == BINARY_EXPRESSION
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt:78]: Is `!!` here because `createBlockCodeFragment` should always create block?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt [hunk 2]
```diff
@@ -70,8 +73,19 @@ class CommentsRule(private val configRules: List<RulesConfig>) : Rule("comments"
...
+                        // A check is performed for the presence of a BINARY_EXPRESSION as first child,
+                        // because the one-line copyright is perceived by the parser as a BINARY EXPRESSION
+                        if (isPossibleError) {
+                            val nodeInsideClass = ktPsiFactory.createBlockCodeFragment("class A {$text}", null).node
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt:82]: It's still not a universal solution, because it'll help only to avoid invalid top-level declarations. With `fun foo() { $text }` you'll probably still get no `ERROR_ELEMENT`s

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt [hunk 3]
```diff
@@ -293,4 +293,24 @@ class CommentedCodeTest : LintTestBase(::CommentsRule) {
...
+        lintMethod(
+            """
+            /*
+                Copyright (c) Your Company Name Here. 2010-2021
+            */
+            
+            package org.cqfn.diktat
+            
+            /*
+                x = 2 + 4 + 1
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:309]: Yep, and that should have caused warning...

**Review by petertrr — CHANGES_REQUESTED** [review]
Maybe, try to avoid false positives by possibly creating false negatives? For example, don't try to parse comment if it doesn't contain `=` or `{}` or some other special symbols that don't usually occur in plain text

**Review by petertrr — CHANGES_REQUESTED** [review]
Also please set `isCopyrightMandatory` in default config to false

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt (hunk 1 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt:78]: Yes, it is

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt [hunk 4]
```diff
@@ -55,9 +55,7 @@ class CommentedCodeTest : LintTestBase(::CommentsRule) {
            |    */
            |    return 0
            |}
-        """.trimMargin(),
-            LintError(4, 5, ruleId, "${COMMENTED_OUT_CODE.warnText()} println(a + 42)", false)
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:59]: Please change these example so that commented code triggers warning with new adjustments

Comment (kentr0w) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:59]: Fixed

Comment (petertrr) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:59]: Sorry, I meant all examples :)
There is really not much sense to have so many positive tests

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt [hunk 5]
```diff
@@ -80,7 +90,8 @@ class CommentsRule(private val configRules: List<RulesConfig>) : Rule("comments"
                     .isEmpty()
             }
             .forEach { (offset, parsedNode) ->
-                COMMENTED_OUT_CODE.warn(configRules, emitWarn, isFixMode, parsedNode.text.substringBefore("\n").trim(), offset, parsedNode)
+                COMMENTED_OUT_CODE.warn(configRules, emitWarn, isFixMode, parsedNode.text.substringBefore("\n").trim(), offset,
+                    errorNodesWithText.find { it.second == parsedNode.text }?.first ?: parsedNode)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt:94]: Is this a case for nodes that have not been parsed because do not contain code markers? If I understand correctly, in this case `parsedNode` will be `null`, do you really need to find by text?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/CompactInitialization.kt [hunk 6]
```diff
@@ -52,7 +52,7 @@ class CompactInitialization(private val configRules: List<RulesConfig>) : Rule("
      * Check property's initializer: if it is a method call, we find all consecutive statements that are this property's
      * fields accessors and wrap them in an `apply` function.
      */
-    @Suppress("UnsafeCallOnNullableType")
+    @Suppress("UnsafeCallOnNullableType", "COMMENTED_OUT_CODE")
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/CompactInitialization.kt:55]: Why? Is this false positive?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/CompactInitialization.kt [hunk 7]
```diff
@@ -81,7 +81,7 @@ class CompactInitialization(private val configRules: List<RulesConfig>) : Rule("
             }
     }
 
-    @Suppress("UnsafeCallOnNullableType", "NestedBlockDepth")
+    @Suppress("UnsafeCallOnNullableType", "NestedBlockDepth", "COMMENTED_OUT_CODE")
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/CompactInitialization.kt:84]: Same here

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt [hunk 8]
```diff
@@ -293,4 +290,58 @@ class CommentedCodeTest : LintTestBase(::CommentsRule) {
...
+            """.trimMargin(),
+            LintError(7, 13, ruleId, "${COMMENTED_OUT_CODE.warnText()} ", false),
+            LintError(10, 13, ruleId, "${COMMENTED_OUT_CODE.warnText()} x = 2+4", false),
+            LintError(14, 13, ruleId, "${COMMENTED_OUT_CODE.warnText()} ", false)
+        )
+    }
+
+    @Test
+    @Tag(WarningNames.COMMENTED_OUT_CODE)
+    fun `should not trigger with suppress`() {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:329]: Why do you need to check suppress here?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/CompactInitialization.kt (hunk 6 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/CompactInitialization.kt:55]: Because there is comment with `=`

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/CompactInitialization.kt (hunk 7 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/CompactInitialization.kt:84]: Because there is comment with `apply { foo(this) }`

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt (hunk 5 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt:94]: No, this case for `Suppress`. `parsedNode` is a new node, that we have created, it hasn't parent, so method `hasSuppress` doesn't work.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt (hunk 8 above)
Comment (kentr0w) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:329]: Because, as I added new logic for `Suppress`

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt (hunk 5 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/comments/CommentsRule.kt:94]: Oh, OK, I see

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/CompactInitialization.kt (hunk 6 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/CompactInitialization.kt:55]: And this thing is parsed correctly? 
```
statements like `name.field = value` where name == propertyName
```
 ?

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt [hunk 9]
```diff
@@ -72,9 +73,7 @@ class CommentedCodeTest : LintTestBase(::CommentsRule) {
            |//    println("This is a test string")
            |    return 0
            |}
-        """.trimMargin(),
-            LintError(4, 1, ruleId, "${COMMENTED_OUT_CODE.warnText()} println(a + 42)", false)
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:76]: Why is there no error here? Do you look for `=` in all lines or jsut the first?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt (hunk 8 above)
Comment (petertrr) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:328]: Ok

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt (hunk 9 above)
Comment (kentr0w) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:76]: Why should there be a mistake here? There isn't `=`

Comment (petertrr) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:76]: Right, github has folded two tests and I looked in the wrong place, nvm.

**Review by petertrr — APPROVED** [review]
