### PR TITLE
Bugfix. Newline rule rbrace(#617)

### LINKED ISSUE #617: NewlinesRule doesn't add line break before }
## Describe the bug
NewlinesRule doesn't add line break before }
## Expected behavior
```kotlin
fun foo() {
    val diktatExtension = project.extensions.create(DIKTAT_EXTENSION, DiktatExtension::class.java).apply {
    inputs = project.fileTree("src").apply {
        include("**/*.kt")
    }
    reporter = PlainReporter(System.out)
    }
}
```
## Observed behavior
```kotlin
fun foo() {
    val diktatExtension = project.extensions.create(DIKTAT_EXTENSION, DiktatExtension::class.java).apply {
    inputs = project.fileTree("src").apply {
        include("**/*.kt")
    }
    reporter = PlainReporter(System.out)}
}
```
## Environment information
* diktat version: 0.1.6-SNAPSHOT

### PR DESCRIPTION
**Pull request by aktsay6**
Handle of right brace case was added

This pull request closes #617

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 1]
```diff
@@ -113,11 +116,58 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
             BLOCK -> handleLambdaBody(node)
             RETURN -> handleReturnStatement(node)
             SUPER_TYPE_LIST, VALUE_PARAMETER_LIST -> handleList(node)
+            RBRACE -> handleRightBrace(node)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:119]: Shouldn't it be handled in `BlockStructureBraces` instead of `NewlinesRule`?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt [hunk 2]
```diff
@@ -144,6 +143,7 @@ class DiktatRuleSetProvider(private var diktatConfigFile: String = DIKTAT_ANALYS
             ::AvoidNestedFunctionsRule,
             ::ExtensionFunctionsSameNameRule,
             // formatting: moving blocks, adding line breaks, indentations etc.
+            ::BlockStructureBraces,
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt:146]: Wow, that turned out easy..

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt (hunk 1 above)
Comment (aktsay6) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt]: Completly forgot about it. Remade bugfix

**Review by petertrr — APPROVED** [review]
