### PR TITLE
Bugfix. CompactInitializationRule builds incorrect tree(#599)

### LINKED ISSUE #599: CompactInitializationRule builds incorrect tree
## Describe the bug
``` kotlin
fun foo() {
    val diktatExtension = project.extensions.create(DIKTAT_EXTENSION, DiktatExtension::class.java)
    diktatExtension.inputs = project.fileTree("src").apply {
        include("**/*.kt")
    }
    diktatExtension.reporter = PlainReporter(System.out)
}
```
This rule builds incorrect tree. In `FUNCTION_LITERAL` there is no `WHITE_SPACE` after `LBRACE`
## Environment information
* diktat version: 0.1.4(same for 0.1.5)

### PR DESCRIPTION
**Pull request by aktsay6**
### What's done:
  * Fixed bug

This pull request closes #599

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/CompactInitialization.kt [hunk 1]
```diff
@@ -103,6 +106,12 @@ class CompactInitialization(private val configRules: List<RulesConfig>) : Rule("
                             it.treeParent.removeChild(it)
                         }
                     // strip receiver name and move assignment itself into `apply`
+                    if (bodyExpression.treeParent.elementType == FUNCTION_LITERAL
+                            && bodyExpression.firstChildNode.elementType == WHITE_SPACE) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/CompactInitialization.kt:110]: Is it error by `KotlinParser` or is something wrong with `getOrCreateApplyBlock`? Where does this incorrectly placed `WHITE_SPACE` node come from? Either way, if you keep this magical hack here, provide some comments for it.

File: diktat-rules/src/test/resources/test/chapter6/compact_initialization/ApplyWithValueArgumentExpected.kt [hunk 2]
```diff
@@ -9,4 +9,12 @@ httpClient.doRequest()
...
 fun setDefaultUrl(httpClient: HttpClient) {
     httpClient.url = "http://example.com"
+}
+
+fun foo() {
+    val diktatExtension = project.extensions.create(DIKTAT_EXTENSION, DiktatExtension::class.java).apply {
+    inputs = project.fileTree("src").apply {
+        include("**/*.kt")
+    }
+    reporter = PlainReporter(System.out)}
```
Comment (petertrr) [inline diktat-rules/src/test/resources/test/chapter6/compact_initialization/ApplyWithValueArgumentExpected.kt:19]: Why is `}` still on the same line? It should be fixed by `NewlinesRule`, is everything ok with the AST here?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/test/resources/test/chapter6/compact_initialization/ApplyWithValueArgumentExpected.kt (hunk 2 above)
Comment (aktsay6) [reply diktat-rules/src/test/resources/test/chapter6/compact_initialization/ApplyWithValueArgumentExpected.kt:19]: AST is fine. It is a bug in NewlinesRule.

Comment (petertrr) [reply diktat-rules/src/test/resources/test/chapter6/compact_initialization/ApplyWithValueArgumentExpected.kt:19]: Is there any issue on this? If not, please create one and describe.

Comment (akuleshov7) [reply diktat-rules/src/test/resources/test/chapter6/compact_initialization/ApplyWithValueArgumentExpected.kt]: Tsay, wtf,  you sound like a pussy: "oh, it is not my bug"
Create an issue or fix it by yourself

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/CompactInitialization.kt [hunk 3]
```diff
@@ -106,6 +108,14 @@ class CompactInitialization(private val configRules: List<RulesConfig>) : Rule("
                             bodyExpression.addChild(it.clone() as ASTNode, null)
                             it.treeParent.removeChild(it)
                         }
+                    // Code above breaks a tree a little bit, so need this hack to recover it
+                    // Code above adds whiteSpace node to block, but it should be in functional literal after LBRACE
+                    if (bodyExpression.treeParent.elementType == FUNCTION_LITERAL
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/CompactInitialization.kt:113]: dafuq? where are tests?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/CompactInitialization.kt [hunk 4]
```diff
@@ -106,6 +108,14 @@ class CompactInitialization(private val configRules: List<RulesConfig>) : Rule("
                             bodyExpression.addChild(it.clone() as ASTNode, null)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/CompactInitialization.kt:108]: I think it would be more consistent, if we change this `forEach` to `forEachIndexed` and inside it `if (idx == 0 && elementType == WHITE_SPACE)` add node to parent, otherwise add to `bodyExpression`.

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Expected.kt [hunk 5]
```diff
@@ -1,45 +1,10 @@
 package org.cqfn.diktat
 
-class SpecialTagsInKdoc {
```
Comment (petertrr) [inline diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Expected.kt:3]: Why is everything else removed in this example?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Expected.kt (hunk 5 above)
Comment (aktsay6) [reply diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example4Expected.kt:3]: Was testing, forgot to return it

**Review by petertrr — APPROVED** [review]
