### PR TITLE
Rule 6.1.7 implicit backing property(#443)

### LINKED ISSUE #443: Rule 6.1.7: in case of using "implicit backing property" scheme, the name of real and back property should be the same
Kotlin has a mechanism of [backing properties](https://kotlinlang.org/docs/reference/properties.html#backing-properties).
In some cases implicit backing is not enough and it should be done explicitly:
```kotlin
private var _table: Map<String, Int>? = null
val table: Map<String, Int>
    get() {
        if (_table == null) {
            _table = HashMap() // Type parameters are inferred
        }
        return _table ?: throw AssertionError("Set to null by another thread")
    }
```

In this case the name of backing property (`_table`) should be the same to the name of real property (`table`), but should have underscore (`_`) prefix.
It is one of the exceptions from the [identifier names rule](#r1.2)

### PR DESCRIPTION
**Pull request by aktsay6**
## Which rule and warnings did you add?
In case of using "implicit backing property" scheme, the name of real and back property should be the same

This pull request closes #443 

## Actions checklist
* [X] Implemented Rule, added Warnings
* [X] Added tests on checks
* [ ] Added tests on fixers
* [X] Updated diktat-analysis.yml
* [X] Updated available-rules.md

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt [hunk 1]
```diff
@@ -121,6 +121,7 @@ enum class Warnings(private val canBeAutoCorrected: Boolean, private val warn: S
     WRONG_NAME_OF_VARIABLE_INSIDE_ACCESSOR(false, "Use `field` keyword instead of property name inside property accessors"),
     MULTIPLE_INIT_BLOCKS(true, "Avoid using multiple `init` blocks, this logic can be moved to constructors or properties declarations"),
     CLASS_SHOULD_NOT_BE_ABSTRACT(true, "class should not be abstract, because it has no abstract functions"),
+    NO_CORRESPONDING_PROPERTY(false, "there is no corresponding property")
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt:124]:
```suggestion
    NO_CORRESPONDING_PROPERTY(false, "backing property should have the same name, but there is no corresponding property")
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ImplicitBackingPropertyRule.kt [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+import com.pinterest.ktlint.core.ast.ElementType.VALUE_PARAMETER
+import org.cqfn.diktat.common.config.rules.RulesConfig
+import org.cqfn.diktat.ruleset.constants.Warnings.NO_CORRESPONDING_PROPERTY
+import org.cqfn.diktat.ruleset.utils.findAllNodesWithSpecificType
+import org.cqfn.diktat.ruleset.utils.getFirstChildWithType
+import org.cqfn.diktat.ruleset.utils.getIdentifierName
+import org.cqfn.diktat.ruleset.utils.hasAnyChildOfTypes
+import org.jetbrains.kotlin.com.intellij.lang.ASTNode
+
+class ImplicitBackingPropertyRule(private val configRules: List<RulesConfig>) : Rule("implicit-backing-property") {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ImplicitBackingPropertyRule.kt:19]: Please add KDoc

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ImplicitBackingPropertyRule.kt [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+    private fun findAllProperties(node: ASTNode) {
+        val properties = node.getChildren(null).filter { it.elementType == PROPERTY }
+
+        val propsWithBackSymbol = mutableListOf<String>()
+
+        properties
+                .filter { it.getFirstChildWithType(IDENTIFIER)!!.text.startsWith("_") }
+                .forEach {
+                    propsWithBackSymbol.add(it.getFirstChildWithType(IDENTIFIER)!!.text)
+                }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ImplicitBackingPropertyRule.kt:44]:
```suggestion
        val propsWithBackSymbol = properties
                .filter { it.getFirstChildWithType(IDENTIFIER)!!.text.startsWith("_") }
                .map {
                    it.getFirstChildWithType(IDENTIFIER)!!.text
                }
```

File: diktat-analysis.yml [hunk 4]
```diff
@@ -339,5 +339,9 @@
   configuration: {}
 # Checks that there are abstract functions in abstract class
 - name: CLASS_SHOULD_NOT_BE_ABSTRACT
+  enabled: true
+  configuration: {}
+# In case of using "implicit backing property" scheme, the name of real and back property should be the same
```
Comment (petertrr) [inline diktat-analysis.yml:344]: But what is described in our rule is pretty much the opposite of "implicit backing properties" - we are checking "explicit backing properties", like in [kotlin docs](https://kotlinlang.org/docs/reference/properties.html#backing-properties)

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/ImplicitBackingPropertyWarnTest.kt [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+import org.cqfn.diktat.ruleset.rules.ImplicitBackingPropertyRule
+import org.cqfn.diktat.util.LintTestBase
+import org.junit.jupiter.api.Tag
+import org.junit.jupiter.api.Test
+
+class ImplicitBackingPropertyWarnTest: LintTestBase(::ImplicitBackingPropertyRule) {
+    private val ruleId = "$DIKTAT_RULE_SET_ID:implicit-backing-property"
+
+    @Test
+    @Tag("")
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/ImplicitBackingPropertyWarnTest.kt:16]: tag?

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/ImplicitBackingPropertyWarnTest.kt [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+                    |       }
+                    |       set(value) {field = value}
+                    |}
+                """.trimMargin()
+        )
+    }
+
+    @Test
+    @Tag("")
+    fun `trigger on backing property`() {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/ImplicitBackingPropertyWarnTest.kt:37]: Why no LintError here?

**Review by petertrr — CHANGES_REQUESTED** [review]
See comments above

**Review by petertrr — COMMENTED** [review]
Please take a look at snapshot check. Your rule triggers quite a lot in `diktat-test-framework` with false-positives. Please add similar examples to tests, one idea how to fix algorithm is in comment below.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ImplicitBackingPropertyRule.kt [hunk 7]
```diff
@@ -50,14 +56,28 @@ class ImplicitBackingPropertyRule(private val configRules: List<RulesConfig>) :
...
-        accessors.forEach {
-            val refExprs = it.findAllNodesWithSpecificType(REFERENCE_EXPRESSION)
+        accessors.filter { it.hasChildOfType(GET_KEYWORD) }.forEach { handleGetAccessors(it, node, propsWithBackSymbol) }
+        accessors.filter { it.hasChildOfType(SET_KEYWORD) }.forEach { handleSetAccessors(it, node, propsWithBackSymbol) }
+    }
+
+    private fun handleGetAccessors(accessor: ASTNode, node: ASTNode, propsWithBackSymbol: List<String>) {
+        val refExprs = accessor
+                .findAllNodesWithSpecificType(RETURN)
+                .flatMap { _return -> _return.findAllNodesWithSpecificType(REFERENCE_EXPRESSION) }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ImplicitBackingPropertyRule.kt:68]: What's with [identifier naming](https://github.com/cqfn/diKTat/blob/master/info/diktat-kotlin-coding-style-guide-en.md#-rule-12)? :)

**Review by petertrr — CHANGES_REQUESTED** [review]
False-positives are still there, please add more tests (like `TestProcessingFactory.allTestsFromResources` in diktat-test-framework). We need to come up with better algorithm for identifying such backing properties. Maybe, check that a certain class property is used both in an assignment in setter and in the return statement in getter?

**Review by petertrr — CHANGES_REQUESTED** [review]
https://github.com/cqfn/diKTat/pull/465/checks?check_run_id=1440909442
Warning is raised on `declaredOptions` in `TestArgumentsReader`, where local variable is returned from getter. We should trigger this warning only for class properties.

File: info/available-rules.md [hunk 8]
```diff
@@ -98,6 +98,7 @@
 |    6 |     6.1.4 | MULTIPLE_INIT_BLOCKS                   | Checks that classes have only one init block | yes | no | - |
 |    6 |     6.1.5 | USELESS_SUPERTYPE                       | Check: if override function can be removed                                                                                                                                   | yes| - |     |
 |    6 |     6.1.6 | CLASS_SHOULD_NOT_BE_ABSTRACT           | Checks: if abstract class has any abstract method. If not, warns that class should not be abstract<br>Fix: deletes abstract modifier                                         | yes | - | - |
+|    6 |     6.1.7 | NO_CORRESPONDING_PROPERTY              | Checks: if in case of using "implicit backing property" scheme, the name of real and back property are the same                                                              | no | - | - |
```
Comment (petertrr) [inline info/available-rules.md:101]:
```suggestion
|    6 |     6.1.7 | NO_CORRESPONDING_PROPERTY              | Checks: if in case of using "backing property" scheme, the name of real and back property are the same                                                              | no | - | - |
```
It's not implicit though

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ImplicitBackingPropertyRule.kt [hunk 9]
```diff
@@ -0,0 +1,112 @@
...
+    @Suppress("UnsafeCallOnNullableType")
+    private fun handleSetAccessors(accessor: ASTNode, node: ASTNode, propsWithBackSymbol: List<String>) {
+        val refExprs = accessor.findAllNodesWithSpecificType(REFERENCE_EXPRESSION)
+
+
+        val localProps = accessor
+                .findAllNodesWithSpecificType(PROPERTY)
+                .map { (it.psi as KtProperty).name!! }
+
+        if (refExprs.isNotEmpty()) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ImplicitBackingPropertyRule.kt:92]: Does this mean that any reference to non-local property will cause warning? What if some other class property is read for some reason? I think, similar to getters, we should check only left-hand side references in assignments. For example, this code:
```kotlin
val foo
    set(value) {
        if (isDebugMode) log.debug(value)
        field = value
    }
```
shouldn't raise a warning beca use there is no backing property.

**Review by petertrr — CHANGES_REQUESTED** [review]
