### PR TITLE
Recommendation-3.5-line-length

### LINKED ISSUE #115: Recommendation 3.5: line length should be less than 120 symbols
**120 - is just a number and should be configurable**

This international code style prohibits non-latin (non ASCII) symbols in the code. But in case you would like to use them anyway - please use the following convention:

- One wide character occupies the width of two narrow characters.
  The "wide" and "narrow" of a character are defined by its [*east asian width* Unicode attribute] (https://unicode.org/reports/tr11/).
  Generally, narrow characters are also called "half-width" characters. All characters in the ASCII character set include letters (such as `a`, `A`), numbers (such as `0`, `3`), and punctuation (such as `, `, `{`), spaces. All of them are narrow characters.
  Wide characters are also called "full-width" characters, Chinese characters (such as `中`, `文`), Chinese punctuation (`, `, `, `), full-width letters and numbers (such as `Ａ`、`３`) are all. These characters counted as 2 narrow characters.
  
- Any line that exceeds this limit (120 narrow symbols) should be wrapped, as described in the *Newline* section. 

 **Exceptions：**

  1. Long URL or long JSON method reference in KDoc.
  2. The `package` and `import` statements.
  3. The command line in the comment so that it can be cut and pasted into the shell for use.

### PR DESCRIPTION
**Pull request by kentr0w**
###What's done:
  Added rule
  Added tests
  close #115 

## Actions checklist
* [x] Implemented Rule, added Warnings
* [x] Added tests on checks
* [ ] Added tests on fixers
* [x] Updated rules-config.json
* [x] Updated available-rules.md

## Fixme
Add for fix

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+                it.text.split("\n").forEach { textNode ->
+                    if (textNode.length > configuration.lineLength)
+                        LONG_LINE.warnAndFix(configRules, emitWarn, isFixMode, textNode, it.startOffset.plus(it.treeParent.startOffset)) {}
+                }
+            }
+        }
+    }
+
+    /**
+     * JSON not supported
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:66]: If this is a comment about something that has been left out of scope of this pull request, please start it with 'fixme' or 'todo', to make it more clear and less probable to forget about it after :)

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+     */
+    private fun checkKDoc(node: ASTNode, configuration: LineLengthConfiguration) {
+        val nodesList = node.findChildByType(KDOC_SECTION)?.findAllNodesWithSpecificType(KDOC_TEXT)
+        nodesList.let { nodes ->
+            nodes!!.forEach {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:71]: Why do you need `let` and then immediately `forEach`?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+                }
+            }
+        }
+    }
+
+    /**
+     * JSON not supported
+     */
+    private fun checkKDoc(node: ASTNode, configuration: LineLengthConfiguration) {
+        val nodesList = node.findChildByType(KDOC_SECTION)?.findAllNodesWithSpecificType(KDOC_TEXT)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:69]: I believe `KDOC_TEXT` can be only in children of `KDOC_SECTION`, so no need to check deeper nodes.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthWarnText.kt [hunk 4]
```diff
@@ -0,0 +1,208 @@
...
+    fun `check correct example`() {
+        lintMethod(LineLength(),
+                """
+                    |package org.cqfn.diktat.ruleset.chapter3
+                    |
+                    |import org.cqfn.diktat.ruleset.rules.LineLength
+                    |import org.cqfn.diktat.util.lintMethod
+                    |
+                    |/**
+                    |*https://www.google.com
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthWarnText.kt:31]:
```suggestion
                    | * https://www.google.com
```
Ususally (and in our code style too) asterisks in KDocs are followed by spaces. Could you please change your test cases and fix logic to correctly handle it?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+            }
+        }
+    }
+
+    private fun checkLength(node: ASTNode, configuration: LineLengthConfiguration) {
+        node.getChildren(null).forEach {
+            if (it.elementType == KDOC) {
+                checkKDoc(it, configuration)
+            } else {
+                it.text.split("\n").forEach { textNode ->
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:57]: I think name`textNode` is confusing. This name, at least for me, mean that this variable corresponds  to node with text, while it really corresponds to a line from text from a node.
Moreover, the general best practices of kotlin are to make outer lambdas with explicit parameters, while inner with either explicit or implicit. Here you have outer `forEach` with parameter `it` and inner `forEach` with named argument. I suggest to make it vice versa.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthWarnText.kt [hunk 6]
```diff
@@ -0,0 +1,208 @@
...
+import com.pinterest.ktlint.core.LintError
+import org.cqfn.diktat.common.config.rules.RulesConfig
+import org.cqfn.diktat.ruleset.constants.Warnings.LONG_LINE
+import org.cqfn.diktat.ruleset.rules.DIKTAT_RULE_SET_ID
+import org.cqfn.diktat.ruleset.rules.LineLength
+import org.cqfn.diktat.util.lintMethod
+import org.junit.Test
+
+
+class LineLengthWarnText {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthWarnText.kt:12]: You tests have a little of duplication. For example, you could have long URLs and long imports in the first positive example as well, because it is part of core logic. Please merge some of duplicated tests and instead add more diversity to you examples: property declarations, functions and constants outside of class bodies etc.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+        if (node.elementType == FILE) {
+            node.getChildren(null).forEach {
+                if (it.elementType != PACKAGE_DIRECTIVE || it.elementType != IMPORT_LIST)
+                    checkLength(it, configuration)
+            }
+        }
+    }
+
+    private fun checkLength(node: ASTNode, configuration: LineLengthConfiguration) {
+        node.getChildren(null).forEach {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:53]: Why do you traverse children here too? I believe there are cases when children of `FILE` node have only single-line children, so checking their children's text could work not as expected (for example, check how your logic handles file-level property declarations).

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt [hunk 8]
```diff
@@ -0,0 +1,85 @@
...
+
+    /**
+     * JSON not supported
+     */
+    private fun checkKDoc(node: ASTNode, configuration: LineLengthConfiguration) {
+        val nodesList = node.findChildByType(KDOC_SECTION)?.findAllNodesWithSpecificType(KDOC_TEXT)
+        nodesList.let { nodes ->
+            nodes!!.forEach {
+                try {
+                    URL(it.text).toURI()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:73]: Please change the order of checks: you don't need to check URL if line is shorter than limit, and checking line length is much easier in terms of performance.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthWarnText.kt (hunk 6 above)
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthWarnText.kt:12]:
```suggestion
class LineLengthWarnTest {
```
Seems like due to the [wrong name](https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html) your test hasn't been picked up by surefire plugin, therefore code coverage is so low.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt [hunk 9]
```diff
@@ -50,27 +50,23 @@ class LineLength : Rule("line-length") {
...
-            try {
-                URL(node.text).toURI()
-            } catch (e: IOException) {
-                LONG_LINE.warnAndFix(configRules, emitWarn, isFixMode,
-                        "max line length ${configuration.lineLength}, but was ${node.text.length}",
-                        node.startOffset) {}
-            }
+    private fun isKDocValid(node: ASTNode): Boolean {
+        return try {
+            URL(node.text).toURI()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:66]: I think we should handle here not only the case with long URL occupying a whole line. For example, in KDocs people can wrap links in markdown. Checking for URL as a part of line using some simple regex could be more suitable.

@akuleshov7 please advice. I think it should be more clearly specified in codestyle guide.

Comment (akuleshov7) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:66]: check the last word on URL

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt [hunk 10]
```diff
@@ -49,7 +50,7 @@ class LineLength : Rule("line-length") {
         var offset = 0
         node.text.lines().forEach {
             if (it.length > configuration.lineLength) {
-                val newNode = node.psi.findElementAt(offset + it.length - 1)!!.node
+                val newNode = node.psi.findElementAt(offset + it.trim().length - 1)!!.node
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:53]: Why do you need to trim here? I think this will return the same node, since you will point to effectively same line of code.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt [hunk 11]
```diff
@@ -10,6 +10,7 @@ import org.cqfn.diktat.common.config.rules.RuleConfiguration
 import org.cqfn.diktat.common.config.rules.RulesConfig
 import org.cqfn.diktat.common.config.rules.getRuleConfig
 import org.cqfn.diktat.ruleset.constants.Warnings.LONG_LINE
+import org.cqfn.diktat.ruleset.utils.prettyPrint
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:13]: Unused import?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt [hunk 12]
```diff
@@ -63,7 +64,7 @@ class LineLength : Rule("line-length") {
     // fixme json method
     private fun isKDocValid(node: ASTNode): Boolean {
         return try {
-            URL(node.text).toURI()
+            URL(node.text.split("\\s".toRegex()).last { it != "" }).toURI()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:67]: I think you should trim here instead: if you trim `node.text` first, then last element of split should not be empty. Also, I think it is better to use `it.isNotEmpty()` instead of comparison.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthWarnTest.kt [hunk 13]
```diff
@@ -0,0 +1,214 @@
...
+
+import com.pinterest.ktlint.core.LintError
+import org.cqfn.diktat.common.config.rules.RulesConfig
+import org.cqfn.diktat.ruleset.constants.Warnings.LONG_LINE
+import org.cqfn.diktat.ruleset.rules.DIKTAT_RULE_SET_ID
+import org.cqfn.diktat.ruleset.rules.LineLength
+import org.cqfn.diktat.util.lintMethod
+import org.junit.Test
+
+class LineLengthWarnTest {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/LineLengthWarnTest.kt:11]: Please add test case with URL in markdown, like 'check this \[link\]\(http://url...)'.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt (hunk 10 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:53]: No, it won't work without trim, because there are spaces at the end of the test.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt (hunk 12 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:67]: I should trim in `checkLength` to take `KDOC_TEXT` not `WHITE_SPACE`

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt (hunk 10 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:53]: ok, I see

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt (hunk 12 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:67]: Ok, got it. Also, shouldn't you be using `\\s+` as a regex here to split on multiple spaces too?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt [hunk 14]
```diff
@@ -0,0 +1,80 @@
...
+
+    // fixme json method
+    private fun isKDocValid(node: ASTNode): Boolean {
+        return try {
+            if (node.elementType == KDOC_TEXT)
+                URL(node.text.split("\\s".toRegex()).last { it.isNotEmpty() }).toURI()
+            else
+                URL(node.text.substring(node.text.indexOfFirst { it == ']' } + 2, node.textLength - 1)).toURI()
+            true
+        } catch (e: IOException) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/LineLength.kt:72]: When you are catching `IOException`, you catch only `MalformedURLException`, which is thrown from `URL` constructor. `toUri()` throws `URISyntaxException` which extends `Exception`. I think you could remove `toUri` call and check that calling constructor is enough to cause and exception. Also, you could narrow a catch clause.
