### PR TITLE
BlockStructureBraces assertion failed

### LINKED ISSUE #436: Assertion failed: anchorBefore == null || anchorBefore.getTreeParent() == parent
## Describe the bug
Code `class A {val x = 0 }` (when there is text right after `{`) causes and error, relevant part of stacktrace:
```
at org.cqfn.diktat.ruleset.rules.BlockStructureBraces.checkOpenBraceEndLine(BlockStructureBraces.kt:185)
	at org.cqfn.diktat.ruleset.rules.BlockStructureBraces.checkOpenBraceOnSameLine(BlockStructureBraces.kt:176)
	at org.cqfn.diktat.ruleset.rules.BlockStructureBraces.checkClass(BlockStructureBraces.kt:84)
	at org.cqfn.diktat.ruleset.rules.BlockStructureBraces.visit(BlockStructureBraces.kt:66)
```

## Environment information
* diktat version: 0.1.2

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
Fixed bug with add children
closes #436

### CODE REVIEW

File: diktat-rules/src/test/resources/test/paragraph3/block_brace/ClassBracesTest.kt [hunk 1]
```diff
@@ -11,3 +11,5 @@ class C{
     companion object{
         private val id = 11}
 }
+
+class D {val x = 0}
```
Comment (petertrr) [inline diktat-rules/src/test/resources/test/paragraph3/block_brace/ClassBracesTest.kt:15]: Please add this example to smoke test too.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesFixTest.kt [hunk 2]
```diff
@@ -43,4 +43,10 @@ class BlockStructureBracesFixTest : FixTestBase ("test/paragraph3/block_brace",
     fun `should fix open and close brace in try-catch-finally expression`() {
         fixAndCompare("TryBraceExpected.kt", "TryBraceTest.kt")
     }
+
+    @Test
+    @Tag(WarningNames.BRACES_BLOCK_STRUCTURE_ERROR)
+    fun `should fix open and close brace in common expression`() {
+        fixAndCompare("CommonExpected.kt", "CommonTest.kt")
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesFixTest.kt:50]: Was it after all actually failing on this example? I don't remember, what we found out in the end.

If it wasn't failing on this particular rule, please move it to smoke test as an additional example.

**Review by petertrr — APPROVED** [review]
lgtm
