### PR TITLE
Fixes for FileStructureRule

### LINKED ISSUE #267: FileStructureRule follow-ups
There are some issues stated in comments in code.
* handle other elements that could be present before package (other comments)
* ~handle cases when PACKAGE_DIRECTIVE node is not present~ already supports nullable package directive for default package
* ~find cases when node.psi.importLists.size > 1~ - shouldn't happen in valid kotlin code, handle cases when it's not present at all

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Fixed logic
* Added tests

This pull request closes #267

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/FileStructureRule.kt [hunk 1]
```diff
@@ -123,19 +124,31 @@ class FileStructureRule(private val configRules: List<RulesConfig>) : Rule("file
...
         var copyrightComment = firstCodeNode.prevSibling { it.elementType == BLOCK_COMMENT }
         var headerKdoc = firstCodeNode.prevSibling { it.elementType == KDOC }
+        // Annotations with target`file` can only be placed before `package` directive.
         var fileAnnotations = node.findChildByType(FILE_ANNOTATION_LIST)
+        // We also collect all other elements that are placed on top of the file.
+        // These may be other comments, so we just place them before the code starts.
+        val otherNodesBeforeCode = firstCodeNode.siblings(forward = false)
+            .filterNot {
+                it.isWhiteSpace() ||
+                        it == copyrightComment || it == headerKdoc || it == fileAnnotations
```
Comment (aktsay6) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/FileStructureRule.kt:144]: What about EOL comments? Do we need to handle it here?

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/FileStructureRule.kt:144]: We state the following structure (as per our code style): copyright information is placed in a block comment, general file comment is placed in KDoc. All other nodes that can appear before code, including EOL comments, are captured here.

File: diktat-rules/src/test/resources/test/paragraph3/file_structure/OtherCommentsExpected.kt [hunk 2]
```diff
@@ -0,0 +1,11 @@
+/**
+ * This is an example
+ */
+
+// some notes on this file
```
Comment (kentr0w) [inline diktat-rules/src/test/resources/test/paragraph3/file_structure/OtherCommentsExpected.kt:5]: Maybe it's better to add comments into KDoc?

File: diktat-rules/src/test/resources/test/paragraph3/file_structure/OtherCommentsTest.kt [hunk 3]
```diff
@@ -0,0 +1,11 @@
+// some notes on this file
```
Comment (kentr0w) [inline diktat-rules/src/test/resources/test/paragraph3/file_structure/OtherCommentsTest.kt:1]: Why `COMMENT_BLOCK` doesn't move exactly like the comment

**Review by kentr0w — CHANGES_REQUESTED** [review]

File: diktat-rules/src/test/resources/test/paragraph3/file_structure/OtherCommentsTest.kt (hunk 3 above)
Comment (petertrr) [reply diktat-rules/src/test/resources/test/paragraph3/file_structure/OtherCommentsTest.kt:1]: If there is a `BLOCK_COMMENT` before code, it's considered as containing copyright information. But you are right, I need to check copyright keywords too, like we do in some other rule.

File: diktat-rules/src/test/resources/test/paragraph3/file_structure/OtherCommentsExpected.kt (hunk 2 above)
Comment (petertrr) [reply diktat-rules/src/test/resources/test/paragraph3/file_structure/OtherCommentsExpected.kt:5]: I check that EOL comments are moved correctly here, why would I need KDoc instead/

Comment (kentr0w) [reply diktat-rules/src/test/resources/test/paragraph3/file_structure/OtherCommentsExpected.kt:5]: I thought it would be better to have one KDOC than KDOC and EOL, but I think so well)

**Review by kentr0w — APPROVED** [review]
lgtm
