### PR TITLE
Bugfix. Newline at the beginning of code block is not removed if there are more than one

### LINKED ISSUE #519: Newline at the beginning of code block is not removed if there are more than one
## Describe the bug
1. ```kotlin
    fun foo() {

      println()
      println()
    }
    ```
removes only one blank line, though we have a rule that removes a single blank line. These changes should be run all at once.

2. ```kotlin
    list.map {
        
        bar()
    }
    ```
the blank line in the beginning of code block is not removed.

## Environment information
* diktat version: 0.1.3

### PR DESCRIPTION
**Pull request by aktsay6**
### What's done:
  * Fixed bugs

This pull request closes #519

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/BlankLinesRule.kt [hunk 1]
```diff
@@ -53,7 +56,10 @@ class BlankLinesRule(private val configRules: List<RulesConfig>) : Rule("blank-l
 
     private fun handleTooManyBlankLines(node: ASTNode) {
         TOO_MANY_BLANK_LINES.warnAndFix(configRules, emitWarn, isFixMode, "do not use more than two consecutive blank lines", node.startOffset, node) {
-            node.leaveExactlyNumNewLines(2)
+            if (node.treeParent.findAllNodesWithSpecificType(WHITE_SPACE).first() == node)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/BlankLinesRule.kt:59]: Isn't `findChildByType` enough here?

**Review by petertrr — APPROVED** [review]

**Review by petertrr — APPROVED** [review]
