### PR TITLE
Fix logic of InlineClassesRule

### LINKED ISSUE #904: [INLINE_CLASS_CAN_BE_USED] inline class can be used
This rule is triggered on the interfaces. I do not think that it should work in that way, isn't it?

### PR DESCRIPTION
**Pull request by petertrr**
Do not suggest to use inline class on versions greater than 1.5.0 and on interfaces

### What's done:
* Changed logic
* Added tests

This pull request closes #904 

Proper support for value classes should be added in #957

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/InlineClassesRule.kt [hunk 1]
```diff
@@ -31,7 +31,11 @@ class InlineClassesRule(configRules: List<RulesConfig>) : DiktatRule(
     listOf(INLINE_CLASS_CAN_BE_USED)) {
     override fun logic(node: ASTNode) {
         val configuration = configRules.getCommonConfiguration()
-        if (node.elementType == CLASS && configuration.kotlinVersion >= ktVersion) {
+        if (node.elementType == CLASS &&
+                !(node.psi as KtClass).isInterface() &&
+                configuration.kotlinVersion >= minKtVersion &&
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/InlineClassesRule.kt:36]: In description you wrote, that we **shouldn't** suggest to use inline classes on **interfaces** and when version **greater than 1.4.x**. 

I see that you add check `!interface`, but why we call `handleClasses` when version > `1.3` and < `1.5.0`?
Shouldn't it be `configuration.kotlinVersion <= 1.4.0`?

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/InlineClassesRule.kt:36]: That's my mistake in the description; `inline` keyword is valid up to 1.5.0

**Review by kgevorkyan — APPROVED** [review]
