### PR TITLE
Cover cases missing in recommendation 3.7

### LINKED ISSUE #242: Cover cases missing in recommendation 3.7
* ~There should be a single space after `{` unless it is a template inside a string. In the latter case there should be no spaces.
`list.map { "${it.foo()}" }`~ - not able to reproduce
* There should be spaces on both sides of `=`, both in assignment and in named arguments.
* method `handleLpar` should also check that there are no spaces before `(` when annotation has arguments:
`@JvmName("jvmName")  // no space before (`

### LINKED ISSUE #283: False-positive WRONG_WHITESPACE on nested braces inside lambda
1. 
    ```kotlin
    list.forEach {
        try {
            foo()
        }
    }
    ```
    causes
    ```
    [WRONG_WHITESPACE] incorrect usage of whitespaces for code separation: there should be no whitespace before '{' of lambda inside argument list
    ```
    on a brace after `try`

2. Lambda passed to a named argument
    ```kotlin
    Example(cb = { _, _ -> Unit })
    ```

3. Lamda as a second argument
    ```kotlin
        foo(bar, { it.baz() })
    ```

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
    Added handler for equals
    Added handler for annotation

## Actions checklist
* [x] Added tests on checks
* [x] Added tests on fixers
* [x] closes #242 
* [x] closes #283

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt [hunk 1]
```diff
@@ -198,10 +208,11 @@ class WhiteSpaceRule(private val configRules: List<RulesConfig>) : Rule("horizon
 
     private fun handleBinaryOperator(node: ASTNode) {
         val operatorNode = if (node.elementType == OPERATION_REFERENCE) node.firstChildNode else node
-
-        if (node.elementType == OPERATION_REFERENCE && node.treeParent.elementType.let { it == BINARY_EXPRESSION || it == POSTFIX_EXPRESSION } ||
+        if (node.elementType == EQ && node.treeParent.elementType == OPERATION_REFERENCE) return
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:211]: What does this case correspond to?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt [hunk 2]
```diff
@@ -111,13 +115,13 @@ class WhiteSpaceRule(private val configRules: List<RulesConfig>) : Rule("horizon
             CONSTRUCTOR_KEYWORD -> handleConstructor(node)
             in keywordsWithSpaceAfter -> handleKeywordWithParOrBrace(node)
             // operators and operator-like symbols
-            OPERATION_REFERENCE, COLONCOLON, DOT, ARROW, SAFE_ACCESS -> handleBinaryOperator(node)
+            OPERATION_REFERENCE, COLONCOLON, DOT, ARROW, SAFE_ACCESS, EQ -> handleBinaryOperator(node)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:118]: `EQ` should be surrounded by spaces no only in properties but everywhere else (assignments, named function arguments etc)

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt (hunk 1 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:211]: Because `OPERATION_REFERENCE ` sometime contains `EQ`. I had test for this.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt (hunk 2 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:118]: But the logic is the same. I add test for this case.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:211]: Yes, and what is an example in code? And why in this case you `return` from the method?

Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:213]: Because I check this in the `handleBinaryOperator`

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:213]: Right, I see now.

**Review by petertrr — APPROVED** [review]
LGTM
