### PR TITLE
Gradle plugin tests & fixes

### LINKED ISSUE #653: Add more examples for gradle functionalTest

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Respect ignoreFailures flag
* Made excludes non-nullable
* Fix for file patterns
* Use plugin.apply in unit tests
* Use GradleVersion from gradle API instead of custom
* Jacoco reports for all functional tests
* Introduced Utils for runctional tests
* Functional tests for Groovy DSL

This pull request closes #653

### CODE REVIEW

File: diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+}
+
+/**
+ * @param arguments additional arguments to pass to [GradleRunner]
+ */
+internal fun runDiktat(testProjectDir: TemporaryFolder,
+                      shouldSucceed: Boolean = true,
+                      arguments: List<String> = emptyList(),
+                      configureRunner: GradleRunner.() -> GradleRunner = { this }
+) = GradleRunner.create()
```
Comment (kentr0w) [inline diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt:41]: Can this function be a util method of GradleRunner?

File: diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+        )
+    }
+}
+
+/**
+ * @param arguments additional arguments to pass to [GradleRunner]
+ */
+internal fun runDiktat(testProjectDir: TemporaryFolder,
+                      shouldSucceed: Boolean = true,
+                      arguments: List<String> = emptyList(),
```
Comment (kentr0w) [inline diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt:39]: Everywhere arguments is `listOf("--info")` , maybe replace `List<String>` to `String`?

**Review by kentr0w — CHANGES_REQUESTED** [review]

File: diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt [hunk 3]
```diff
@@ -2,39 +2,12 @@
  * Utilities for diktat gradle plugin
  */
 
+@file:Suppress("FILE_NAME_MATCH_CLASS")
+
```
Comment (aktsay6) [inline diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt:6]: Do we still need it here?

Comment (petertrr) [reply diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt:6]: Yes, there is a single class in this file, but I don't want to change file name accordingly.

File: diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt (hunk 2 above)
Comment (petertrr) [reply diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt:39]: I want to keep it possible to start multiple flags, e.g. during debugging you may change it to `listOf("--info", "--stacktrace")`.

File: diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt (hunk 1 above)
Comment (petertrr) [reply diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt:41]: Do you mean extension method?

Comment (kentr0w) [reply diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt:41]: Yes

Comment (petertrr) [reply diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt:41]: I don't see much sense in it: I don't pass `GradleRunner` as a parameter so it won't reduce arguments list; the method starts with call of static method from Java, so it can't be used in an extension.

Comment (kentr0w) [reply diktat-gradle-plugin/src/functionalTest/kotlin/org/cqfn/diktat/plugin/gradle/Utils.kt:41]: Yes, I was wrong - misunderstood

**Review by kentr0w — APPROVED** [review]
lgtm
