### PR TITLE
Fix bug in PackageNaming for kotlin scripts

### LINKED ISSUE #861: [ERROR] Internal error has occurred in package-naming: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
In case you will run mvn diktat:check in the root of diktat you will see this issue.

```
 if (realNameParts.isNotEmpty() && packageNameParts.map { node -> node.text } != realNameParts) {
            val realPackageNameStr = realNameParts.joinToString(PACKAGE_SEPARATOR)
            // issue happens here if there is no package name for the file
            val offset = packageNameParts[0].startOffset
            PACKAGE_NAME_INCORRECT_PATH.warnAndFix(configRules, emitWarn, isFixMode,
                realPackageNameStr, offset, packageNameParts[0]) {
                insertNewPackageName(packageDirective, realPackageNameStr)
            }
        }
```

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Changed logic
* Updated smoke tests

This pull request closes #861

### CODE REVIEW

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/script/SimpleRunInScriptExpected.kts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+
```
Comment (akuleshov7) [inline diktat-rules/src/test/resources/test/smoke/src/main/kotlin/script/SimpleRunInScriptExpected.kts:1]: discussed, need to add test for kts with package name

Comment (petertrr) [reply diktat-rules/src/test/resources/test/smoke/src/main/kotlin/script/SimpleRunInScriptExpected.kts:1]: Added

**Review by akuleshov7 — APPROVED** [review]
lgtm, sorry for this bug
image
