### PR TITLE
Logging of file name in DiktatRule is unreliable

### LINKED ISSUE #938: Logging of file name in DiktatRule is unreliable
## Describe the bug
`getFilePath()` should be called only on node with type `FILE`. We should add `getRootNode()` there, and also `require` node element type in `getFilePath()`

## Environment information
* diktat version: 0.6.2

Linked with https://github.com/cqfn/diKTat/issues/882

### PR DESCRIPTION
**Pull request by Cheshiriks**
### What's done:
* added getRootNode() and require in getFilePath()
Closes #938

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 1]
```diff
@@ -737,7 +737,10 @@ fun ASTNode.calculateLineColByOffset() = buildPositionInTextLocator(text)
  *
  * @return name of the file [this] node belongs to
  */
-fun ASTNode.getFilePath(): String = getUserData(KtLint.FILE_PATH_USER_DATA_KEY).let {
+fun ASTNode.getFilePath(): String = getRootNode().let {
+    require(it.elementType == FILE) { "Root node type is not FILE" }
+    it
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:742]: You can use `also` instead of `let` to avoid this line

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 2]
```diff
@@ -737,7 +737,10 @@ fun ASTNode.calculateLineColByOffset() = buildPositionInTextLocator(text)
...
+}.getUserData(KtLint.FILE_PATH_USER_DATA_KEY).let {
     requireNotNull(it) { "File path is not present in user data" }
     it
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:745]: I think `it` is not needed here, because `requireNotNull` returns it's argument

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 3]
```diff
@@ -737,7 +737,10 @@ fun ASTNode.calculateLineColByOffset() = buildPositionInTextLocator(text)
  *
  * @return name of the file [this] node belongs to
  */
-fun ASTNode.getFilePath(): String = getUserData(KtLint.FILE_PATH_USER_DATA_KEY).let {
+fun ASTNode.getFilePath(): String = getRootNode().let {
+    require(it.elementType == FILE) { "Root node type is not FILE" }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:741]:
```suggestion
    require(it.elementType == FILE) { "Root node type is not FILE, but file_path is present in user_data only in FILE nodes" }
```

**Review by petertrr — APPROVED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt (hunk 1 above)
Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt]: fixed
