### PR TITLE
Rule 6.1.2. Prefer data classes instead of classes without any functional logic

### LINKED ISSUE #430: Rule 6.1.2: Prefer data classes instead of classes without any functional logic
### <a name="r6.1.2"></a> Rule 6.1.2: Prefer data classes instead of classes without any functional logic
Some people say that data class - is a code smell, but in case you really need to use it and your is becoming more simple because of that - you can use Kotlin `data classes`. Main purpose of these classes is to hold data.
But also `data classes` will automatically generate several useful methods:
- equals()/hashCode() pair;
- toString()
- componentN() functions corresponding to the properties in their order of declaration;
- copy() function

So instead of using `normal` classes:
```kotlin
class Test {
    var a: Int = 0
    var b: Int = 0
    
    constructor(a:Int, b: Int) {
        this.a = a
        this.b = b
    }
}
// or
class Test(var a: Int = 0, var b: Int = 0)
 
// or
class Test() {
    var a: Int = 0
    var b: Int = 0
}
```

Prefer:
```kotlin
data class Test1(var a: Int = 0, var b: Int = 0)
```

Exception: Note, that data classes cannot be abstract, open, sealed or inner, that's why these types of classes cannot be changed to data class.

### PR DESCRIPTION
**Pull request by aktsay6**
### What's done:
  * Rule logic made
  * Added tests

This pull request closes #430 

## Actions checklist
* [X] Implemented Rule, added Warnings
* [X] Added tests on checks
* [ ] Added tests on fixers
* [X] Updated diktat-analysis.yml
* [X] Updated available-rules.md

## Fixme

Need to know types of vars and props to create data class and add autofixing to rule.

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DataClassesRule.kt [hunk 1]
```diff
@@ -0,0 +1,73 @@
+package org.cqfn.diktat.ruleset.rules
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DataClassesRule.kt:1]:
```suggestion
package org.cqfn.diktat.ruleset.rules.classes
```
Let's try to place rules in different packages when it's logically possible

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DataClassesRule.kt [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+    private fun raiseWarn(node: ASTNode) {
+        USE_DATA_CLASS.warn(configRule, emitWarn, isFixMode, "${(node.psi as KtClass).name}", node.startOffset, node)
+    }
+
+    @Suppress("UnsafeCallOnNullableType")
+    private fun ASTNode.canBeDataClass() : Boolean {
+        if (hasChildOfType(MODIFIER_LIST)) {
+            val list = getFirstChildWithType(MODIFIER_LIST)!!
+            return list.getChildren(null).any { it.elementType !in BAD_MODIFIERS }
+                    && findAllNodesWithSpecificType(FUN).isEmpty()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DataClassesRule.kt:60]: You can check `CLASS_BODY`'s children, not `findAllNodes` that traverses the whole tree.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt [hunk 3]
```diff
@@ -57,7 +59,8 @@ class DiktatSmokeTest : FixTestBase("test/smoke/src/main/kotlin",
         fixAndCompare("Example2Expected.kt", "Example2Test.kt")
         unfixedLintErrors.assertEquals(
                 LintError(1, 1, "$DIKTAT_RULE_SET_ID:file-naming", "${FILE_NAME_INCORRECT.warnText()} Example2Test.kt_copy", true), // todo this is a false one
-                LintError(1, 1, "$DIKTAT_RULE_SET_ID:header-comment", "${HEADER_MISSING_IN_NON_SINGLE_CLASS_FILE.warnText()} $expectedFileAbsolutePath", false)
+                LintError(1, 1, "$DIKTAT_RULE_SET_ID:header-comment", "${HEADER_MISSING_IN_NON_SINGLE_CLASS_FILE.warnText()} $expectedFileAbsolutePath", false),
+                LintError(1, 1, "$DIKTAT_RULE_SET_ID:data-classes", "${USE_DATA_CLASS.warnText()} TestException", false)
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt:63]: Let's add to code style and to this rule:
`If class extends another class, don't suggest to convert it to data class`

This doesn't make enough sense to make mandatory, even though it's allowed.

**Review by petertrr — CHANGES_REQUESTED** [review]

**Comment by akuleshov7** [comment]
Don't forget that this should also be a data class:
```
class Test {
    var a: Int = 0
        get() = field
        set(value: Int) { field = value}
}
```

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/DataClassesRuleWarnTest.kt [hunk 4]
```diff
@@ -25,7 +26,22 @@ class DataClassesRuleWarnTest : LintTestBase(::DataClassesRule) {
...
     @Test
-    @Tag("USE_DATA_CLASS")
+    @Tag(USE_DATA_CLASS)
+    fun `should trigger - dont forget to consider this class in fix`() {
+        lintMethod(
+                """
+                    |class Test {
+                    |   var a: Int = 0
+                    |          get() = field
+                    |          set(value: Int) { field = value}
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter6/DataClassesRuleWarnTest.kt:36]: I think we should also check if these accessors are trivial. If user has some other logic there, it might be not a very good idea to suggest data class conversion. Maybe, check if accessor's body contains only single expression?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt [hunk 5]
```diff
@@ -64,9 +68,47 @@ class DataClassesRule(private val configRule: List<RulesConfig>) : Rule("data-cl
...
+     */
+    private fun areGoodProps(node: ASTNode): Boolean {
+        val propertiesWithAccessors = node.getAllChildrenWithType(PROPERTY).filter { it.hasChildOfType(PROPERTY_ACCESSOR) }
+
+        if (propertiesWithAccessors.isNotEmpty()) {
+            propertiesWithAccessors.forEach {
+                val accessors = it.getAllChildrenWithType(PROPERTY_ACCESSOR)
+
+                if (!areGoodAccessors(accessors))
+                    return false
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt:88]:
```suggestion
            propertiesWithAccessors.any {
                val accessors = it.getAllChildrenWithType(PROPERTY_ACCESSOR)

                !areGoodAccessors(accessors)
```
I'd rater use operation on collection and then return it's result than place an additional `return` inside the loop.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt [hunk 6]
```diff
@@ -64,9 +68,47 @@ class DataClassesRule(private val configRule: List<RulesConfig>) : Rule("data-cl
...
+
+    @Suppress("UnsafeCallOnNullableType")
+    private fun areGoodAccessors(accessors: List<ASTNode>): Boolean {
+        accessors.forEach {
+            if (it.hasChildOfType(BLOCK)) {
+                val block = it.getFirstChildWithType(BLOCK)!!
+
+                return block
+                        .getChildren(null)
+                        .filter { expr -> expr.psi as? KtExpression != null }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt:103]:
```suggestion
                        .filter { expr -> expr.psi is KtExpression }
```

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt [hunk 7]
```diff
@@ -1,12 +1,14 @@
 package org.cqfn.diktat.ruleset.smoke
 
 import com.pinterest.ktlint.core.LintError
+import org.cqfn.diktat.ruleset.constants.Warnings
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt:4]: Some unused imports in this file?

**Review by petertrr — CHANGES_REQUESTED** [review]
Take a look at snapshot run - you rule detects enum classes as subjects for warning.

**Review by petertrr — APPROVED** [review]
