### PR TITLE
Bugfix. New lines rule(#748)

### LINKED ISSUE #748: Possible bug in NewLinesRule.
## Describe the bug
If class has more than 3 arguments, then each of them should start from new line.
## Expected behavior
```kotlin
class AnnotationNewLineRule(configRules: List<RulesConfig>) : DiktatRule("annotation-new-line", 
configRules,
listOf(ANNOTATION_NEW_LINE)) {
```
## Observed behavior
```kotlin
class AnnotationNewLineRule(configRules: List<RulesConfig>) : DiktatRule("annotation-new-line", configRules, listOf(ANNOTATION_NEW_LINE)) {
```
## Environment information
* diktat version: 0.4.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by aktsay6**
Fixed bug mentioned in linked issue

This pull request closes #748

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt [hunk 1]
```diff
@@ -305,9 +308,15 @@ class NewlinesRule(configRules: List<RulesConfig>) : DiktatRule("newlines", conf
             return
         }
 
+        if (node.elementType == VALUE_ARGUMENT_LIST && !node.hasParent(SUPER_TYPE_LIST)) {
+            // check that it is not listOf(1,2,3...)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:312]:
```suggestion
            // check that it is not function invocation, but only supertype constructor calls
```
```suggestion
            // check that it is not listOf(1,2,3...)
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt [hunk 2]
```diff
@@ -342,6 +352,25 @@ class NewlinesRule(configRules: List<RulesConfig>) : DiktatRule("newlines", conf
             }
         }
 
+    private fun handleFirstValueArgument(node: ASTNode) = node
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:355]: It can be merged with `handleFirstValueParameter` with a couple of additional arguments

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt (hunk 1 above)
Comment (aktsay6) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt]: Fixed

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt (hunk 2 above)
Comment (aktsay6) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt]: Merged

**Review by petertrr — APPROVED** [review]

**Review by aktsay6 — COMMENTED** [review]
@petertrr Please, rereview. There was a bug with function calls and it's arguments. Added tests on it. The change is in NewLinesRule file.

**Review by petertrr — APPROVED** [review]
> @petertrr Please, rereview.

OK, lgtm
