### PR TITLE
Fix for issue #407 - no newline between consecutive braces in autocorrect mode

### LINKED ISSUE #407: No newlines between two consecutive }} after first run of diktat
The code
```kotlin
when (node.elementType) {
            CLASS, FUN, PRIMARY_CONSTRUCTOR, SECONDARY_CONSTRUCTOR -> checkAnnotation(node)
}
```
is being fixed to
```kotlin
when (node.elementType) {
            CLASS, FUN, PRIMARY_CONSTRUCTOR, SECONDARY_CONSTRUCTOR -> checkAnnotation(node)

            else -> {
                // this is a generated else block
            }}
```
even though there should be a newline before the lase `}`

### PR DESCRIPTION
**Pull request by petertrr**
* Fixed issue
* Rearranged rules in DiktatRuleSetProvider
* Added more smoke tests
* Applied diktat code style

This pull request closes #407

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt [hunk 1]
```diff
@@ -46,34 +46,36 @@ class DiktatRuleSetProvider(private val diktatConfigFile: String = "diktat-analy
...
+                ::CommentsFormatting,
+                // naming
                 ::FileNaming,
                 ::PackageNaming,
-                ::StringTemplateFormatRule,
-                ::FileSize,
-                ::DataClassesRule,
                 ::IdentifierNaming,
-                ::LocalVariablesRule,
+                // code structure
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt:59]: may be you will add a comment so we won't change the order of the code in the future?

**Review by akuleshov7 — APPROVED** [review]
lgtm

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt:59]: Yes, good point
