### PR TITLE
Fixing issue in WhiteSpaceRule

### LINKED ISSUE #405: IllegalStateException: treePrev must not be null in WhiteSpaceRule in fix mode
`CliArgument` as of commit https://github.com/cqfn/diKTat/commit/bf1b26a67e85498a4579d38e373a688a14eb137a when `dikat:fix` is run throws this exception. `diktat:check` shows
`/home/runner/work/diKTat/diKTat/diktat-common/src/main/kotlin/org/cqfn/diktat/common/cli/CliArgument.kt:11:24: [WRONG_WHITESPACE] incorrect usage of whitespaces for code separation: ( should have 0 space(s) before and 0 space(s) after, but has 1 space(s) before`.

Investigation shows that it's because of a space between class name and parenthesis:
`data class CliArgument (` throws exception, while `data class CliArgument(` doesn't

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Changed logic
* Added tests

This pull request closes #405

### CODE REVIEW

File: diktat-rules/src/test/resources/test/paragraph3/spaces/WhiteSpaceBeforeLParExpected.kt [hunk 1]
```diff
@@ -15,3 +15,8 @@ class Example : SuperExample {
         when (expression) { }
     }
 }
+
+data class Example(
```
Comment (akuleshov7) [inline diktat-rules/src/test/resources/test/paragraph3/spaces/WhiteSpaceBeforeLParExpected.kt:19]: same bug was with functions?
now it fixes `foo ()`?

**Review by akuleshov7 — APPROVED** [review]
lgtm

File: diktat-rules/src/test/resources/test/paragraph3/spaces/WhiteSpaceBeforeLParExpected.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/test/resources/test/paragraph3/spaces/WhiteSpaceBeforeLParExpected.kt:19]: Thanks, this case was missing in tests. Added.
But diktat fixes it already.
