### PR TITLE
Wrong newlines in functional style

### LINKED ISSUE #321: False-positive of WRONG_NEWLINES - functional style on fully qualified names
```kotlin
java.lang.Boolean.getBoolean(properties.getProperty("parallel.mode"))
```
FQ name `java.lang.Boolean` is detected as a chain of calls by the rule.

### PR DESCRIPTION
**Pull request by aktsay6**
### What's done:
  * Fixed bugs

This pull request closes #321 #326 

## Actions checklist
* [ ] Implemented Rule, added Warnings
* [ ] Added tests on checks
* [ ] Added tests on fixers
* [ ] Updated diktat-analysis.yml
* [ ] Updated available-rules.md

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 1]
```diff
@@ -313,6 +314,14 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
     private fun ASTNode.getParentExpressions() =
             parents().takeWhile { it.elementType in chainExpressionTypes && it.elementType != LAMBDA_ARGUMENT }
 
+    private fun ASTNode.containsManyFunctions() =
+            parents().takeWhile { it.elementType == DOT_QUALIFIED_EXPRESSION }
+                    .lastOrNull()
+                    ?.let {
+                        (Regex("""\((.*?)\)""").findAll(it.text).count()) +
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:321]: Why are you constantly trying to parse code using regex?) You have the entire AST which is already parsed and structured for you.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 2]
```diff
@@ -313,6 +314,14 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
     private fun ASTNode.getParentExpressions() =
             parents().takeWhile { it.elementType in chainExpressionTypes && it.elementType != LAMBDA_ARGUMENT }
 
+    private fun ASTNode.containsManyFunctions() =
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:317]: Initial attempt on this was so that chain of property accesses (without parenthesis) was also considered part of functional style. If I understand correctly, if you count only function calls, you will allow things like
```
list
    .filter {
    }
    .foo.bar.baz
    .forEach { }
```
I suggest instead to only filter out non-call parts of dot qualified expression at the beginning. Everything after the first call in the chain cannot be a fully qualified name.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 3]
```diff
@@ -141,12 +141,13 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
     }
 
+    @Suppress("ComplexMethod")
     private fun handleOperatorWithLineBreakBefore(node: ASTNode) {
         if (node.isDotFromPackageOrImport()) {
             return
         }
         val isIncorrect = node.run {
-            if (isCallsChain()) {
+            if (isCallsChain() && containsManyFunctions()) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:150]: Please add fixme somewhere that we can't distinguish fully qualified names from chain of calls for now (using only AST), but should do it in the future.

**Review by petertrr — CHANGES_REQUESTED** [review]
Take a look at comments. Also, there is another issue in this very logic: #326 . Will it be automatically fixed by change from this PR?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 4]
```diff
@@ -305,6 +309,26 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
                     getAllLeafsWithSpecificType(SAFE_ACCESS, it)
                 }
             }
+            // fixme: we can't distinguish fully qualified names from chain of calls for now
+            ?.filter {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:313]: Maybe, this logic can be done as `dropWhile` on list of `.` and `?.`? This way you won't need to split expressions once again for every element.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 5]
```diff
@@ -502,4 +502,45 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
...
+    @Test
+    @Tag(WarningNames.WRONG_NEWLINES)
+    fun `should not trigger`() {
+        lintMethod(
+                """
+                    |fun foo(): String {
+                    |        val isParallelMode: Boolean
+                    |            get() = java.lang.Boolean.getBoolean(properties.getProperty("parallel.mode"))
+                    |        
+                    |        allProperties.filter {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:515]: Please add examples with safe call on the first expression.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 6]
```diff
@@ -313,6 +337,12 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
     private fun ASTNode.getParentExpressions() =
             parents().takeWhile { it.elementType in chainExpressionTypes && it.elementType != LAMBDA_ARGUMENT }
 
+    private fun isMultilineLambda(node: ASTNode): Boolean {
+        val leftBrace = node.findAllNodesWithSpecificType(LBRACE).firstOrNull()
+
+        return leftBrace != null && leftBrace.treeNext.isWhiteSpaceWithNewline()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:343]: There can be a lambda with parameters after `{`. You could, maybe, just check node type of lambda and then count lines of text.

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 7]
```diff
@@ -306,20 +310,18 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
-
-                    val firstCallee = 1
-                    return@filter if (dotExprs[firstCallee].contains('(') || dotExprs[firstCallee].contains('{')) {
-                        true
-                    } else dotExprs.last().contains('(') || dotExprs.last().contains('{')
-                }
+                // should skip node's that are val params. For example: b.some(z.a()) -> skip z.a()
+                if (it.treeParent.treeParent != null && it.treeParent.treeParent.elementType == VALUE_ARGUMENT)
+                    return@filter false
+                true
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:317]:
```suggestion
                it.treeParent.treeParent != null && it.treeParent.treeParent.elementType == VALUE_ARGUMENT
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 8]
```diff
@@ -306,20 +310,18 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
                     getAllLeafsWithSpecificType(SAFE_ACCESS, it)
                 }
             }
-            // fixme: we can't distinguish fully qualified names from chain of calls for now
             ?.filter {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:313]:
```suggestion
            ?.filterNot {
```

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 9]
```diff
@@ -511,8 +511,47 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
...
+                    |           predicate(it)
+                    |        }
+                    |        .foo()
+                    |        .bar()
+                    |        
+                    |        allProperties?.filter {
+                    |           predicate(it)
+                    |        }
+                    |        .foo()
+                    |        .bar()
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:532]: Please add example with multiline lambda later in the chain:
```
list.foo()
    .bar()
    .filter {
        baz()
    }
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 10]
```diff
@@ -306,20 +310,18 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
+                if (it.treeParent.treeParent != null && it.treeParent.treeParent.elementType == VALUE_ARGUMENT)
+                    return@filter false
+                true
+            }
+            ?.dropWhile { !it.treeParent.textContains('(') && !it.treeParent.textContains('{') }
+            // fixme: we can't distinguish fully qualified names from chain of calls for now
+            ?.filterIndexed { index, it ->
+                // if first callee is multiline lambda, then we let user decide how to line lambda
+                if (index == 0 && isMultilineLambda(it.treeParent))
+                    return@filterIndexed false
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:324]: Why do you use `return` here? You can just write a predicate, it would be more readable.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 11]
```diff
@@ -330,6 +332,10 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
     private fun ASTNode.getParentExpressions() =
             parents().takeWhile { it.elementType in chainExpressionTypes && it.elementType != LAMBDA_ARGUMENT }
 
+    private fun isMultilineLambda(node: ASTNode): Boolean =
+            node.findAllNodesWithSpecificType(LAMBDA_ARGUMENT).firstOrNull()?.text?.count { it == '\n' } ?: -1 > 0
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:336]: Won't `findAllNodesWithSpecificType` trigger on some nested lambdas or lambdas further in a call chain?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 12]
```diff
@@ -278,6 +283,20 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
                 }
     }
 
+
+    private fun ASTNode.getOrderedCallExpressions(elementTypeDot: IElementType, elementTypeSafeCall: IElementType, result: MutableList<ASTNode>) {
+        // if statements here have the only right order - don't change it
+        if (this.isLeaf()) {
+            if (this.elementType == elementTypeDot || this.elementType == elementTypeSafeCall) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:290]: Why do you pass element types via parameters? Won't they always be the same?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 13]
```diff
@@ -294,25 +313,46 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
             ?.run {
                 mutableListOf<ASTNode>().also {
-                    getAllLeafsWithSpecificType(DOT, it)
-                    getAllLeafsWithSpecificType(SAFE_ACCESS, it)
+                    getOrderedCallExpressions(DOT, SAFE_ACCESS, it)
                 }
             }
+            ?.filterNot {
+                // should skip node's that are val params. For example: b.some(z.a()) -> skip z.a()
+                it.treeParent.treeParent != null && it.treeParent.treeParent.elementType == VALUE_ARGUMENT
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:325]: I think there could be other examples when dots are used differently (like type parameters with some qualified class names). I think better approach here will be to collect dots and `?.`s only from actual calls inside `getOrderedCallExpressions`: you could, for example, get `psi as KtDotQualifiedExpression` and then check is right side is qualified expression too and so on. This way you won't need to filter retrieved values afterwards.

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 14]
```diff
@@ -294,25 +330,42 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
             .lastOrNull()
             ?.run {
                 mutableListOf<ASTNode>().also {
-                    getAllLeafsWithSpecificType(DOT, it)
-                    getAllLeafsWithSpecificType(SAFE_ACCESS, it)
+                    getOrderedCallExpressions(psi, it)
                 }
             }
+            ?.dropWhile { !it.treeParent.textContains('(') && !it.treeParent.textContains('{') }
+            // fixme: we can't distinguish fully qualified names from chain of calls for now
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:341]:
```suggestion
            // fixme: we can't distinguish fully qualified names (like java.lang) from chain of property accesses (like list.size) for now
```
Just to be sure we don't forget what this was about

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 15]
```diff
@@ -502,4 +502,73 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
...
+                    |           }
+                    |        }
+                    |}
+                """.trimMargin()
+        )
+    }
+
+    @Test
+    @Tag(WarningNames.WRONG_NEWLINES)
+    fun `should trigger on non-multiline lambdas`() {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:550]: Please add example like
```kotlin
list.filter {

}
.map(::foo).filter {
    bar()
}
```
It should be considered incorrect, when multiline lambda is not the first call.

**Review by petertrr — APPROVED** [review]
LGTM
