### PR TITLE
Recommendation-3.8-no-spaces

### LINKED ISSUE #184: Recommendation 3.8: No spaces should be inserted for horizontal alignment
*Horizontal alignment* - is a practice to add additional spaces in the code, to align code blocks on the same level with previous code blocks.

- It always takes time to format and support such code and fix alignment for new developers in case they need to change something in aligned code.
- Long identifier names will break the alignment and will make the code less presentable.
- The disadvantages of alignment are greater than the benefits; in order to reduce maintenance costs and not cause trouble, misalignment is the best choice.

Recommendation: the only exception where it can look good is `enum class`, where you can use alignment (in table format) to make code more readable:
```kotlin
enum class Warnings(private val id: Int, private val canBeAutoCorrected: Boolean, private val warn: String) : Rule {
    PACKAGE_NAME_MISSING         (1, true,  "no package name declared in a file"),
    PACKAGE_NAME_INCORRECT_CASE  (2, true,  "package name should be completely in a lower case"),
    PACKAGE_NAME_INCORRECT_PREFIX(3, false, "package name should start from company's domain")
    ;
}
```

 Recommended examples：
 ```kotlin
 private val nr: Int // no alignment, but looks fine
 private var color: Color // no alignment
 ```

 Not recommended：
 ```kotlin
 private val    nr: Int    // aligned comment with extra spaces
 private val color: Color  // alignment for a comment and alignment for identifier name
 ```

**You should: support check (warning) and autofix rule that will replace multiple spaces with one space**

### PR DESCRIPTION
**Pull request by aktsay6**
### What's done:
Implemented recommendation for rule 3.8
closes #184 

## Actions checklist
* [x] Implemented Rule, added Warnings
* [x] Added tests on checks
* [ ] Added tests on fixers
* [x] Updated rules-config.json
* [ ] Updated available-rules.md

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+import org.cqfn.diktat.common.config.rules.RulesConfig
+import org.cqfn.diktat.common.config.rules.getRuleConfig
+import org.jetbrains.kotlin.com.intellij.lang.ASTNode
+import org.cqfn.diktat.ruleset.constants.Warnings.TOO_MANY_SPACES
+import org.cqfn.diktat.ruleset.utils.*
+
+class NoSpacesRule : Rule("no-spaces") {
+
+    companion object {
+        private const val MAX_SPACES = 1L
```
Comment (kentr0w) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt:17]: Why is the long type used here?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+
+        if (node.elementType == WHITE_SPACE){
+            checkWhiteSpace(node, configuration)
+        }
+
+    }
+
+
+    private fun checkWhiteSpace(node: ASTNode, configuration: NoSpacesRuleConfiguration) {
+        val space = node.textLength
```
Comment (kentr0w) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt:46]: There is no necessary to use variable

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+
+        if (space > configuration.numberOfSpaces && !node.isWhiteSpaceWithNewline()) {
+            TOO_MANY_SPACES.warn(configRules, emitWarn, isFixMode, "", node.startOffset)
```
Comment (kentr0w) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt:49]: Shouldn't be empty `freeText` in warning

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+        }
+    }
+
+
+
+    class NoSpacesRuleConfiguration(config: Map<String, String>) : RuleConfiguration(config) {
+        val numberOfSpaces = config["spaces"]?.toLongOrNull() ?: MAX_SPACES
```
Comment (kentr0w) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt:56]: Please rename parameter `spaces`  to more understandable

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt [hunk 5]
```diff
@@ -72,6 +72,7 @@ enum class Warnings(private val canBeAutoCorrected: Boolean, private val warn: S
     BACKTICKS_PROHIBITED(false, "Backticks should not be used in identifier's naming. The only exception test methods marked with @Test annotation"),
     REDUNDANT_SEMICOLON(true, "there should be no redundant semicolon at the end of lines"),
     WRONG_NEWLINES(true, "incorrect line breaking"),
+    TOO_MANY_SPACES(true, "too many spaces")
```
Comment (kentr0w) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt:75]: Why there is `true` if you don't have fix

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt [hunk 6]
```diff
@@ -12,7 +12,7 @@ enum class Warnings(private val canBeAutoCorrected: Boolean, private val warn: S
     PACKAGE_NAME_INCORRECT_PREFIX(true, "package name should start from company's domain"),
     // FixMe: should add autofix
     PACKAGE_NAME_INCORRECT_SYMBOLS(false, "package name should contain only latin (ASCII) letters or numbers. For separation of words use dot"),
-    PACKAGE_NAME_INCORRECT_PATH(true, "package name does not match the directory hierarchy for this file, the real package name should be:"),
+    PACKAGE_NAME_INCORRECT_PATH(true, "package name does not match the directory hierarchy for this file, the path to the file is"),
```
Comment (kentr0w) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt:15]: Why?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+                configRules.getRuleConfig(TOO_MANY_SPACES)?.configuration ?: mapOf())
+
+        if (node.elementType == WHITE_SPACE){
+            checkWhiteSpace(node, configuration)
+        }
+
+    }
+
+
+    private fun checkWhiteSpace(node: ASTNode, configuration: NoSpacesRuleConfiguration) {
```
Comment (kentr0w) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt:45]: What about enum?

**Review by kentr0w — CHANGES_REQUESTED** [review]
Make it fixable

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt [hunk 8]
```diff
@@ -35,24 +41,61 @@ class NoSpacesRule : Rule("no-spaces") {
...
+            squeezeSpacesToOne(node, configuration)
+        }
+    }
+
+    private fun isWhitespaceInEnum(node: ASTNode): Boolean {
+        node.parent({it.elementType == CLASS_BODY})
+                ?.parent({it.elementType == CLASS})
+                ?.findChildByType(MODIFIER_LIST)
+                ?.findChildByType(ENUM_KEYWORD)
+                ?: return true
```
Comment (kentr0w) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt:74]: You have to change `true` to `false`

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt [hunk 9]
```diff
@@ -35,24 +41,61 @@ class NoSpacesRule : Rule("no-spaces") {
...
+        } else {
+            squeezeSpacesToOne(node, configuration)
+        }
+
+    }
+
+    private fun checkWhiteSpaceEnum(node: ASTNode, configuration: NoSpacesRuleConfiguration) {
+        val isInEnum = isWhitespaceInEnum(node)
+
+        if (isInEnum) {
```
Comment (kentr0w) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt:64]: I think there will be problem when there isn't emun

**Review by kentr0w — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt [hunk 10]
```diff
@@ -61,19 +57,16 @@ class NoSpacesRule : Rule("no-spaces") {
...
         }
     }
 
     private fun isWhitespaceInEnum(node: ASTNode): Boolean {
-        node.parent({it.elementType == CLASS_BODY})
-                ?.parent({it.elementType == CLASS})
-                ?.findChildByType(MODIFIER_LIST)
-                ?.findChildByType(ENUM_KEYWORD)
-                ?: return true
+        node.parent({it.elementType == ENUM_ENTRY})
```
Comment (kentr0w) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt:66]: I think you can simplify it

**Review by kentr0w — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt (hunk 6 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt:15]: Guys, @aktsay6 @kentr0w, when you resolve conversations where resolution is not obvious, please leave comments.

Really, why?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt [hunk 11]
```diff
@@ -0,0 +1,89 @@
...
+import com.pinterest.ktlint.core.ast.isWhiteSpaceWithNewline
+import com.pinterest.ktlint.core.ast.parent
+import org.cqfn.diktat.common.config.rules.RuleConfiguration
+import org.cqfn.diktat.common.config.rules.RulesConfig
+import org.cqfn.diktat.common.config.rules.getRuleConfig
+import org.jetbrains.kotlin.com.intellij.lang.ASTNode
+import org.cqfn.diktat.ruleset.constants.Warnings.TOO_MANY_SPACES
+import org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.LeafElement
+
+class NoSpacesRule : Rule("no-spaces") {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt:16]: Why `NoSpacesRule`, when it actually is `TooManySpacesRule`? Or even, `ConsecutiveSpacesRule`.

Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt:16]: Please add KDoc with description of this rule.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt [hunk 12]
```diff
@@ -0,0 +1,89 @@
...
+
+    companion object {
+        private const val MAX_SPACES = 1
+    }
+
+
+    private lateinit var configRules: List<RulesConfig>
+    private lateinit var emitWarn: ((offset: Int, errorMessage: String, canBeAutoCorrected: Boolean) -> Unit)
+    private var fileName: String? = null
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/NoSpacesRule.kt:25]: This parameter seems to be unused.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt (hunk 6 above)
Comment (aktsay6) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt:15]: It was merged from master earlier

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ConsecutiveSpacesRuleFixTest.kt [hunk 13]
```diff
@@ -0,0 +1,28 @@
+package org.cqfn.diktat.ruleset.chapter3
+
+import org.cqfn.diktat.common.config.rules.RulesConfig
+import org.cqfn.diktat.ruleset.constants.Warnings
+import org.cqfn.diktat.ruleset.rules.ConsecutiveSpacesRule
+import org.cqfn.diktat.util.FixTestBase
+import org.junit.Test
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/ConsecutiveSpacesRuleFixTest.kt:7]:
```suggestion
import org.junit.jupiter.api.Test
```
Your import is for junit 4, we are using junit 5. Because of the wrong import these tests are not picked up by runner, therefore your code coverage is lower than it should be. Please fix it.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt (hunk 6 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt:15]: The most recent change for this line on master is https://github.com/cqfn/diKTat/commit/19db2eff2096777e128c837537ddb0adc70dd390, but the change has been vice versa. Are you sure you have merged correctly?

Comment (aktsay6) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/constants/Warnings.kt:15]: Seems like a merge mistake

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ConsecutiveSpacesRule.kt [hunk 14]
```diff
@@ -0,0 +1,96 @@
...
+
+    private fun checkWhiteSpaceEnum(node: ASTNode, configuration: TooManySpacesRuleConfiguration) {
+        val isInEnum = isWhitespaceInEnum(node)
+
+        if (!isInEnum) {
+            squeezeSpacesToOne(node, configuration)
+        }
+    }
+
+    private fun isWhitespaceInEnum(node: ASTNode): Boolean = node.parent({it.elementType == ENUM_ENTRY}) != null
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ConsecutiveSpacesRule.kt:72]:
```suggestion
    private fun isWhitespaceInEnum(node: ASTNode): Boolean = node.parent(ENUM_ENTRY) != null
```
There is another overloaded version of this method.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ConsecutiveSpacesRule.kt [hunk 15]
```diff
@@ -0,0 +1,96 @@
...
+
+    private fun squeezeSpacesToOne(node: ASTNode, configuration: TooManySpacesRuleConfiguration) {
+
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ConsecutiveSpacesRule.kt:75]: Our code style prohibits usage of blank lines in the beginning or at the end of code block (see recommendation 3.6 for details), so please remove such lines. Soon it will be checked in CI build, but it's better to fix it already now.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ConsecutiveSpacesRule.kt [hunk 16]
```diff
@@ -0,0 +1,96 @@
...
+        val spaces = node.textLength
+        if (spaces > configuration.numberOfSpaces && !node.isWhiteSpaceWithNewline()) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ConsecutiveSpacesRule.kt:77]: Maybe also check not only that white space doesn't contain newlines, but that it is not followed by EOL comment. There could be more than one space before `//` and it is handled in another rule.

**Review by petertrr — CHANGES_REQUESTED** [review]
Please also add a line in `available-rules.md`.

**Review by petertrr — CHANGES_REQUESTED** [review]
Please re-add the generated `WarningNames` and also add your rule to `available-rules.md`.

File: info/available-rules.md [hunk 17]
```diff
@@ -61,3 +61,4 @@
...
 |    3 |      3.6 | TOO_MANY_BLANK_LINES                    | Check: warns if blank lines are used placed incorrectly.<br>Fix: removes redundant blank lines.                                                                              | yes | BlankLinesWarnTest<br>BlankLinesFixTest                                                                                                                                                                    |                                                                                    - |              
 |    3 |      3.7 | WRONG_WHITESPACE                        | Check: warns if usage of horizontal spaces violates code style guide.<br>Fix: fixes incorrect whitespaces.                                                                   | yes | WhiteSpaceRuleWarnTest<br>WhiteSpaceRuleFixTest                                                                                                                                                            |                         - |                                                                                     - |
+|    3 |      3.8 | TOO_MANY_CONSECUTIVE_SPACES
```
Comment (petertrr) [inline info/available-rules.md:64]: Please add `|` for empty columns too, also please fill description and configuration column, they are important, especially since your warning has some configuration options.

**Review by petertrr — APPROVED** [review]

**Review by kentr0w — APPROVED** [review]
