### PR TITLE
Fix for issue #415 - WHEN_WITHOUT_ELSE doesn't recognize when expression in when branch

### LINKED ISSUE #415: WHEN_WITHOUT_ELSE doesn't recognize when expression in when branch
## Describe the bug
```kotlin
when (expr1) {
    is Type1 -> when (expr1.field) {
                is Type2 -> when (foo(epxr1)) {
                    SomeEnum.Field1 -> bar()
                    SomeEnum.Field2 -> baz()
                }
}
```
the `when` in `is Type2` is not treated as an expression (it's treated as a statement, though it's an expression).

## Expected behavior
WHEN_WITHOUT_ELSE shouldn't check when expressions at all until we have type resolution.

## Environment information
* diktat version: 0.1.2

### PR DESCRIPTION
**Pull request by petertrr**
This pull request closes #415

### CODE REVIEW

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/WhenMustHaveElseWarnTest.kt [hunk 1]
```diff
@@ -73,4 +73,21 @@ class WhenMustHaveElseWarnTest : LintTestBase(::WhenMustHaveElseRule) {
...
+    fun `regression - shouldn't check when in when branches and assignments`() {
+        lintMethod(
+            """
+                    |fun foo() {
+                    |    var x: Int
+                    |    x = when(it) {
+                    |        1 -> when (x) {
+                    |            2 -> foo()
+                    |        }
+                    |    }
```
Comment (akuleshov7) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/WhenMustHaveElseWarnTest.kt:88]: 2 else should be here? why no warnings?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhenMustHaveElseRule.kt [hunk 2]
```diff
@@ -69,21 +69,27 @@ class WhenMustHaveElseRule(private val configRules: List<RulesConfig>) : Rule("n
...
     private fun isStatement(node: ASTNode) : Boolean {
-
         // Checks if there is return before when
         if (node.hasParent(RETURN)) {
             return false
         }
 
+        // Checks if `when` is the last statement in lambda body
         if (node.treeParent.elementType == BLOCK && node.treeParent.treeParent.elementType == FUNCTION_LITERAL) {
             if (node.treeParent.lastChildNode == node) {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhenMustHaveElseRule.kt:79]: why not a single statement :)

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/WhenMustHaveElseWarnTest.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/WhenMustHaveElseWarnTest.kt:88]: Because in this cases return value of `when` expression is used afterwards, and the compiler can check whether the choice is exhaustive. Since we don't have information about expression type, we don't check these cases at all.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhenMustHaveElseRule.kt (hunk 2 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhenMustHaveElseRule.kt:79]: It's not my code, but I can change :)

**Review by akuleshov7 — APPROVED** [review]
lgtm
