### PR TITLE
Fix bug with incorrect reordering of enum classes

### LINKED ISSUE #843: autofix for `WRONG_ORDER_IN_CLASS_LIKE_STRUCTURES` removes values from enum class
## Describe the bug

Applying autofix for the rule `WRONG_ORDER_IN_CLASS_LIKE_STRUCTURES` via the Gradle plugin (`./gradlew diktatFix`) can result in values being removed from an enum class such as the following:

```
enum class Enum {
  FOO,
  BAR,
  ;

  companion object
  fun f() {}
}
```

## Expected behavior

The function definition and the companion object should be swapped, resulting in the following file:
```
enum class Enum {
  FOO,
  BAR,
  ;

  fun f() {}
  companion object
}
```

The above is passes `./gradlew diktatCheck`.

## Observed behavior

The autofix removes the values from the enum class, resulting in the following file:

```
enum class Enum {
  fun f() {}

  companion object
}
```

## Steps to Reproduce

Run autofix against a project containing an enum class such as the one described above, e.g. via `./gradlew diktatFix` when using the Gradle plugin.

## Environment information
* diktat version: 0.5.0
* build tool (maven/gradle): Gradle, v6.8.3
* how is diktat run (CLI, plugin, etc.):
* kotlin version: 1.4.32 (kotlin-compiler-embeddable-1.4.30)
* JDK: Corretto-11.0.7.10.1
* operating system: GNU/Linux; Ubuntu 20.04

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Changed code style guide - properties are considered loggers only if they are private
* Fixed bug in logic
* Added tests
* Added smoke tests
* Refactoring

This pull request closes #843

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt [hunk 1]
```diff
@@ -73,49 +75,21 @@ class ClassLikeStructuresOrderRule(configRules: List<RulesConfig>) : DiktatRule(
...
+        val blocks = Blocks(
+            (node.psi as KtClassBody).enumEntries.map { it.node },
+            AllProperties(loggers, constProperties, properties, lateInitProperties),
+            objects.toMutableList(), initBlocks, constructors, methods, usedClasses,
+            companionObject.toMutableList(), unusedClasses
+        )
             .allBlockFlattened()
             .map { astNode ->
-                Pair(astNode, astNode.siblings(false).takeWhile { it.elementType == WHITE_SPACE || it.isPartOfComment() }.toList())
+                listOf(astNode) + astNode.siblings(false).takeWhile { it.elementType == WHITE_SPACE || it.isPartOfComment() }.toList()
```
Comment (aktsay6) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt:89]: Do we need to check Annotations in here?

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt:89]: I think, annotations are usually part of node with declaration, specifically part of modifier list. Can you give any example that would break with this logic?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt [hunk 2]
```diff
@@ -73,49 +75,21 @@ class ClassLikeStructuresOrderRule(configRules: List<RulesConfig>) : DiktatRule(
         val initBlocks = node.getChildren(TokenSet.create(CLASS_INITIALIZER)).toMutableList()
         val constructors = node.getChildren(TokenSet.create(SECONDARY_CONSTRUCTOR)).toMutableList()
         val methods = node.getChildren(TokenSet.create(FUN)).toMutableList()
-        val (usedClasses, unusedClasses) = node
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt:76]: not able to understand where was the issue because of the refactoring, could you please provide some info?

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt:76]: We are explicitly choosing class elements to sort. We were simply skipping enum members, now I added handling of them. I believe there are no more unexpected class elements that are not covered.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt (hunk 1 above)
Comment (aktsay6) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt:89]: Yeah, forgot that they are in modifier list. Then everything should be fine

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt [hunk 3]
```diff
@@ -150,6 +124,47 @@ class ClassLikeStructuresOrderRule(configRules: List<RulesConfig>) : DiktatRule(
...
+                    }
+            } ?: false
+        }
+        .let { it.first.toMutableList() to it.second.toMutableList() }
+
+    /**
+     * @param blocks list of class elements with leading whitespaces and comments
+     */
+    @Suppress("UnsafeCallOnNullableType")
+    private fun ASTNode.checkAndReorderBlocks(blocks: List<List<ASTNode>>) {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt:147]: do we need an assert or require in this method? If it is too dangerous, then do not add

**Comment by akuleshov7** [comment]
```allProperties.filter { it.findLeafWithSpecificType(CONST_KEYWORD) != null }.toMutableList()```
at least this part can be moved to functions

**Comment by akuleshov7** [comment]
why do we select different properties? and after that unify them:
```
 AllProperties(loggers, constProperties, properties, lateInitProperties),
```

this is useless, no?

**Comment by akuleshov7** [comment]
```node.getChildren(TokenSet.create(FUN)).toMutableList()```
this can be moved to a different function

**Comment by petertrr** [comment]
> why do we select different properties? and after that unify them:
> 
> ```
>  AllProperties(loggers, constProperties, properties, lateInitProperties),
> ```
> 
> **this is useless, no?**

We group them in four distinct blocks and then arrange in order of these blocks. I believe I introduced this class so that `Blocks` wouldn't have too much arguments

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt (hunk 3 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt:147]: What sort of assert do you mean?

Comment (akuleshov7) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt:135]: by ASTNode type

**Review by akuleshov7 — APPROVED** [review]
lgtm

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt (hunk 3 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/ClassLikeStructuresOrderRule.kt:135]: Added a not in KDocs
