### PR TITLE
Fix of #85 - fixed check for package names of files under src/test

### LINKED ISSUE #85: diktat incorrectly calculates package name (domain name duplication)
```
[INFO]    [ktlint] C:\Users\pwx5333130\Documents\diKTat\diktat-common\src\test\kotlin\org\cqfn\diktat\test\JsonReaderTest.kt:1:9: [5] package name does not match the directory hierarchy for this file, the path to the file is: org.cqfn.diktat.test.org.cqfn.diktat.test
```

### PR DESCRIPTION
**Pull request by petertrr**
This fixes #85 

### What's done:
* Fixed bug in logic
* Added tests

### CODE REVIEW

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackageNamingWarnTest.kt [hunk 1]
```diff
@@ -131,4 +131,22 @@ class PackageNamingWarnTest {
                 rulesConfigList = rulesConfigList
         )
     }
+
+    @Test
+    fun `regression - incorrect warning on file under test directory`() {
```
Comment (akuleshov7) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter1/PackageNamingWarnTest.kt:136]: same - please check that you have updated tests list in docs
