### PR TITLE
Recommendation 3.7 parts 7, 8 and 9

### LINKED ISSUE #151: Recommendation 3.7: Usage of whitespace for code separation
1. Any keywords (like 'if', 'when', 'for', e.t.c) should be separated with a single whitespace from the opening parenthesis.
     Only exceptions are: 'super' and 'constructor' keywords. They should not be separated from a parenthesis.

  2. Separate any keywords (such as `else` or `catch`, etc.) from the opening brace ('{') with a single whitespace.
  
  3. Use single whitespace before any opening brace (`{`).
     Only exception is passing a lambda as an argument inside parenthesis:
     ```kotlin
         private fun foo(a: (Int) -> Int, b: Int) {}
         foo({x: Int -> x}, 5) // no space before '{'
     ```

  4. Single whitespace should be placed on both sides of binary operators. This also applies to operator-like symbols, for example: 

     - Colon in generic structures with 'where' keyword： `where T : Type`
     - Arrow in lambdas： `(str: String) -> str.length()`

  **Exceptions：**

  - Two colons (`::`) are written without spaces: `Object::toString`
  - Dot separator (`.`) that stays on the same line with an object name: `object.toString()`

  5. Spaces should be used after ',',':',';' (except cases when those symbols are in the end of line). There should be no whitespaces in the end of line.

  6. There should be *only one space* between identifier and it's type： `list: List<String>`
  
  7. When using '[]' operator (get/set) there should be *no* spaces between identifier and '[': `someList[0]`
  
  8. There should be no space between a method name and a parenthesis: `foo() {}`

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Added inspections for braces, brackets and parenthesis
* Do not count spaces before EOL comments
* Refactoring

This pull request closes #151 (parts 7,8 and 9 - this is the last pull request for that issue).

## Actions checklist
* [x] Implemented Rule, added Warnings
* [x] Added tests on checks
* [ ] Added tests on fixers

### CODE REVIEW

**Review by akuleshov7 — APPROVED** [review]
lgtm

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/WhiteSpaceRuleWarnTest.kt [hunk 1]
```diff
@@ -16,10 +16,11 @@ class WhiteSpaceRuleWarnTest {
 
     private val lbraceWarn = "${WRONG_WHITESPACE.warnText()} there should be a whitespace before '{'"
     private val eolSpaceWarn = "${WRONG_WHITESPACE.warnText()} there should be no spaces in the end of line"
-    private fun binaryOpWarn(op: String, before: Int?, after: Int?, reqBefore: Int, reqAfter: Int?) =
-//            "${WRONG_WHITESPACE.warnText()} $op should ${if (isException) "not " else ""}be surrounded by whitespaces"
-            "${WRONG_WHITESPACE.warnText()} $op should have $reqBefore space(s) before" +
-                    (if (reqAfter != null) " and $reqAfter space(s) after" else "") +
+    private fun tokenWarn(token: String, before: Int?, after: Int?, reqBefore: Int?, reqAfter: Int?) =
+            "${WRONG_WHITESPACE.warnText()} $token should have" +
```
Comment (akuleshov7) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/WhiteSpaceRuleWarnTest.kt:20]: you know how I don't like such code with "if"s, but lgtm anyway

Comment (petertrr) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/spaces/WhiteSpaceRuleWarnTest.kt:20]: Well, this method in for tests only, and there would be a lot of branches, so I thought that poor readability won't hurt much in this particular case :)
