### PR TITLE
Interface vs Data class bug#1003

### LINKED ISSUE #1003: Interfaces are violating the USE_DATA_CLASS rule
## Describe the bug

Interfaces are violating the USE_DATA_CLASS rule.

## Expected behavior

Interfaces cannot be data classes, so this should not happen.

## Steps to Reproduce

Have an interface with simple fields:

```kotlin
interface MutationResponse {
    val code: String
    val success: Boolean
    val message: String
}
```

## Environment information
* diktat version: 1.0.0-rc.2
* build tool (maven/gradle): gradle
* how is diktat run (CLI, plugin, etc.): plugin
* kotlin version: 1.5.21
* operating system: macOS
* link to a project (if your project is public):

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
- Fixed bug
- Added test
- Closes #1003

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/DataClassesRule.kt [hunk 1]
```diff
@@ -144,12 +145,12 @@ class DataClassesRule(configRules: List<RulesConfig>) : DiktatRule(
     }
 
     @Suppress("UnsafeCallOnNullableType")
-    private fun ASTNode.isDataClass(): Boolean {
+    private fun ASTNode.isDataClassOrInterface(): Boolean {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/DataClassesRule.kt:148]: That's a weird method, why not use `node.psi as KtClass`, which probably already has both checks for data and interface modifiers?

**Review by petertrr — CHANGES_REQUESTED** [review]

**Review by petertrr — APPROVED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/DataClassesRule.kt (hunk 1 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/DataClassesRule.kt]: Thanks, fixed
