### PR TITLE
Bugfix. Fix documentation generation(#647)

### LINKED ISSUE #647: Fixing documentation generation
Document generation do not produce appropriate whitepaper

### PR DESCRIPTION
**Pull request by aktsay6**
Fixed documentation generation process

This pull request closes #647

### CODE REVIEW

File: info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationAvailableRules.kt [hunk 1]
```diff
@@ -18,7 +18,7 @@ fun generateAvailableRules(rootDir: File, wpDir: File) {
         .map { it[2].replace("\\s+".toRegex(), "") to it[5] }
         .forEach { ruleMap[it.first]!!.config = it.second}
     val newText = File(wpDir, "sections/appendix.tex").readLines().toMutableList()
-    newText.removeAll(newText.subList(newText.indexOf("\\section*{available-rules}") + 1, newText.indexOf("\\section*{\\textbf{Diktat Coding Convention}}")))
+    newText.removeAll(newText.subList(newText.indexOf("\\section*{available-rules}") + 1, newText.indexOf("\\lstMakeShortInline[basicstyle=\\ttfamily\\bfseries]`")))
```
Comment (petertrr) [inline info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationAvailableRules.kt:21]: I believe, there is still no section `available-rules`? Will `fromIndex` always be 0?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationAvailableRules.kt (hunk 1 above)
Comment (aktsay6) [reply info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationAvailableRules.kt]: Added new section

File: info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt [hunk 2]
```diff
@@ -131,6 +133,27 @@ enum class FindType {
     ;
 }
 
+private fun handleHyperlinks(line: String): String {
+    var correctedString = line
+    if (correctedString.contains(HYPERLINKS)) {
+        val hyperlinkSubString = HYPERLINKS.find(correctedString)!!.groupValues
+        hyperlinkSubString.forEach {
+            var link = Regex("""\(http.*\)""").find(it)!!.groupValues.first().drop(1).dropLast(1) // drop ( and )
```
Comment (petertrr) [inline info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt:141]: Isn't it better to introduce captured groups in `HYPERLINKS` regex and retrieve them there instead of having two additional regexes?

File: info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt [hunk 3]
```diff
@@ -131,6 +133,27 @@ enum class FindType {
...
+            // need to replace back, because it is a hyperlink
+            link = link.replace("\\#", "#")
+            link = link.replace("\\&", "&")
+            link = link.replace("\\_", "_")
+            var text = Regex("""\[.*]""").find(it)!!.groupValues.first()
+            // need to replace ` in hyperlink, because it breaks latex compilation
+            text = text.replace("`", "")
```
Comment (petertrr) [inline info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt:148]: Maybe, replace with quotes that don't break latex? Do `'` fit here?

File: info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt [hunk 4]
```diff
@@ -131,6 +133,27 @@ enum class FindType {
...
+            val hyperlink = """\\href{${link}}{${text}}"""
```
Comment (petertrr) [inline info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt:149]:
```suggestion
            val hyperlink = """\\href{$link}{$text}"""
```

File: info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt [hunk 5]
```diff
@@ -131,6 +133,27 @@ enum class FindType {
...
+    var correctedString = line
+    if (correctedString.contains(HYPERLINKS)) {
+        val hyperlinkSubString = HYPERLINKS.find(correctedString)!!.groupValues
+        hyperlinkSubString.forEach {
+            var link = Regex("""\(http.*\)""").find(it)!!.groupValues.first().drop(1).dropLast(1) // drop ( and )
+            // need to replace back, because it is a hyperlink
+            link = link.replace("\\#", "#")
+            link = link.replace("\\&", "&")
+            link = link.replace("\\_", "_")
+            var text = Regex("""\[.*]""").find(it)!!.groupValues.first()
```
Comment (petertrr) [inline info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt:146]: I think, `[]` should be dropped here as well.

**Review by petertrr — CHANGES_REQUESTED** [review]

File: info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt (hunk 3 above)
Comment (aktsay6) [reply info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt:148]: Backticks make words highlighting in markdown.  Can we delete them here, because it will be highlighted as hyperlink?

Comment (petertrr) [reply info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt:148]: Backticks can highlight code inside link text [like `this`](https://example.com). Do we really have such cases in our text? Aren't all code snippets already converted to `texttt` in your converter? 
I think it should be safe to remove them here, though.

File: info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt [hunk 6]
```diff
@@ -131,6 +133,27 @@ enum class FindType {
...
+        val hyperlinkSubString = HYPERLINKS.findAll(correctedString)
+        hyperlinkSubString.forEach {
+            var (text, link) = HYPERLINKS.find(it.value)!!.destructured
+            // need to replace back, because it is a hyperlink
+            link = link.trim().drop(1).dropLast(1) // drop ( and )
+            link = link.replace("\\#", "#")
+            link = link.replace("\\&", "&")
+            link = link.replace("\\_", "_")
+            // need to replace ` in hyperlink, because it breaks latex compilation
+            text = text.replace("`", "")
```
Comment (petertrr) [inline info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt:148]: I think you still need to remove `[]` from `text` here: now it looks like `\href{https://docs.oracle.com/en/Kotlin/Kotlinse/11/tools/KDoc.html}{[Official Document]}` in tex. Are these brackets rendered too? If yes, they are not needed in the rendered result, link should be just highlighted.

**Review by petertrr — CHANGES_REQUESTED** [review]

File: info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt (hunk 6 above)
Comment (aktsay6) [reply info/buildSrc/src/main/kotlin/org/cqfn/diktat/generation/docs/GenerationDocs.kt:148]: Fixed

File: info/guide/diktat-coding-convention.md [hunk 7]
```diff
@@ -1,3 +1,22 @@
+<img src="/logo.svg" width="64px"/>
+
+# Diktat Coding Convention
```
Comment (petertrr) [inline info/guide/diktat-coding-convention.md:3]: This is old format of TOC, it's updated in master now. Please check and support new format in both generators from TOC.md to full guide md and then from full guide to tex.

**Review by petertrr — CHANGES_REQUESTED** [review]
Just remembered about TOC, other changes look good.

File: info/guide/diktat-coding-convention.md (hunk 7 above)
Comment (aktsay6) [reply info/guide/diktat-coding-convention.md]: Added

**Review by petertrr — APPROVED** [review]
