### PR TITLE
Fix Conflicting TOO_MANY_BLANK_LINES and BRACES_BLOCK_STRUCTURE_ERROR with empty block

### LINKED ISSUE #791: Conflicting TOO_MANY_BLANK_LINES and BRACES_BLOCK_STRUCTURE_ERROR with empty block
## Describe the bug
```kotlin
foo {

}
```
in check mode produces two errors:
```
[TOO_MANY_BLANK_LINES] too many consecutive blank lines: do not put newlines in the beginning of code blocks
[BRACES_BLOCK_STRUCTURE_ERROR] braces should follow 1TBS style: no newline before closing brace
```
in fix mode everything is fine, because, I suppose, the first inspection removes the blank line and the second restores it.

## Environment information
* diktat version: 0.4.1

### PR DESCRIPTION
**Pull request by Cheshiriks**
### What's done:
* Fixed Conflicting TOO_MANY_BLANK_LINES and BRACES_BLOCK_STRUCTURE_ERROR with empty block in lambda
closes #791

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BlockStructureBraces.kt [hunk 1]
```diff
@@ -232,7 +233,12 @@ class BlockStructureBraces(configRules: List<RulesConfig>) : DiktatRule(
         if (!configuration.closeBrace) {
             return
         }
-        val space = node.findChildByType(RBRACE)!!.treePrev
+        var space = node.findChildByType(RBRACE)!!.treePrev
+        node.findParentNodeWithSpecificType(ElementType.LAMBDA_ARGUMENT)?.let {
+            if (space.text == "") {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BlockStructureBraces.kt:238]:
```suggestion
            if (space.text.isEmpty()) {
```

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example8Expected.kt [hunk 2]
```diff
@@ -0,0 +1,10 @@
+package org.cqfn.diktat
+
+/*
+ * Copyright (c) Your Company Name Here. 2010-2020
+ */
+
+fun foo() {
+    run { }
```
Comment (petertrr) [inline diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example8Expected.kt:8]: Doesn't `EmptyBlock` trigger in this case?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/BlankLinesRule.kt [hunk 3]
```diff
@@ -44,6 +46,16 @@ class BlankLinesRule(configRules: List<RulesConfig>) : DiktatRule(
             it.elementType == BLOCK && it.treeParent?.elementType != SCRIPT ||
                     it.elementType == CLASS_BODY || it.elementType == FUNCTION_LITERAL
         }) {
+            node.findParentNodeWithSpecificType(LAMBDA_ARGUMENT)?.let {
+                if ((node.treeNext?.treeNext?.elementType == RBRACE) && (node.treePrev.elementType == LBRACE)) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/BlankLinesRule.kt:50]: What does `treeNext.treeNext` here correspond to? If `node` is `WHITE_SPACE` here, I'd expect `treeNext` to be a `LBRACE`.

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/BlankLinesRule.kt (hunk 3 above)
Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/BlankLinesRule.kt:50]: Lambda body is always has a BLOCK
{ } - (LBRACE, WHITE_SPACE, BLOCK "", RBRACE)

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/BlankLinesRule.kt:50]: Oh, that's not obvious :) Please add a comment in code describing it.

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example8Expected.kt (hunk 2 above)
Comment (Cheshiriks) [reply diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example8Expected.kt:8]: No. The smoke test works out correctly. Probably the rule doesn't work for lambda.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BlockStructureBraces.kt [hunk 4]
```diff
@@ -232,7 +233,12 @@ class BlockStructureBraces(configRules: List<RulesConfig>) : DiktatRule(
         if (!configuration.closeBrace) {
             return
         }
-        val space = node.findChildByType(RBRACE)!!.treePrev
+        var space = node.findChildByType(RBRACE)!!.treePrev
+        node.findParentNodeWithSpecificType(ElementType.LAMBDA_ARGUMENT)?.let {
+            if (space.text.isEmpty()) {
+                space = space.treePrev
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BlockStructureBraces.kt:239]: This line is marked as not covered with tests. Which case does this branch cover? Is it present in tests?
(Maybe this rule is activated after BlankLines rule? Then this check might be redundant)

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example8Expected.kt (hunk 2 above)
Comment (petertrr) [reply diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example8Expected.kt:8]: Please check, I'm sure I have seen it trigger on lambdas before.

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BlockStructureBraces.kt (hunk 4 above)
Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BlockStructureBraces.kt:239]: This rule always worked for lambda with empty BLOCK. Since the BLOCK node was checked, but not checked WHITE_SPACE

Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BlockStructureBraces.kt:239]: I will add a test for this bug

**Review by akuleshov7 — CHANGES_REQUESTED** [review]
why is not fixed and merged yet, @Cheshiriks

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/EmptyBlock.kt [hunk 5]
```diff
@@ -41,12 +37,26 @@ class EmptyBlock(configRules: List<RulesConfig>) : DiktatRule(
...
+    @Suppress("UnsafeCallOnNullableType", "TOO_LONG_FUNCTION")
     private fun checkEmptyBlock(node: ASTNode, configuration: EmptyBlockStyleConfiguration) {
         if (node.treeParent.isOverridden() || isAnonymousSamClass(node)) {
             return
         }
         if (node.isBlockEmpty()) {
+            node.findParentNodeWithSpecificType(ElementType.LAMBDA_ARGUMENT)?.let {
+                // Lambda body is always has a BLOCK -> run { } - (LBRACE, WHITE_SPACE, BLOCK "", RBRACE)
+                if (!configuration.emptyBlockExist && isEmptyWhiteSpace(node)) {
+                    val freeText = "do not put newlines in empty lambda"
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/EmptyBlock.kt:52]: It should be configurable

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/EmptyBlock.kt [hunk 6]
```diff
@@ -41,12 +37,26 @@ class EmptyBlock(configRules: List<RulesConfig>) : DiktatRule(
         checkEmptyBlock(newNode, configuration)
     }
 
-    @Suppress("UnsafeCallOnNullableType")
+    private fun isEmptyWhiteSpace(node: ASTNode) =
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/EmptyBlock.kt:40]: The method's name is confusing. Why does it return `true` if there is no white space? Also, it doesn't check for empty white space, it checks for newlines.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BlockStructureBraces.kt [hunk 7]
```diff
@@ -233,6 +234,11 @@ class BlockStructureBraces(configRules: List<RulesConfig>) : DiktatRule(
             return
         }
         val space = node.findChildByType(RBRACE)!!.treePrev
+        node.findParentNodeWithSpecificType(ElementType.LAMBDA_ARGUMENT)?.let {
+            if (space.text.isEmpty()) {
+                return
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/BlockStructureBraces.kt:239]: Hm, still marked as not covered. Are you sure there is an empty `BLOCK` node in the new test example?

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EmptyBlockWarnTest.kt [hunk 8]
```diff
@@ -125,24 +139,9 @@ class EmptyBlockWarnTest : LintTestBase(::EmptyBlock) {
...
+                    |   val y = listOf<Int>().map { } 
                     |}
-                """.trimMargin(),
-            LintError(2, 30, ruleId, "${EMPTY_BLOCK_STRUCTURE_ERROR.warnText()} empty blocks are forbidden unless it is function with override keyword", false)
-        )
-    }
-
-    @Test
-    @Tag(WarningNames.EMPTY_BLOCK_STRUCTURE_ERROR)
-    fun `check empty lambda with config`() {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/EmptyBlockWarnTest.kt:137]: Why did you remove this test, it was checking behavior with different configuration flag

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/EmptyBlock.kt [hunk 9]
```diff
@@ -41,7 +36,10 @@ class EmptyBlock(configRules: List<RulesConfig>) : DiktatRule(
         checkEmptyBlock(newNode, configuration)
     }
 
-    @Suppress("UnsafeCallOnNullableType")
+    private fun isNewLine(node: ASTNode) =
+            node.findChildByType(WHITE_SPACE)?.text?.contains("\n") ?: true
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/EmptyBlock.kt:40]: Why is it `true` when white space node is missing?

**Review by akuleshov7 — APPROVED** [review]
Lgtm

**Review by petertrr — APPROVED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/EmptyBlock.kt (hunk 9 above)
Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/EmptyBlock.kt]: Yes, there must be a false
