### PR TITLE
Bugfix. False positives in UNUSED_IMPORT

### LINKED ISSUE #742: False positives in UNUSED_IMPORT
## Describe the bug
Unused imports rule should not check `get` and `set` methods that can use brackets notation:
```kotlin
import com.example.get

val a = list[1]  // equivalent to list.get(1) using com.example.get
```

## Environment information
* diktat version: 0.4.0

### PR DESCRIPTION
**Pull request by Cheshiriks**
### What's done:
  * Fixed bug

This pull request closes #742

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/FileStructureRule.kt [hunk 1]
```diff
@@ -245,14 +246,19 @@ class FileStructureRule(configRules: List<RulesConfig>) : DiktatRule("file-struc
...
     private fun findAllReferences(node: ASTNode) {
-        node.findAllNodesWithSpecificType(OPERATION_REFERENCE)?.forEach { ref ->
+        node.findAllNodesWithSpecificType(OPERATION_REFERENCE).forEach { ref ->
             if (!ref.isPartOf(IMPORT_DIRECTIVE)) {
-                operatorMap.filterValues { it == ref.text }.keys.forEach { key -> refSet.add(key) }
+                val references = operatorMap.filterValues { it == ref.text }
+                if (references.isNotEmpty()) {
+                    references.keys.forEach { key -> refSet.add(key) }
+                } else {
+                    refSet.add(ref.text)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/FileStructureRule.kt:255]: Why is this branch needed? Does it catch infix functions? Please add a comment in code

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTest.kt [hunk 2]
```diff
@@ -327,4 +327,52 @@ class FileStructureRuleTest : LintTestBase(::FileStructureRule) {
...
+    @Tag(WarningNames.UNUSED_IMPORT)
+    fun `Ignore Imports`() {
+        lintMethod(
+            """
+                |package org.cqfn.diktat.example
+                |
+                |import com.example.get
+                |
+                |fun main() {
+                |   val a = list[1]
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTest.kt:373]: Please also add all ignored imports into this example

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/FileStructureRule.kt [hunk 3]
```diff
@@ -247,16 +247,24 @@ class FileStructureRule(configRules: List<RulesConfig>) : DiktatRule("file-struc
...
+                }
+                else {
+                    refSet.add(ref.text)
+                }
             }
         }
         node.findAllNodesWithSpecificType(REFERENCE_EXPRESSION)?.forEach {
             if (!it.isPartOf(IMPORT_DIRECTIVE)) {
-                refSet.add(it.text)
+                refSet.add(it.text.replace("`", ""))
```
[the remark this answers is not in the document]
Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/FileStructureRule.kt:261]: The _importedName_ method removes the quotes, but the node._text_ method does not. Therefore, the _equals_ method returns false.

[the remark this answers is not in the document]
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/FileStructureRule.kt:261]: Ok, that makes sense. Since it's not obvious, please add a comment in code about it.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/FileStructureRule.kt (hunk 1 above)
Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/FileStructureRule.kt:255]: Yes. This is needed to check infix  functions that relate to OPERATION_REFERENCE

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTest.kt [hunk 4]
```diff
@@ -327,4 +327,54 @@ class FileStructureRuleTest : LintTestBase(::FileStructureRule) {
             """.trimMargin(),
         )
     }
+
+    @Test
+    @Tag(WarningNames.UNUSED_IMPORT)
+    fun `Operator overloading 2`() {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/FileStructureRuleTest.kt:333]:
```suggestion
    fun `Should correctly check infix functions`() {
```
Please also add a negative example - when infix function is imported and unused, there should be a warning.

**Review by petertrr — CHANGES_REQUESTED** [review]

**Review by petertrr — APPROVED** [review]
LGTM
