### PR TITLE
Bugfixes in Indentation Rule

### LINKED ISSUE #349: More bugs in IndentationRule
* Indentation is not increased after an arrow in when expression
* `?:` on a start of a new line should be indented like elements in a chain of calls
* code
    ```kotlin
        constructor(resourceFilePath: String,
                    ruleSupplier: (rulesConfigList: List<RulesConfig>) -> Rule,
                    rulesConfigList: List<RulesConfig>? = null,
                    cb: (LintError, Boolean) -> Unit = defaultCallback) : this(resourceFilePath,
            { overrideRulesConfigList -> DiktatRuleSetProvider4Test(ruleSupplier, overrideRulesConfigList) }, cb, rulesConfigList)

    ```
    get fixed to
    ```kotlin
        constructor(resourceFilePath: String,
                                         ruleSupplier: (rulesConfigList: List<RulesConfig>) -> Rule,
                                         rulesConfigList: List<RulesConfig>? = null,
                                         cb: (LintError, Boolean) -> Unit = defaultCallback) : this(resourceFilePath,
            { overrideRulesConfigList -> DiktatRuleSetProvider4Test(ruleSupplier, overrideRulesConfigList) }, cb, rulesConfigList)

    ```
* when there are comments in dot-calls chain, indentation of statement right after a comment is too long
* exceptional indentation is broken after a comment, even though it should spread on the statement after comment

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Increased indentation after an arrow in when expressions
* Increased indentation before elvis
* Fixed error in aligning parameters
* when there are comments in dot-calls chain, indentation of statement right after a comment is too long
* exceptional indentation is broken after a comment, even though it should spread on the statement after comment
* `as`, `is` and other infix functions should increase indentation
* Tests
* Code style fixes

This pull request closes #349

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/IndentationRule.kt [hunk 1]
```diff
@@ -195,6 +187,19 @@ class IndentationRule(private val configRules: List<RulesConfig>) : Rule("indent
         }
     }
 
+    private fun ASTNode.getExceptionalIndentInitiator() = treeParent.let { parent ->
+        when (parent.psi) {
+            // fixme: custom logic for determining exceptional indent initiator, should be moved elsewhere
+            is KtDotQualifiedExpression -> {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/IndentationRule.kt:193]: braces not needed?
and yes I would also move it away

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/indentation/Checkers.kt [hunk 2]
```diff
@@ -84,8 +96,15 @@ internal class ValueParameterListChecker(configuration: IndentationConfig) : Cus
                     }
 
             val expectedIndent = if (parameterAfterLpar != null && configuration.alignedParameters && parameterList.elementType == VALUE_PARAMETER_LIST) {
-                // fixme: probably there is a better way to find column number
-                parameterList.parents().last().text.substringBefore(parameterAfterLpar.text).lines().last().count()
+                // count column number of the first parameter
+                val ktFile = whiteSpace.parents.last() as KtFile
+                ktFile.text
+                        .lineSequence()
+                        .scan(0 to "") { (length, _), s -> length + s.length + 1 to s }
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/indentation/Checkers.kt:103]: please add comments of what are you doing here or move to some method. Now it looks like some hack, I do not understand

**Review by akuleshov7 — APPROVED** [review]
approved

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/indentation/Checkers.kt (hunk 2 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/indentation/Checkers.kt:103]: Yes, I will add comments. Basically, I just find a particular line using node's offset and then calculate column number for this node.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/IndentationRule.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/IndentationRule.kt:193]: At first there was hack for only one case, but now that there are several I think it should be extracted to `CheckResult`, for example. I think I'll better do it in the next PR, because this is for sure not the last bug in indentation logic.
