### PR TITLE
NPE in AstNodeUtils

### LINKED ISSUE #137: NPE inside `ASTNodeUtils.findLBrace`
```
[INFO]    [ktlint] C:\Users\pwx5333130\Documents\diktat-fresh\diktat-common\src\main\kotlin\org\cqfn\diktat\common\config\rules\RulesConfigReader.kt:18:1: Internal Error (diktat-ruleset:empty-block-structure). Please create a ticket at https://github.com/pinterest/ktlint/issues (if possible, provide the source code that triggered an error) (cannot be auto-corrected)
[INFO]    [ktlint] C:\Users\pwx5333130\Documents\diktat-fresh\diktat-common\src\test\kotlin\org\cqfn\diktat\test\JsonReaderTest.kt:11:40: Internal Error (diktat-ruleset:empty-block-structure). Please create a ticket at https://github.com/pinterest/ktlint/issues (if possible, provide the source code that triggered an error) (cannot be auto-corrected)
```

The problem code (as by offset provided from the error):
```
@JsonIgnoreProperties(ignoreUnknown = true)
```
```
filter { it.name == "CLASS_NAME_INCORRECT" && it.enabled }
```

Here is the error:
```
[INFO]    [ktlint] Caused by: kotlin.KotlinNullPointerException
[INFO]    [ktlint] 	at org.cqfn.diktat.ruleset.utils.AstNodeUtilsKt.findLBrace(AstNodeUtils.kt:324)
[INFO]    [ktlint] 	at org.cqfn.diktat.ruleset.rules.EmptyBlock.searchNode(EmptyBlock.kt:42)
[INFO]    [ktlint] 	at org.cqfn.diktat.ruleset.rules.EmptyBlock.visit(EmptyBlock.kt:38)
[INFO]    [ktlint] 	at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:167)
[INFO]    [ktlint] 	... 18 more
```

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
  Made safe call function for class and object declaration
   closes #137

### CODE REVIEW

File: diktat-rules/src/test/resources/test/paragraph3/empty_block/EmptyBlockExpected.kt [hunk 1]
```diff
@@ -16,3 +16,6 @@ fun goo () {
     while (x > 0)
         --x
 }
+
```
Comment (akuleshov7) [inline diktat-rules/src/test/resources/test/paragraph3/empty_block/EmptyBlockExpected.kt:19]: I guess this time we need to have more tests

Comment (petertrr) [reply diktat-rules/src/test/resources/test/paragraph3/empty_block/EmptyBlockExpected.kt:19]: Well, cases with NPE have been discovered during check of our own code with diktat and NPEs were present in snapshot CI build. Now they are gone at least for `diktat-common`. @kentr0w have you run check locally for other modules? Please do and comment if there are any errors left in this rule.

Comment (kentr0w) [reply diktat-rules/src/test/resources/test/paragraph3/empty_block/EmptyBlockExpected.kt:19]: I tested on other modules and there were no similar errors.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 2]
```diff
@@ -347,7 +347,7 @@ fun ASTNode.findLBrace(): ASTNode? {
         ElementType.WHEN -> this.findChildByType(ElementType.LBRACE)!!
         ElementType.FOR, ElementType.WHILE, ElementType.DO_WHILE ->
             this.findChildByType(ElementType.BODY)?.findChildByType(ElementType.BLOCK)?.findChildByType(ElementType.LBRACE)
-        ElementType.CLASS, ElementType.OBJECT_DECLARATION -> this.findChildByType(ElementType.CLASS_BODY)!!.findChildByType(ElementType.LBRACE)
+        ElementType.CLASS, ElementType.OBJECT_DECLARATION -> this.findChildByType(ElementType.CLASS_BODY)?.findChildByType(ElementType.LBRACE)
         ElementType.FUNCTION_LITERAL -> this.findChildByType(LBRACE)
         else -> this.findChildByType(ElementType.BLOCK)?.findChildByType(ElementType.LBRACE)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:352]: Which cases are currently covered by `else` branch? I think it's better to specify them explicitly.

Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt]: I Added new cases, but I'm not sure i handled them all

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt]: Then I suggest to return `null` from `else` and also log, which node type was given, like it's done in similar case in another rule, see `WhiteSpaceRule.handleColon`.

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt]: Actually, it's not a good idea, because we will spam a lot in logs, let's keep simple `return null`.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 3]
```diff
@@ -343,13 +343,14 @@ fun ASTNode.moveChildBefore(childToMove: ASTNode, beforeThisNode: ASTNode?, with
...
+        ElementType.THEN, ElementType.ELSE, ElementType.FUN, ElementType.TRY, ElementType.CATCH, ElementType.FINALLY ->
+            this.findChildByType(ElementType.BLOCK)?.findChildByType(ElementType.LBRACE)
         ElementType.WHEN -> this.findChildByType(ElementType.LBRACE)!!
         ElementType.FOR, ElementType.WHILE, ElementType.DO_WHILE ->
             this.findChildByType(ElementType.BODY)?.findChildByType(ElementType.BLOCK)?.findChildByType(ElementType.LBRACE)
-        ElementType.CLASS, ElementType.OBJECT_DECLARATION -> this.findChildByType(ElementType.CLASS_BODY)!!.findChildByType(ElementType.LBRACE)
+        ElementType.CLASS, ElementType.OBJECT_DECLARATION -> this.findChildByType(ElementType.CLASS_BODY)?.findChildByType(ElementType.LBRACE)
         ElementType.FUNCTION_LITERAL -> this.findChildByType(LBRACE)
-        else -> this.findChildByType(ElementType.BLOCK)?.findChildByType(ElementType.LBRACE)
+        else -> return null
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:353]:
```suggestion
        else -> null
```

**Review by petertrr — APPROVED** [review]
