### PR TITLE
FP in AnnotationNewLineRule with comment

### LINKED ISSUE #609: FP ANNOTATION_NEW_LINE when there is a comment after an annotation
## Describe the bug
```kotlin
@ExperimentalStdlibApi  // to use `scan` on sequence
    @Suppress("WRONG_NEWLINES")
    override fun checkNode() {}
```

## Observed behavior
`[ANNOTATION_NEW_LINE] annotations must be on new line: @ExperimentalStdlibApi not on a single line`

## Environment information
* diktat version: 0.1.6-SNAPSHOT

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
   Fixed bug and added tests
   closes #609 

## Fixme
  The fix is ​​not working correctly.

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 1]
```diff
@@ -138,12 +141,31 @@ fun ASTNode.isFollowedByNewline() =
             it.treeNext.elementType == WHITE_SPACE && it.treeNext.text.contains("\n")
         } ?: false
 
+/**
+ * This function is similar to isFollowedByNewline(), but there may be a comment after the node
+ */
+fun ASTNode.isFollowedByNewlineWithComment() =
+        parent({ it.treeNext != null && it.treeNext.treeNext != null }, strict = false)?.let {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:148]:
```suggestion
        parent({ it.treeNext?.treeNext != null }, strict = false)?.let {
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 2]
```diff
@@ -138,12 +141,31 @@ fun ASTNode.isFollowedByNewline() =
...
+            it.treeNext.treeNext.elementType == EOL_COMMENT && it.treeNext.treeNext.isFollowedByNewline()
+        } ?: false ||
+                parent({ it.treeNext != null }, strict = false)?.let {
+                    it.treeNext.run {
+                        when (elementType) {
+                            WHITE_SPACE -> text.contains("\n")
+                            EOL_COMMENT -> isFollowedByNewline()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:155]:
```suggestion
                            EOL_COMMENT, BLOCK_COMMENT, KDOC -> isFollowedByNewline()
```
All other types of comments can occupy a single line, so we should cover cases like `foo() /* comment */` too

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 3]
```diff
@@ -138,12 +141,31 @@ fun ASTNode.isFollowedByNewline() =
             it.treeNext.elementType == WHITE_SPACE && it.treeNext.text.contains("\n")
         } ?: false
 
+/**
+ * This function is similar to isFollowedByNewline(), but there may be a comment after the node
+ */
+fun ASTNode.isFollowedByNewlineWithComment() =
+        parent({ it.treeNext != null && it.treeNext.treeNext != null }, strict = false)?.let {
+            it.treeNext.treeNext.elementType == EOL_COMMENT && it.treeNext.treeNext.isFollowedByNewline()
+        } ?: false ||
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:150]: I think, you should change these branches order: at first check `treeNext`, which should be enough for most of cases, and if it doesn't give us enough information, check `treeNext.treeNext`.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 4]
```diff
@@ -138,12 +141,31 @@ fun ASTNode.isFollowedByNewline() =
...
+                parent({ it.treeNext != null }, strict = false)?.let {
+                    it.treeNext.run {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:152]:
```suggestion
                parent({ it.treeNext != null }, strict = false)
                    ?.treeNext.run {
```
If `let` contains only a single call on `it`, you can just remove it.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 5]
```diff
@@ -138,12 +141,31 @@ fun ASTNode.isFollowedByNewline() =
...
+                            WHITE_SPACE -> text.contains("\n")
+                            EOL_COMMENT -> isFollowedByNewline()
+                            else -> false
+                        }
+                    }
+                } ?: false
+
 /**
  * Checks if there is a newline before this element. See [isFollowedByNewline] for motivation on parents check.
+ * Also there is
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:163]: hm?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 6]
```diff
@@ -138,12 +141,31 @@ fun ASTNode.isFollowedByNewline() =
...
  */
 fun ASTNode.isBeginByNewline() =
         parent({ it.treePrev != null }, strict = false)?.let {
-            it.treePrev.elementType == WHITE_SPACE && it.treePrev.text.contains("\n")
+            it.treePrev.elementType == WHITE_SPACE && it.treePrev.text.contains("\n") ||
+                    (it.treePrev.elementType == IMPORT_LIST && it.treePrev.isLeaf() && it.treePrev.treePrev.isLeaf())
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:168]: Why do you need to check imports separately? Does it apply to other nodes in the beginning of the file too?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt (hunk 5 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:163]: Forgot to end comment)

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt (hunk 6 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:168]: I added KDOC for this

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 7]
```diff
@@ -138,12 +143,31 @@ fun ASTNode.isFollowedByNewline() =
             it.treeNext.elementType == WHITE_SPACE && it.treeNext.text.contains("\n")
         } ?: false
 
+/**
+ * This function is similar to isFollowedByNewline(), but there may be a comment after the node
+ */
+fun ASTNode.isFollowedByNewlineWithComment() =
+        parent({ it.treeNext != null }, strict = false)?.let { astNode ->
+            astNode.treeNext.run {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:151]:
```suggestion
        parent({ it.treeNext != null }, strict = false)
            ?.treeNext.run {
```
I don't think you need this additional scope here.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 8]
```diff
@@ -138,12 +143,31 @@ fun ASTNode.isFollowedByNewline() =
...
+
 /**
  * Checks if there is a newline before this element. See [isFollowedByNewline] for motivation on parents check.
+ * Or if there is nothing before, it cheks, that there are empty imports and package before (Every FILE node has children of type IMPORT_LIST and PACKAGE)
  */
 fun ASTNode.isBeginByNewline() =
         parent({ it.treePrev != null }, strict = false)?.let {
-            it.treePrev.elementType == WHITE_SPACE && it.treePrev.text.contains("\n")
+            it.treePrev.elementType == WHITE_SPACE && it.treePrev.text.contains("\n") ||
+                    (it.treePrev.elementType == IMPORT_LIST && it.treePrev.isLeaf() && it.treePrev.treePrev.isLeaf())
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:170]: Is `treePrev.treePrev` always not null here? Can it be guaranteed or should be checked?

**Review by petertrr — APPROVED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt (hunk 8 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:170]: Yes, because each `FILE` node contains `PACKAGE_DIRECTIVE` before `IMPORT_LIST`
