### PR TITLE
Fixing bug with lineNumber in autocorrect mode

### LINKED ISSUE #371: IndexOutOfBoundsException when calculating line number in fixing mode
For example, when `diktat:fix@diktat` is run on `TestComparatorUnit` as of commit https://github.com/cqfn/diKTat/commit/6dbf1b0639c718bee8fb2e150d3e8ca3046a91af, the following error occurs (error arises from tree mutations and `getLineNumber` operating on old offsets and doesn't depend on runner):
```
[ERROR] Unhandled exception during rule execution: 
com.pinterest.ktlint.core.RuleExecutionException: java.lang.IndexOutOfBoundsException: Wrong offset: 2040. Should be in range: [0, 2019]
    at com.pinterest.ktlint.core.KtLint$format$2.invoke (KtLint.kt:384)
    at com.pinterest.ktlint.core.KtLint$format$2.invoke (KtLint.kt:43)
    at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke (KtLint.kt:246)
    at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke (KtLint.kt:43)
    at com.pinterest.ktlint.core.KtLint.visit (KtLint.kt:572)
    at com.pinterest.ktlint.core.KtLint.visit (KtLint.kt:573)
    at com.pinterest.ktlint.core.KtLint.visit (KtLint.kt:573)
    at com.pinterest.ktlint.core.KtLint.visit (KtLint.kt:573)
    at com.pinterest.ktlint.core.KtLint.access$visit (KtLint.kt:43)
    at com.pinterest.ktlint.core.KtLint$visitor$2.invoke (KtLint.kt:244)
    at com.pinterest.ktlint.core.KtLint$visitor$2.invoke (KtLint.kt:43)
    at com.pinterest.ktlint.core.KtLint.format (KtLint.kt:369)
    at org.cqfn.diktat.plugin.maven.DiktatFixMojo.runAction (DiktatMojo.kt:38)
    at org.cqfn.diktat.plugin.maven.DiktatBaseMojo.checkFile (DiktatBaseMojo.kt:134)
    at org.cqfn.diktat.plugin.maven.DiktatBaseMojo.checkDirectory (DiktatBaseMojo.kt:108)
    at org.cqfn.diktat.plugin.maven.DiktatBaseMojo.execute (DiktatBaseMojo.kt:74)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: java.lang.IndexOutOfBoundsException: Wrong offset: 2040. Should be in range: [0, 2019]
    at org.jetbrains.kotlin.com.intellij.openapi.editor.impl.LineSet.findLineIndex (LineSet.java:178)
    at org.jetbrains.kotlin.com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber (DocumentImpl.java:991)
    at com.pinterest.ktlint.core.ast.PackageKt.lineNumber (package.kt:235)
    at org.cqfn.diktat.ruleset.utils.AstNodeUtilsKt.isGoingAfter (AstNodeUtils.kt:521)
    at org.cqfn.diktat.ruleset.utils.VariableSearchASTUtilsKt.getAllUsagesOfProperty (VariableSearchASTUtils.kt:63)
    at org.cqfn.diktat.ruleset.utils.VariableSearchASTUtilsKt.getAllUsages (VariableSearchASTUtils.kt:49)
    at org.cqfn.diktat.ruleset.rules.ImmutableValNoVarRule.visit (ImmutableValNoVarRule.kt:39)
    at com.pinterest.ktlint.core.KtLint$format$2.invoke (KtLint.kt:374)
    at com.pinterest.ktlint.core.KtLint$format$2.invoke (KtLint.kt:43)
    at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke (KtLint.kt:246)
    at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke (KtLint.kt:43)
    at com.pinterest.ktlint.core.KtLint.visit (KtLint.kt:572)
    at com.pinterest.ktlint.core.KtLint.visit (KtLint.kt:573)
    at com.pinterest.ktlint.core.KtLint.visit (KtLint.kt:573)
    at com.pinterest.ktlint.core.KtLint.visit (KtLint.kt:573)
    at com.pinterest.ktlint.core.KtLint.access$visit (KtLint.kt:43)
    at com.pinterest.ktlint.core.KtLint$visitor$2.invoke (KtLint.kt:244)
    at com.pinterest.ktlint.core.KtLint$visitor$2.invoke (KtLint.kt:43)
    at com.pinterest.ktlint.core.KtLint.format (KtLint.kt:369)
    at org.cqfn.diktat.plugin.maven.DiktatFixMojo.runAction (DiktatMojo.kt:38)
    at org.cqfn.diktat.plugin.maven.DiktatBaseMojo.checkFile (DiktatBaseMojo.kt:134)
    at org.cqfn.diktat.plugin.maven.DiktatBaseMojo.checkDirectory (DiktatBaseMojo.kt:108)
    at org.cqfn.diktat.plugin.maven.DiktatBaseMojo.execute (DiktatBaseMojo.kt:74)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
```

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Use getLineNumber everywhere
* Added test

This pull request closes #371

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 1]
```diff
@@ -517,11 +531,37 @@ data class ReplacementResult(val oldNodes: List<ASTNode>, val newNodes: List<AST
...
+
+fun ASTNode.getLineNumber(isFixMode: Boolean): Int? =
+    if (!isFixMode) {
+        lineNumber()
+    } else {
+        calculateLineNumber()
+    }
+
+/**
+ * This function calculates line number instead of using cached values.
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:551]: I thought we discussed it and decided that ktlint calculates everything correctly.
So why it is needed?

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:551]: We discussed it regarding warning messages, but we also use line number in some rules (e.g., method `ASTNode.isBefore`), and when AST has already been mutated by previous rules, it leads to `ArrayIndexOutOfBoundsException` (see #371).

**Review by aktsay6 — APPROVED** [review]
lgtm
