### PR TITLE
Enum order breaks white space

### LINKED ISSUE #721: Not able to use simple enum formatting
## Describe the bug
```kotlin
package org.cqfn.realth.domain

enum class IssueType {
    VCS, PROJECT_STRUCTURE, TESTS
}
```
should be allowed, but is fixed into
```kotlin
package org.cqfn.diktat.org.cqfn.realth.domain

enum class IssueType {
    PROJECT,
    TESTS,
    VCS
}
```
and emits unfixed warnings for `ENUMS_SEPARATED`.

## Environment information
* diktat version: 0.3.0

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
   Rewrote algorithm to swap element
  closes #721

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SortRule.kt [hunk 1]
```diff
@@ -80,12 +82,11 @@ class SortRule(private val configRules: List<RulesConfig>) : Rule("sort-rule") {
...
         nonSortList: List<ASTNode>,
         node: ASTNode) {
+        val spaceBefore = nonSortList.map { astNode -> astNode.prevSibling { it.elementType == WHITE_SPACE } }
         val nodeBefore: ASTNode? = nonSortList.last().treeNext
         node.removeRange(nonSortList.first(), nonSortList.last().treeNext)
         sortList.forEachIndexed { nodeIndex, astNode ->
-            if (nodeIndex != 0) {
-                node.addChild(PsiWhiteSpaceImpl("\n"), nodeBefore)
-            }
+            spaceBefore[nodeIndex]?.let { node.addChild(it, nodeBefore) }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SortRule.kt:89]: OK, so now you keep spaces when swapping enum members. But how did it lead to the error described in the issue? Is it something to do with enum members without spaces between them (`A,B` instead of `A, B`) or is something with interaction between this rule and `WhitespaceRule` or `NewlinesRule`? Also, what happens if input contains members without space after comma?

Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SortRule.kt:97]: The error was in the `swapSortNodes` method. In our algorithm, after each insertion of the correct element, we also insert a new line

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt [hunk 2]
```diff
@@ -80,12 +83,18 @@ class SortRule(private val configRules: List<RulesConfig>) : Rule("sort-rule") {
         sortList: List<ASTNode>,
         nonSortList: List<ASTNode>,
         node: ASTNode) {
+        val spaceBefore = nonSortList.map { astNode ->
+            val nodeBefore = astNode.prevSibling { it.elementType == WHITE_SPACE || it.elementType == ENUM_ENTRY }
+            if (nodeBefore?.elementType == WHITE_SPACE) {
+                nodeBefore
+            } else {
+                null
+            }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt:92]:
```suggestion
            nodeBefore?.takeIf { it.elementType == WHITE_SPACE }
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt [hunk 3]
```diff
@@ -80,12 +83,18 @@ class SortRule(private val configRules: List<RulesConfig>) : Rule("sort-rule") {
         sortList: List<ASTNode>,
         nonSortList: List<ASTNode>,
         node: ASTNode) {
+        val spaceBefore = nonSortList.map { astNode ->
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt:86]: It'll be better to collect all previous sibling till `ENUM_ENTRY`. This way you will be able to store comments while sorting:
```kotlin
enum class Example {
    A /* comment about A */, B,  // comment about B
    C 
}
```

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SortRule.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/SortRule.kt]: Yes, I see now, OK.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt [hunk 4]
```diff
@@ -71,11 +78,47 @@ class SortRule(configRules: List<RulesConfig>) : DiktatRule("sort-rule", configR
...
+            val nodeBefore = astNode.prevSibling { it.elementType == WHITE_SPACE || it.elementType == ENUM_ENTRY }
+            if (nodeBefore?.elementType == WHITE_SPACE) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt:83]: `takeIf`?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt [hunk 5]
```diff
@@ -71,11 +78,47 @@ class SortRule(configRules: List<RulesConfig>) : DiktatRule("sort-rule", configR
...
+            node.addChild(astNode, nodeBefore)
+        }
+    }
+
+    private fun swapSortEnumEntry(
+        sortList: List<ASTNode>,
+        nonSortList: List<ASTNode>,
+        node: ASTNode) {
+        val spaceBefore = if (node.findAllNodesWithSpecificType(EOL_COMMENT).isNotEmpty()) {
+            val lastEntry = node.findAllNodesWithSpecificType(ENUM_ENTRY).last()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt:102]: Isn't it `nonSortList.last()`?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt [hunk 6]
```diff
@@ -71,11 +78,47 @@ class SortRule(configRules: List<RulesConfig>) : DiktatRule("sort-rule", configR
...
+            if (lastEntry.hasChildOfType(EOL_COMMENT) && !lastEntry.hasChildOfType(COMMA)) {
+                lastEntry.addChild(LeafPsiElement(COMMA, ","), lastEntry.findChildByType(EOL_COMMENT))
+            }
+            listOf(null) + List(nonSortList.size - 1) { listOf(PsiWhiteSpaceImpl("\n")) }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt:106]: Maybe, use `buildList` instead, or at least `repeat` instead of `List`? Also, you can check `if (index == 0)` inside second argument of `List`, it'll be better than lists concat

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt [hunk 7]
```diff
@@ -71,11 +78,47 @@ class SortRule(configRules: List<RulesConfig>) : DiktatRule("sort-rule", configR
...
+        } else {
+            nonSortList.map { astNode ->
+                astNode
+                    .siblings(false)
+                    .toList()
+                    .takeWhile { it.isWhiteSpace() || it.isPartOfComment() }
+                    .ifEmpty { null }
+            }
+        }
+        val nodeBefore: ASTNode? = nonSortList.last().treeNext
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt:116]: Why is `treeNext` called `before`?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt (hunk 3 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt:81]: What about this? Or are these nodes included in `ENUM_ENTRY`?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt (hunk 5 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt:102]: Yes, fixed

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt (hunk 7 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/SortRule.kt:116]: Because this node  is used as a parameter `before` in `addChild` mothod. But I renamed it.

**Review by petertrr — APPROVED** [review]
