### PR TITLE
Correct fix with string concat

### LINKED ISSUE #914: KotlinParseException: Your text is not valid
The exception occurs on the project okhttp

[ERROR] 2021-06-09 16:15:57 Internal error has occurred in class-compact-initialization. Please make an issue on this bug at https://github.com/cqfn/diKTat/.
org.cqfn.diktat.ruleset.utils.KotlinParseException: Your text is not valid
        at org.cqfn.diktat.ruleset.utils.KotlinParser.createNode(KotlinParser.kt:75)
        at org.cqfn.diktat.ruleset.utils.KotlinParser.createNode$default(KotlinParser.kt:75)
        at org.cqfn.diktat.ruleset.rules.chapter6.classes.CompactInitialization.getOrCreateApplyBlock(CompactInitialization.kt:124)
        at org.cqfn.diktat.ruleset.rules.chapter6.classes.CompactInitialization.moveAssignmentIntoApply(CompactInitialization.kt:80)
        at org.cqfn.diktat.ruleset.rules.chapter6.classes.CompactInitialization.access$moveAssignmentIntoApply(CompactInitialization.kt:30)
        at org.cqfn.diktat.ruleset.rules.chapter6.classes.CompactInitialization$handleProperty$2$1.invoke(CompactInitialization.kt:72)
        at org.cqfn.diktat.ruleset.rules.chapter6.classes.CompactInitialization$handleProperty$2$1.invoke(CompactInitialization.kt:71)
        at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix(Warnings.kt:259)
        at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix$default(Warnings.kt:201)

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
- Fixed bug
- Added comment and tests
- Fixed #914

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt [hunk 1]
```diff
@@ -282,7 +283,22 @@ class LineLength(configRules: List<RulesConfig>) : DiktatRule(
         val incorrectText = wrongStringTemplate.node.text
         val firstPart = incorrectText.substring(0, wrongStringTemplate.delimiterIndex)
         val secondPart = incorrectText.substring(wrongStringTemplate.delimiterIndex, incorrectText.length)
-        wrongStringTemplate.node.treeParent.replaceChild(wrongStringTemplate.node, KotlinParser().createNode("$firstPart\" +\n\"$secondPart"))
+        val correctNode =
+            try {
+                KotlinParser().createNode("$firstPart\" +\n\"$secondPart")
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:288]: I think we need to just not put any pluses in ```${}``` block, no?
Need to check if we are in `${}` write now or not. If yes - add a new line

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:288]: I wanted to suggest the same. We can find the current node by offset, and if it is text - add concatenation, else - simply add a line break

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt [hunk 2]
```diff
@@ -143,8 +143,18 @@ class LineLength(configRules: List<RulesConfig>) : DiktatRule(
...
-        val leftOffset = positionByOffset(node.startOffset).second
-        val delimiterIndex = node.text.substring(0, configuration.lineLength.toInt() - leftOffset).lastIndexOf(' ')
+        var multiLineOffset = 0
+        val (nodeText, leftOffset) = if (node.text.lines().size > 1 ) {
+            node
+                .text
+                .lines()
+                .takeWhile { it.length < configuration.lineLength }
+                .forEach { multiLineOffset += it.length }
+            node.text.lines().find { it.length > 120 }!! to positionByOffset(node.psi.findElementAt(multiLineOffset + 1)!!.node.startOffset).second
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:153]: Hardcoded 120? 😠

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt [hunk 3]
```diff
@@ -457,7 +480,7 @@ class LineLength(configRules: List<RulesConfig>) : DiktatRule(
             val hasNewLineBefore: Boolean,
             val indexLastSpace: Int = 0) : LongLineFixableCases()
 
-        class StringTemplate(val node: ASTNode, val delimiterIndex: Int) : LongLineFixableCases()
+        class StringTemplate(val node: ASTNode, val delimiterIndex: Int, val multiLineOffset: Int) : LongLineFixableCases()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:483]: Maybe, make `multiLineOffset` `Int?` to better indicate, that string is single line if it is `null` instead of `0`?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt [hunk 4]
```diff
@@ -278,11 +288,24 @@ class LineLength(configRules: List<RulesConfig>) : DiktatRule(
         node.replaceChild(whiteSpaceAfterPlus, PsiWhiteSpaceImpl("\n"))
     }
 
+    @Suppress("UnsafeCallOnNullableType", "COMMENT_WHITE_SPACE")
     private fun fixStringTemplate(wrongStringTemplate: LongLineFixableCases.StringTemplate) {
         val incorrectText = wrongStringTemplate.node.text
         val firstPart = incorrectText.substring(0, wrongStringTemplate.delimiterIndex)
         val secondPart = incorrectText.substring(wrongStringTemplate.delimiterIndex, incorrectText.length)
-        wrongStringTemplate.node.treeParent.replaceChild(wrongStringTemplate.node, KotlinParser().createNode("$firstPart\" +\n\"$secondPart"))
+        val isSplitInWhiteSpace = wrongStringTemplate.multiLineOffset == 0 && wrongStringTemplate.node.psi.findElementAt(wrongStringTemplate.delimiterIndex)!!.node.isWhiteSpace()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:296]: Please provide some comments explaining, why is number of lines connected with being split at white space

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt (hunk 3 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:483]: I think it will be better when we check if `multiLineOffset == 0`, but when we calculate this variable, it will be worse

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt [hunk 5]
```diff
@@ -293,6 +294,7 @@ class LineLength(configRules: List<RulesConfig>) : DiktatRule(
         val incorrectText = wrongStringTemplate.node.text
         val firstPart = incorrectText.substring(0, wrongStringTemplate.delimiterIndex)
         val secondPart = incorrectText.substring(wrongStringTemplate.delimiterIndex, incorrectText.length)
+        // wrongStringTemplate.multiLineOffset equals zero if string in one line
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:297]: That's not what I meant :) Why do you check if split is at white space only for single-line string?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt [hunk 6]
```diff
@@ -278,11 +289,26 @@ class LineLength(configRules: List<RulesConfig>) : DiktatRule(
...
     }
 
+    @Suppress("UnsafeCallOnNullableType", "COMMENT_WHITE_SPACE")
     private fun fixStringTemplate(wrongStringTemplate: LongLineFixableCases.StringTemplate) {
         val incorrectText = wrongStringTemplate.node.text
         val firstPart = incorrectText.substring(0, wrongStringTemplate.delimiterIndex)
         val secondPart = incorrectText.substring(wrongStringTemplate.delimiterIndex, incorrectText.length)
-        wrongStringTemplate.node.treeParent.replaceChild(wrongStringTemplate.node, KotlinParser().createNode("$firstPart\" +\n\"$secondPart"))
+        // wrongStringTemplate.multiLineOffset equals zero if string in one line
+        // if wrongStringTemplate.multiLineOffset isn't equal to 0, it means that string is multiline, which means that split should be without quote
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:298]: With or without? If we are inside a multiline string, we should split it with quote and concatenation, shouldn't we? Also, for multiline strings we are not checking any methods like `trimIndent()`:
```kotlin
val string = """
    first line
    veryy looooooooooooooooong second line
""".trimIndent()
```
how will we split it?

**Review by akuleshov7 — APPROVED** [review]
please fix the remarks and merge

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt [hunk 7]
```diff
@@ -142,9 +142,25 @@ class LineLength(configRules: List<RulesConfig>) : DiktatRule(
...
+        val leftOffset = if (node.text.lines().size > 1) {
+            node
+                .text
+                .lines()
+                .takeWhile { it.length < configuration.lineLength }
+                .forEach { multiLineOffset += it.length }
+            node
+                .text
+                .lines()
+                .find { it.length > configuration.lineLength }!!
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:157]:
```suggestion
                .first { it.length > configuration.lineLength }
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt [hunk 8]
```diff
@@ -142,9 +142,25 @@ class LineLength(configRules: List<RulesConfig>) : DiktatRule(
...
+                .takeWhile { it.isWhitespace() }
+                .count()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:159]:
```suggestion
                .count { it.isWhitespace() }
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt [hunk 9]
```diff
@@ -154,13 +170,19 @@ class LineLength(configRules: List<RulesConfig>) : DiktatRule(
             // can't fix this case
             return LongLineFixableCases.None
         }
+        // check, that space to split is a part of text - not code
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:173]: Please add a comment, why we can't fix it if it is code. Btw, shouldn't we treat it as an expression in completely separate branch of this rule?

**Review by petertrr — APPROVED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt (hunk 8 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:159]: But this is not the same

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt (hunk 9 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:173]: I added comment. No, because if code inside string is longer than expected, it will fixed. I added tests for this case.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt (hunk 8 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/LineLength.kt:159]: Oh, yeah, you are right, my bad
