### PR TITLE
Bugfix. Lambda passed as an argument is forced to be on the same line as the previous argument

### LINKED ISSUE #490: Lambda passed as an argument is forced to be on the same line as the previous argument
## Describe the bug
```kotlin
fun foo() {
    foo(
        0,
        { obj -> obj.bar() }
    )
}
```
=>
```kotlin
fun foo() {
    foo(
            0, { obj -> obj.bar() }
    )
}
```

## Environment information
* diktat version: 0.1.3

### PR DESCRIPTION
**Pull request by aktsay6**
### What's done:
  * Fixed bugs

This pull request closes #490

### CODE REVIEW

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example1Test.kt [hunk 1]
```diff
@@ -18,13 +18,13 @@ return   x+ y}
             this.replace("\\", "/")        .replace("//", "/")
                     .split("/")
 
-
     fun foo(x :  Int
             ,
-             y: Int ): Int {
```
Comment (petertrr) [inline diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example1Test.kt:24]: Are changes in this file intentional?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/WhiteSpaceRule.kt [hunk 2]
```diff
@@ -203,7 +203,8 @@ class WhiteSpaceRule(private val configRules: List<RulesConfig>) : Rule("horizon
                     whitespaceOrPrevNode.treeParent.removeChild(whitespaceOrPrevNode)
                 }
             }
-        } else if (prevNode.elementType !in keywordsWithSpaceAfter) {
+        } else if (prevNode.elementType !in keywordsWithSpaceAfter && prevNode.elementType != COMMA) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/WhiteSpaceRule.kt:206]: Does this mean that cases like `foo(x,     { bar(it) }) won't be fixed now?

**Review by petertrr — CHANGES_REQUESTED** [review]

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/WhiteSpaceRule.kt [hunk 3]
```diff
@@ -188,22 +188,28 @@ class WhiteSpaceRule(private val configRules: List<RulesConfig>) : Rule("horizon
...
                 }
                 ?: false
+
         val prevNode = whitespaceOrPrevNode.let { if (it.elementType == WHITE_SPACE) it.treePrev else it }
         val numWhiteSpace = whitespaceOrPrevNode.numWhiteSpaces()
         // note: the conditions in the following `if`s cannot be collapsed into simple conjunctions
         if (isFromLambdaAsArgument) {
-            if (numWhiteSpace != 0) {
+            val isFirstArgument = node
+                    .parents()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/WhiteSpaceRule.kt:200]:
```suggestion
                    .parent({ it.elementType == VALUE_ARGUMENT })
```
no need to analyze all parents here

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/WhiteSpaceRule.kt [hunk 4]
```diff
@@ -188,22 +188,28 @@ class WhiteSpaceRule(private val configRules: List<RulesConfig>) : Rule("horizon
...
+                    .let { it[2].prevSibling { prevNode -> prevNode.elementType == COMMA } == null }
+
+            if (numWhiteSpace != 0 && isFirstArgument) {
                 WRONG_WHITESPACE.warnAndFix(configRules, emitWarn, isFixMode, "there should be no whitespace before '{' of lambda" +
                         " inside argument list", node.startOffset, node) {
                     whitespaceOrPrevNode.treeParent.removeChild(whitespaceOrPrevNode)
                 }
             }
         } else if (prevNode.elementType !in keywordsWithSpaceAfter) {
+            // If it is lambda, then we don't force it to be on newline or same line
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/WhiteSpaceRule.kt:212]: This  comment should be in the previous block

**Review by petertrr — APPROVED** [review]
