### PR TITLE
DataClassesRule shouldn't trigger when no property in constructor

### LINKED ISSUE #666: DataClassesRule when class has non-properties in the constructor
## Describe the bug
```kotlin
class Example(map: Map) {
   val field = map.getOrDefault...
    val secondFiled = map.get ...
}
```
can be *theoretically* converted to data class by moving proporties to the primary constructor and creating a secondary one with `map` parameter which delegates to the primary, like this:
```kotlin
data class Example (val field: Type, val secondField: Type) {
    constructor(map: Map) : this (map.get(...), map.get(...))
}
```
But it creates more code and also leads to creating several constructors (primary constructor of `data class` can't be made `private` because it is exposed via `copy` method).

Should it be considered a case for triggering of `DataClassRule`?

## Environment information
* diktat version: 0.1.7

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
   * [x] Fixed bug
   * [x] Added test
closes #666

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt [hunk 1]
```diff
@@ -61,6 +63,9 @@ class DataClassesRule(private val configRule: List<RulesConfig>) : Rule("data-cl
 
     @Suppress("UnsafeCallOnNullableType", "FUNCTION_BOOLEAN_PREFIX")
     private fun ASTNode.canBeDataClass(): Boolean {
+        if (findChildByType(PRIMARY_CONSTRUCTOR)?.let { constructor -> (constructor.psi as KtPrimaryConstructor).valueParameters.none { it.hasValOrVar() } } == true) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt:66]: We should also check if there is at least one property, either in the primary constructor or in the class body. We are not checking it currently, but class without properties can't be a data class.

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt [hunk 2]
```diff
@@ -63,9 +64,14 @@ class DataClassesRule(private val configRule: List<RulesConfig>) : Rule("data-cl
 
     @Suppress("UnsafeCallOnNullableType", "FUNCTION_BOOLEAN_PREFIX")
     private fun ASTNode.canBeDataClass(): Boolean {
-        if (findChildByType(PRIMARY_CONSTRUCTOR)?.let { constructor -> (constructor.psi as KtPrimaryConstructor).valueParameters.none { it.hasValOrVar() } } == true) {
+        val isNotPropertyInClassBody = findChildByType(CLASS_BODY)?.let { (it.psi as KtClassBody).properties.isEmpty() } ?: true
+        val isNotPropertyInConstructor = findChildByType(PRIMARY_CONSTRUCTOR)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt:68]:
```suggestion
        val hasPropertyInConstructor = findChildByType(PRIMARY_CONSTRUCTOR)
```
Very confusing name, this variable is true if there are only properties in constructor, right?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt (hunk 2 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/classes/DataClassesRule.kt:68]: Yes

**Review by petertrr — APPROVED** [review]
