### PR TITLE
Bugfix. CommentedCode when text inside block comment may be interpreted as KDoc

### LINKED ISSUE #652: [FP] CommentedCode when text inside block comment may be interpreted as KDoc
## Describe the bug
```
/*
 * some text here
maybe even with another line
 */
```
causes
`[COMMENTED_OUT_CODE] you should not comment out code, use VCS to save it in history and delete this block: /* (cannot be auto-corrected)`

## Environment information
* diktat version: 0.1.7

### PR DESCRIPTION
**Pull request by aktsay6**
### What's done:
  * Fixed bug
  * Added tests

The bug was in the way block comments opening and closing tokens were removed

This pull request closes #652

### CODE REVIEW

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt [hunk 1]
```diff
@@ -256,4 +256,42 @@ class CommentedCodeTest : LintTestBase(::CommentsRule) {
...
+
+
+    @Test
+    @Tag(WarningNames.COMMENTED_OUT_CODE)
+    fun `should not trigger on multiline comments #1`() {
+        lintMethod(
+                """
+            |/*
+            |
+            |   Copyright 2018-2020 Charles Korn.
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:268]:
```suggestion
            |   Copyright 2018-2020 John Doe.
```
Let's not use real people's names here :)

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt [hunk 2]
```diff
@@ -256,4 +256,42 @@ class CommentedCodeTest : LintTestBase(::CommentsRule) {
...
             LintError(1, 1, ruleId, "${COMMENTED_OUT_CODE.warnText()} public fun someFunc(name: String): Boolean =", false))
     }
+
+
+    @Test
+    @Tag(WarningNames.COMMENTED_OUT_CODE)
+    fun `should not trigger on multiline comments #1`() {
+        lintMethod(
+                """
+            |/*
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:266]:
```suggestion
            |   /*
```
Wasn't the bug in case leading or trailing spaces are present? Or did it trigger on simple comments too?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt (hunk 1 above)
Comment (aktsay6) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt]: Fixed

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt (hunk 2 above)
Comment (aktsay6) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:266]: It didn't trigger on simple comment, neither it triggers if we add spaces in this test. When I was testing with fix tests and different yml, I found out that it adds leading spaces to `BLOCK_COMMENT`.

Comment (petertrr) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:266]: You should reproduce it in auto tests too, in smoke test, if I understand correctly. There is currently an option to disable rules by editing config in smoke test, you can enhance it to allow custom configuration of rules.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt [hunk 3]
```diff
@@ -44,14 +44,18 @@ class DiktatSmokeTest : FixTestBase("test/smoke/src/main/kotlin",
...
             .toMutableList()
             .also { rulesConfig ->
                 rulesToDisable.forEach { warning ->
                     rulesConfig.removeIf { it.name == warning.name }
                     rulesConfig.add(RulesConfig(warning.name, enabled = false, configuration = emptyMap()))
                 }
+                rulesToOverride?.forEach { map ->
+                    rulesConfig.removeIf { it.name == map.key }
+                    rulesConfig.add(RulesConfig(map.key, enabled = true, configuration = map.value))
+                }
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt:58]:
```suggestion
    private fun overrideRulesConfig(rulesToDisable: List<Warnings>, rulesToOverride: Map<String, Map<String, String>> = emptyMap()) {
        val rulesConfig = RulesConfigReader(javaClass.classLoader).readResource(configFilePath)!!
            .toMutableList()
            .also { rulesConfig ->
                rulesToDisable.forEach { warning ->
                    rulesConfig.removeIf { it.name == warning.name }
                    rulesConfig.add(RulesConfig(warning.name, enabled = false, configuration = emptyMap()))
                }
                rulesToOverride?.forEach { (name, configuration) ->
                    rulesConfig.removeIf { it.name == map.key }
                    rulesConfig.add(RulesConfig(name, enabled = true, configuration = configuration))
                }
```

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt [hunk 4]
```diff
@@ -84,10 +88,35 @@ class DiktatSmokeTest : FixTestBase("test/smoke/src/main/kotlin",
...
+                                    |   
+                                    |       http://www.apache.org/licenses/LICENSE-2.0
+                                """.trimMargin())
+                        )
+                        )
+                )
+        )
+        fixAndCompare("Example5Expected.kt", "Example5Test.kt")
+
+        if (unfixedLintErrors.contains(LintError(line=1, col=1, ruleId="diktat-ruleset:comments", detail="${Warnings.COMMENTED_OUT_CODE.warnText()} /*"))) {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt:115]: `Assertions.assertFalse`?

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt [hunk 5]
```diff
@@ -84,10 +88,35 @@ class DiktatSmokeTest : FixTestBase("test/smoke/src/main/kotlin",
...
+            Warnings.PACKAGE_NAME_INCORRECT_PREFIX), null)
         fixAndCompare("DefaultPackageExpected.kt", "DefaultPackageTest.kt")
     }
 
+    @Test
+    @Tag("DiktatRuleSetProvider")
+    fun `smoke test #5`() {
+        overrideRulesConfig(emptyList(),
+                mapOf(
+                        Pair(Warnings.HEADER_MISSING_OR_WRONG_COPYRIGHT.name, mapOf(
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/smoke/DiktatSmokeTest.kt:100]: Why not use `to` instead of explicitly calling `Pair` constructor? I think it's convention for maps creation.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt (hunk 2 above)
Comment (aktsay6) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/comments/CommentedCodeTest.kt:266]: Done

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example5Expected.kt [hunk 6]
```diff
@@ -0,0 +1,15 @@
+                         /*
```
Comment (petertrr) [inline diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example5Expected.kt:1]: Why are we still doing this awful fix with lots of leading spaces?

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example5Expected.kt [hunk 7]
```diff
@@ -0,0 +1,15 @@
...
+                          * Copyright 2018-2020 John Doe.
```
Comment (petertrr) [inline diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example5Expected.kt:2]: I thought you removed insertion of this leading asterisk?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example5Expected.kt (hunk 6 above)
Comment (petertrr) [reply diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example5Expected.kt:1]: nvm, it's in #661

File: diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example5Expected.kt (hunk 7 above)
Comment (petertrr) [reply diktat-rules/src/test/resources/test/smoke/src/main/kotlin/Example5Expected.kt:2]: nvm, I've mistaken it for #661

**Review by petertrr — APPROVED** [review]
