### PR TITLE
Recommendation 3.7 parts 5 and 6

### LINKED ISSUE #151: Recommendation 3.7: Usage of whitespace for code separation
1. Any keywords (like 'if', 'when', 'for', e.t.c) should be separated with a single whitespace from the opening parenthesis.
     Only exceptions are: 'super' and 'constructor' keywords. They should not be separated from a parenthesis.

  2. Separate any keywords (such as `else` or `catch`, etc.) from the opening brace ('{') with a single whitespace.
  
  3. Use single whitespace before any opening brace (`{`).
     Only exception is passing a lambda as an argument inside parenthesis:
     ```kotlin
         private fun foo(a: (Int) -> Int, b: Int) {}
         foo({x: Int -> x}, 5) // no space before '{'
     ```

  4. Single whitespace should be placed on both sides of binary operators. This also applies to operator-like symbols, for example: 

     - Colon in generic structures with 'where' keyword： `where T : Type`
     - Arrow in lambdas： `(str: String) -> str.length()`

  **Exceptions：**

  - Two colons (`::`) are written without spaces: `Object::toString`
  - Dot separator (`.`) that stays on the same line with an object name: `object.toString()`

  5. Spaces should be used after ',',':',';' (except cases when those symbols are in the end of line). There should be no whitespaces in the end of line.

  6. There should be *only one space* between identifier and it's type： `list: List<String>`
  
  7. When using '[]' operator (get/set) there should be *no* spaces between identifier and '[': `someList[0]`
  
  8. There should be no space between a method name and a parenthesis: `foo() {}`

### PR DESCRIPTION
**Pull request by petertrr**
## Which rule and warnings did you add?

This pull request closes #151 (parts 5 and 6)

## What's done:
* [x] Implemented Rule, added Warnings
* [x] Added tests on checks
* [x] Added tests on fixers
* POM cleanup

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt [hunk 1]
```diff
@@ -20,30 +22,45 @@ import com.pinterest.ktlint.core.ast.ElementType.INIT_KEYWORD
...
 import org.jetbrains.kotlin.psi.psiUtil.parents
+import org.jetbrains.kotlin.psi.psiUtil.parentsWithSelf
 
 /**
  * This rule checks usage of whitespaces for horizontal code separation
  * 1. There should be single space between keyword and (, unless keyword is `constructor`
  * 2. There should be single space between keyword and {
+ * 3. There should be single space before any {, unless lambda inside parentheses of argument list
+ * 4. Binary operators should be surrounded by whitespaces, excluding :: and .
+ * 5. Spaces should be used after ',',':',';' (except cases when those symbols are in the end of line).
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:61]: ',',':',';' - could you please put spaces here - it is not readable

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt [hunk 2]
```diff
@@ -143,40 +164,74 @@ class WhiteSpaceRule : Rule("horizontal-whitespace") {
...
-            treePrev.removeIfWhiteSpace()
-            // for `!!` and possibly other postfix expressions treeNext can be null
-            (treeNext ?: treeParent.treeNext).removeIfWhiteSpace()
+    private fun handleEolWhiteSpace(node: ASTNode) {
+        val hasSpaces = node.text.substringBefore('\n').contains(' ')
+        // the second condition corresponds to the last line of file
+        val isEol = node.textContains('\n') || node.psi.parentsWithSelf.all { it.nextSibling == null }
+        if (hasSpaces && isEol) {
+            WRONG_WHITESPACE.warnAndFix(configRules, emitWarn, isFixMode, "there should be no spaces in the end of line", node.startOffset) {
+                (node as LeafElement).replaceWithText(node.text.trimStart(' '))
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:215]: I thought you are fixing spaces in the end of line

**Review by akuleshov7 — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt [hunk 3]
```diff
@@ -143,40 +164,74 @@ class WhiteSpaceRule : Rule("horizontal-whitespace") {
...
         }
+    }
 
+    private fun handleBinaryOperator(node: ASTNode) {
         val operatorNode = if (node.elementType == OPERATION_REFERENCE) node.firstChildNode else node
 
         if (node.elementType == OPERATION_REFERENCE && node.treeParent.elementType.let { it == BINARY_EXPRESSION || it == POSTFIX_EXPRESSION } ||
                 node.elementType != OPERATION_REFERENCE) {
-            checkAndFixBinaryOperator(node, operatorNode)
+            val requiredNumSpaces = if (operatorNode.elementType in operatorsWithNoWhitespace) 0 else 1
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:181]: basically such logic better to move to a separate methods

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt (hunk 2 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:215]: That's because `WHITE_SPACE` node on EOL can have newline in it. Therefore I only trim spaces at the beginning of `WHITE_SPACE` node's text.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt [hunk 4]
```diff
@@ -143,40 +164,74 @@ class WhiteSpaceRule : Rule("horizontal-whitespace") {
...
-    private fun checkAndFixBinaryOperator(node: ASTNode, operatorNode: ASTNode) {
+    private fun handleToken(node: ASTNode, requiredSpacesBefore: Int?, requiredSpacesAfter: Int?) {
+        require(requiredSpacesBefore != null || requiredSpacesAfter != null)
         val spacesBefore = node.treePrev.numWhiteSpaces()
-        val spacesAfter = (node.treeNext ?: node.treeParent.treeNext)  // for `!!` and possibly other postfix expressions treeNext can be null
-                .numWhiteSpaces()
-        val requiredNumSpaces = if (operatorNode.elementType in operatorsWithNoWhitespace) 0 else 1
-        if (spacesBefore != null && spacesBefore != requiredNumSpaces || spacesAfter != null && spacesAfter != requiredNumSpaces) {
-            val freeText = "${node.text} should ${if (requiredNumSpaces == 0) "not " else ""}be surrounded by whitespaces"
+        val spacesAfter = if (requiredSpacesAfter != null) {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:189]: Think more functional: 
`if ( != null) {} else null`
can be replaced by
```
requiredSpacesAfter?.map 
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt [hunk 5]
```diff
@@ -200,4 +255,12 @@ class WhiteSpaceRule : Rule("horizontal-whitespace") {
 
     private fun ASTNode.removeIfWhiteSpace() = takeIf { it.elementType == WHITE_SPACE && !it.textContains('\n') }
             ?.let { it.treeParent.removeChild(it) }
+
+    private fun getDescription(shouldBefore: Boolean,
+                               shouldAfter: Boolean,
+                               before: Int?,
+                               after: Int?): String =
+            (if (shouldBefore) " $before space(s) before" else "") +
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:263]: please, I am begging you - make it more readable and less compact here:
if (should && should) {
} else if (should) {
} else if (should) {

**Review by akuleshov7 — APPROVED** [review]
lgtm

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt (hunk 4 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:189]: Yes, will change.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt (hunk 3 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:181]: As discussed, this logic is used only here, so will keep.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt (hunk 5 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/WhiteSpaceRule.kt:263]: OK, will fix.
