### PR TITLE
Diktat should avoid fixing/raising a warning an issue for override constructor arguments

### LINKED ISSUE #833: Diktat should avoid fixing/raising a warning an issue for overriden contructor arguments
We should not suggest a `@param` Kdoc for the following code:

```
public class Ktoml(
    override val serializersModule: SerializersModule = EmptySerializersModule
)
```

### PR DESCRIPTION
**Pull request by Cheshiriks**
### What's done:
* added check for override constructor arguments
Closes #833

### CODE REVIEW

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocCommentsWarnTest.kt [hunk 1]
```diff
@@ -268,6 +268,19 @@ class KdocCommentsWarnTest : LintTestBase(::KdocComments) {
...
     }
 
+    @Test
+    @Tag(WarningNames.KDOC_NO_CONSTRUCTOR_PROPERTY)
+    fun `shouldn't trigger on override parameter`() {
+        lintMethod(
+            """
+                    |@Suppress("MISSING_KDOC_TOP_LEVEL")
+                    |public class Example (
+                    |   override val serializersModule: SerializersModule = EmptySerializersModule
```
Comment (akuleshov7) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocCommentsWarnTest.kt:278]: do we have a positive scenario? where we trigger an error?

**Review by akuleshov7 — APPROVED** [review]
Please answer one small question and feel free to merge

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocCommentsWarnTest.kt (hunk 1 above)
Comment (Cheshiriks) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/KdocCommentsWarnTest.kt:278]: Yes. In the test "no property kdoc and class"
