### PR TITLE
Correct order in ClassLikeStructursOrderRule

### LINKED ISSUE #482: Messy reordering by DiktatRuleSet
## Describe the bug
```kotlin
class Example {
companion object {
        private val keywordsWithSpaceAfter = TokenSet.create(
                // these keywords are followed by {
                ELSE_KEYWORD, TRY_KEYWORD, DO_KEYWORD, FINALLY_KEYWORD, INIT_KEYWORD,
                // these keywords are followed by (
                FOR_KEYWORD, IF_KEYWORD, WHILE_KEYWORD, CATCH_KEYWORD,
                // these keywords can be followed by either { or (
                WHEN_KEYWORD
        )

        val operatorsWithNoWhitespace = TokenSet.create(DOT, RANGE, COLONCOLON, SAFE_ACCESS, EXCLEXCL)

        // this is the number of parent nodes needed to check if this node is lambda from argument list
        private const val numParentsForLambda = 3
    }
}
```
is autocorrected into
```kotlin
class Example {
    companion object {
        val operatorsWithNoWhitespace = TokenSet.create(DOT, RANGE, COLONCOLON, SAFE_ACCESS, EXCLEXCL)// this is the number of parent nodes needed to check if this node is lambda
        // from argument list
        private const val NUM_PARENTS_FOR_LAMBDA = 3
        private val keywordsWithSpaceAfter = TokenSet.create(
                // these keywords are followed by {
                ELSE_KEYWORD, TRY_KEYWORD, DO_KEYWORD, FINALLY_KEYWORD, INIT_KEYWORD,
                // these keywords are followed by (
                FOR_KEYWORD, IF_KEYWORD, WHILE_KEYWORD, CATCH_KEYWORD,
                // these keywords can be followed by either { or (
                WHEN_KEYWORD
        )

        
    }
}
```
and it has a whole lot of problems:
- comment is getting split and it's parts are shuffled
- blank lines are left
- comments are incorrectly formatted after move

## Environment information
* diktat version: 0.1.3

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
   Fixed bug and added tests
   Closes #482

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ClassLikeStructuresOrderRule.kt [hunk 1]
```diff
@@ -89,27 +89,42 @@ class ClassLikeStructuresOrderRule(private val configRules: List<RulesConfig>) :
...
+                val prevNodes = astNode.siblings(false).takeWhile { it.elementType == WHITE_SPACE || it.isPartOfComment()}.toList()
+                when (prevNodes.size) {
+                    0 -> BodyChild(astNode, null, null, null)
+                    1 -> BodyChild(astNode, prevNodes[0], null, null)
+                    2 -> BodyChild(astNode, prevNodes[0], prevNodes[1], null)
+                    else -> BodyChild(astNode, prevNodes[2], prevNodes[1], prevNodes[0])
+                }
+            }
+
+        val classChild = node.children().filter { it.elementType in classChildren }.toList()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ClassLikeStructuresOrderRule.kt:107]:
```suggestion
        val classChildren = node.children().filter { it.elementType in childrenTypes }.toList()
```

**Review by petertrr — CHANGES_REQUESTED** [review]

**Comment by petertrr** [comment]
If you are keeping order of elements after reordering, will it fix #573 too?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ClassLikeStructuresOrderRule.kt [hunk 2]
```diff
@@ -88,28 +88,35 @@ class ClassLikeStructuresOrderRule(private val configRules: List<RulesConfig>) :
...
-                    replacement.oldNodes.forEachIndexed { idx, oldNode ->
+            .map { astNode ->
+                listOf(astNode) + astNode.siblings(false).takeWhile { it.elementType == WHITE_SPACE || it.isPartOfComment()}.toList()
+            }
+
+        val classChildren = node.children().filter { it.elementType in childrenTypes }.toList()
+        if (classChildren != blocks.map { it.first() }) {
+            blocks.forEachIndexed { index, listOfChildren ->
+                val astNode = listOfChildren.first()
+                if (astNode != classChildren[index]) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/ClassLikeStructuresOrderRule.kt:105]: You could have this predicate in `filterIndexed` before `forEach` to avoid additional block depth level.

**Review by petertrr — CHANGES_REQUESTED** [review]
LGTM, but a couple of suggestions

**Review by petertrr — APPROVED** [review]
