### PR TITLE
Fix of #122 - warn about missing KDoc on method even if it cannot be autosuggested

### LINKED ISSUE #122: Warning MISSING_KDOC_ON_FUNCTION is not emitted if KDoc cannot be auto suggested

### PR DESCRIPTION
**Pull request by petertrr**
This closes #122 

### What's done:
* Changed logic
* Added tests

### CODE REVIEW

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt [hunk 1]
```diff
@@ -36,7 +36,8 @@ fun lintMethod(rule: Rule,
                     it.assertThat(actual.col).`as`("Column").isEqualTo(expected.col)
                     it.assertThat(actual.ruleId).`as`("Rule id").isEqualTo(expected.ruleId)
                     it.assertThat(actual.detail).`as`("Detailed message").isEqualTo(expected.detail)
-                    // fixme: in ktlint canBeAutoCorrected is not included in equals/hashCode for `backward compatibility`
+                    // fixme: fix all tests and uncomment
+//                    it.assertThat(actual.canBeAutoCorrected).`as`("Can be autocorrected").isEqualTo(expected.canBeAutoCorrected)
```
Comment (akuleshov7) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt:40]: commenting code :D 
Our main feature

Comment (petertrr) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/util/TestUtils.kt:40]: Right... Then we'll need to fix it asap ))
