### PR TITLE
False-positive activation of 1TBS rule

### LINKED ISSUE #215: False-positive activation of 1TBS rule
For example, for this code:
```kotlin
fun List<RulesConfig>.getRuleConfig(rule: Rule): RulesConfig? {
    return this.find { it.name == rule.ruleName() }
}
```
rule gives the following error:
```
[INFO]    [ktlint] C:\...\diktat-common\src\main\kotlin\org\cqfn\diktat\common\config\rules\RulesConfigReader.kt:61:51: [BRACES_BLOCK_STRUCTURE_ERROR] braces should follow 1TBS style: no newline before closing brace
```

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
  Added check for lambdas
  closes #215

### CODE REVIEW

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesWarnTest.kt [hunk 1]
```diff
@@ -469,9 +470,27 @@ class BlockStructureBracesWarnTest {
                     |   }
                     |}
                 """.trimMargin(),
-                LintError(4, 11, ruleId, "${BRACES_BLOCK_STRUCTURE_ERROR.warnText()} incorrect newline before opening brace", true),
-                LintError(5, 40, ruleId, "${BRACES_BLOCK_STRUCTURE_ERROR.warnText()} no newline before closing brace", true),
-                LintError(6, 35, ruleId, "${BRACES_BLOCK_STRUCTURE_ERROR.warnText()} no newline before closing brace", true)
+                LintError(4, 11, ruleId, "${BRACES_BLOCK_STRUCTURE_ERROR.warnText()} incorrect newline before opening brace", true)
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesWarnTest.kt:473]: Why is there an error in `foo(){`?

Comment (kentr0w) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesWarnTest.kt:473]: Because there should be space before open brace. There is incorrect warn message.

Comment (petertrr) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/BlockStructureBracesWarnTest.kt:473]: And space should be handled in `WhiteSpaceRule`, I suppose. If your rule already checks it, please change warn message, or if it doesn't, please check only `WHITE_SPACE` nodes.

**Review by petertrr — APPROVED** [review]
