### PR TITLE
Bugfix.Problems with year checking logic in copyright(#688)

### LINKED ISSUE #688: Problems with year checking logic in copyright
As referenced in #687:

there are some incorrect fixing cases:
* Additional blank line is inserted after rearranging comments
* Sometimes, when year is still not changed, there is an NPE somewhere in year checking logic.

Overall, it seems there are some cases that need to be fixed and covered with tests in year checking logic.

The changes from PR #687 can be reverted and tests executed to see exceptions and inconsistencies.

### PR DESCRIPTION
**Pull request by aktsay6**
### What's done:
  * Fixed NPE
  * Added tests

This pull request closes #688

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt [hunk 1]
```diff
@@ -185,7 +185,7 @@ class HeaderCommentRule(private val configRules: List<RulesConfig>) : Rule("head
 
         if (copyrightWithCorrectYear.isNotEmpty()) {
             WRONG_COPYRIGHT_YEAR.warnAndFix(configRules, emitWarn, isFixMode, "year should be $curYear", node.startOffset, node) {
-                (headerComment as LeafElement).replaceWithText(headerComment.text.replace(copyrightText, copyrightWithCorrectYear))
+                (headerComment as? LeafElement)?.replaceWithText(headerComment.text.replace(copyrightText, copyrightWithCorrectYear))
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt:188]: Why was the exception happening?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt [hunk 2]
```diff
@@ -58,6 +59,8 @@ private fun generateWarningNames() {
 
 private fun validateYear() {
     val file = File("diktat-rules/src/test/resources/test/paragraph2/header/CopyrightDifferentYearExpected.kt")
+    log.info("===================================")
+    println(file)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt:63]: ?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt [hunk 3]
```diff
@@ -58,6 +59,8 @@ private fun generateWarningNames() {
 
 private fun validateYear() {
     val file = File("diktat-rules/src/test/resources/test/paragraph2/header/CopyrightDifferentYearExpected.kt")
+    log.info("===================================")
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt:62]: What about other files? We could check an entire directory `paragraph2/header`, I think.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleFixTest.kt [hunk 4]
```diff
@@ -71,6 +71,17 @@ class HeaderCommentRuleFixTest : FixTestBase(
         )
     }
 
+    @Test
+    @Tag(WRONG_COPYRIGHT_YEAR)
+    fun `should not raise npe`() {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleFixTest.kt:76]: NPE occured when there was a file with copyright and year 2020 (like `2019-2020`) and it should have been fixed to `2019-2021`, but there was an NPE instead. You are checking a different case.

**Review by petertrr — CHANGES_REQUESTED** [review]
You can use [this CI build](https://github.com/cqfn/diKTat/runs/1652469974) as a reference for the errors that have occured. You are now not covering all of them.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt (hunk 1 above)
Comment (aktsay6) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt:188]: Because there can be no copyright in file

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt:188]: Then why didn't it appear before? Errors started to occur only when the year has changed, all tests have successfully passed with current year being 2020.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleFixTest.kt (hunk 4 above)
Comment (aktsay6) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleFixTest.kt:76]: In logs that you provided I saw NPE occurring on this case. I guess the problem is that we are checking only one file. As you said, we should check copyright in each file (`paragraph2/header`)

Comment (petertrr) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter2/HeaderCommentRuleFixTest.kt:76]: We had `2020-2020` set in config for copyright text and I expected just to see failing tests: expected `2020-2021` and actual `2020-2020`. But there are NPEs all of a sudden. I guess that indicates some flaws in logic of checks.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt (hunk 2 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt]: ??

File: diktat-analysis.yml [hunk 5]
```diff
@@ -277,6 +277,9 @@
 # Checks year in the copyright
 - name: WRONG_COPYRIGHT_YEAR
   enabled: true
+# Checks copyrights year in configuration
+- name: WRONG_COPYRIGHT_YEAR_CONFIGURATION
```
Comment (petertrr) [inline diktat-analysis.yml:281]: I still think it's not a very good idea to mix config validation with code style warnings. This ensures that the issue gets user's attention, yes, but OTOH you can disable config validation from the config itself and you have one more thing to keep in mind. Let's log a warning in this case, we already have logic that checks copyright year and it will emit a separate warning disregarding value from config.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/comments/HeaderCommentRule.kt:198]: I still don't get why it's nullable. Is this fix actually being executed somewhere?

**Review by petertrr — CHANGES_REQUESTED** [review]
You have added an empt file instead of `gradlew`. Please either add gradlew and `gradle-wrapper-*` files or remove gradlew.bat if it was by accident.

File: info/gradlew.bat [hunk 6]
```diff
@@ -0,0 +1,104 @@
+@rem
```
Comment (petertrr) [inline info/gradlew.bat:1]: Please address my previous comment about gradle wrapper scripts.

**Review by petertrr — CHANGES_REQUESTED** [review]
mostly lgtm, two more questions

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt [hunk 7]
```diff
@@ -58,27 +57,28 @@ private fun generateWarningNames() {
...
-                afterCopyrightRegex.matches(line) -> afterCopyrightRegex.replace(line) {
-                    val copyrightYears = it.value.split("(c)", "(C)", "©")
-                    val validYears = "${copyrightYears[0]}-$curYear"
-                    line.replace(afterCopyrightRegex, validYears)
-                }
-                else -> line
-            })
+    val files = File("diktat-rules/src/test/resources/test/paragraph2/header")
+    files.listFiles().forEach { file ->
+        if (file.name.contains("CopyrightDifferentYearTest.kt")) {
```
[the remark this answers is not in the document]
Comment (aktsay6) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt:62]: It is hardcoded, because test, which uses this file, is checking if year is corrected right

File: info/gradlew.bat (hunk 6 above)
Comment (aktsay6) [reply info/gradlew.bat:1]: Yeah, it was a mistake adding this file

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt:62]: I mean, if you want to exclude one file from the loop, you could do `filterNot` before `forEach`. Now, with `return@forEach`, it looks kinda like it relies on elements order and will not check files that can be after `CopyrightDifferentYearTest`.

File: info/gradlew.bat (hunk 6 above)
Comment (aktsay6) [reply info/gradlew.bat]: Fixed

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (aktsay6) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/generation/Generation.kt]: Yeah, that seems better. Fixed

**Review by petertrr — APPROVED** [review]
