### PR TITLE
function style bug in NewlinesRule

### LINKED ISSUE #492: Enhancments for functional style in NewlinesRule
It actually even isn't compliant with our current code style: we are forcing a line break after `it`, but I thought it looks too ugly. I'll add an issue about making this rule prettier and maybe taking into account text length.

_Originally posted by @petertrr in https://github.com/cqfn/diKTat/pull/485#discussion_r517192102_

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
    Fixed bugs and added tests
closes #492

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 1]
```diff
@@ -98,13 +100,15 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
     companion object {
         // fixme: these token sets can be not full, need to add new once as corresponding cases are discovered.
         // error is raised if these operators are prepended by newline
-        private val lineBreakAfterOperators = TokenSet.create(ANDAND, OROR, PLUS, PLUSEQ, MINUS, MINUSEQ, MUL, MULTEQ, DIV, DIVEQ)
+        private val lineBreakAfterOperators = TokenSet.create(ANDAND, OROR, PLUS, PLUSEQ, MINUS, MINUSEQ, MUL, MULTEQ, DIV, DIVEQ, ELVIS)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:103]: Why is elvis here?

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 2]
```diff
@@ -224,15 +225,16 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
...
         lintMethod(
                 """
                     |fun foo(bar: Bar?) {
                     |    bar.baz()
                     |    bar?.baz()
                     |    bar!!.baz()
                     |}
-                """.trimMargin()
+                """.trimMargin(),
+                LintError(4,10,ruleId, "$functionalStyleWarn .", true)
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:237]: I think we only check cases with more than two calls?

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 3]
```diff
@@ -243,14 +245,14 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
                 """
                     |fun foo(list: List<Bar>?) {
                     |    list!!.filterNotNull()
-                    |        .map { it.baz() }.firstOrNull {
+                    |        .map { it.baz() }
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:248]: Why?

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 4]
```diff
@@ -437,7 +439,8 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
                     |fun qux(list: List<Int>): Int {
                     |    list.filter {
                     |        return@filter condition(it)
-                    |    }.forEach {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:440]: Why? Also, it's strange that there hasn't been any warning on this.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 5]
```diff
@@ -548,7 +551,7 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
 
     @Test
     @Tag(WarningNames.WRONG_NEWLINES)
-    fun `should trigger on non-multiline lambdas`() {
+    fun `shouldn't trigger on non-multiline lambdas`() {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:554]: Why did you remove it?

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 6]
```diff
@@ -647,8 +647,154 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
...
+            """.trimMargin(),
+                LintError(4, 10, ruleId, "$functionalStyleWarn .", true),
+                LintError(9, 10, ruleId, "$functionalStyleWarn .", true),
+                LintError(9, 16, ruleId, "$functionalStyleWarn .", true)
+        )
+    }
+
+    @Test
+    @Tag(WarningNames.WRONG_NEWLINES)
+    fun `should warn dot qualified with save access`() {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:712]:
```suggestion
    fun `should warn dot qualified with safe access`() {
```

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 7]
```diff
@@ -647,8 +647,154 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
...
+                LintError(2, 7, ruleId, "$functionalStyleWarn .", true),
+                LintError(16, 10, ruleId, "$functionalStyleWarn .", true),
+                LintError(21, 7, ruleId, "$functionalStyleWarn .", true),
+                LintError(22, 10, ruleId, "$functionalStyleWarn .", true)
+        )
+    }
+
+    @Test
+    @Tag(WarningNames.WRONG_NEWLINES)
+    fun `should warn dot qualifided with exclexcl`() {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:782]: test name?

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 8]
```diff
@@ -647,8 +647,154 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
...
+                |       ?:
+                |        goo()
+                |      
+                |   x.goo()
+                |       ?:goo()
+                |       
+                |   y.ds()?:gh()
+                |}
+            """.trimMargin(),
+                LintError(4,8, ruleId, "${WRONG_NEWLINES.warnText()} shouldn't be a new line after ?:", true)
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:797]: We probably need more complex logic on `?:`, like described [in the issue](https://github.com/cqfn/diKTat/issues/554#issuecomment-734722405).  I think it can be done later in a separate PR.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 9]
```diff
@@ -149,16 +153,26 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
+            if (node.isFollowedByNewline()){
+                WRONG_NEWLINES.warnAndFix(configRules, emitWarn, isFixMode,
+                        "shouldn't be a new line after ${node.text}", node.startOffset, node) {
+                    val spaceAfter = node.parent({it.treeNext != null}, strict = false)?.treeNext
+                    val parentSpace = spaceAfter?.treeParent
+                    parentSpace?.removeChild(spaceAfter)
+                }
+            }
+        } else  {
+            if (node.prevCodeSibling()?.isFollowedByNewline() == true) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:168]: `else if` instead of `else { if }`?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt (hunk 5 above)
Comment (kentr0w) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:554]: Because in this case there are no mistakes.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt (hunk 8 above)
Comment (kentr0w) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:797]: Yes, we have another issue for this case

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt (hunk 1 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:103]: Because handle for elvis is `handleOperatorWithLineBreakAfter`

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt (hunk 2 above)
Comment (kentr0w) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:237]: Yes, but as we [discussed](https://github.com/cqfn/diKTat/issues/492#issuecomment-732816549) `!!`  - is equivalent to dot - need line break

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 10]
```diff
@@ -371,13 +372,15 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
-        .getIdentifierName()?.text
+            .getIdentifierName()?.text
 
     private fun ASTNode.getOrderedCallExpressions(psi: PsiElement, result: MutableList<ASTNode>) {
         // if statements here have the only right order - don't change it
 
         if (psi.children.isNotEmpty() && (psi.children[0].node.elementType != DOT_QUALIFIED_EXPRESSION
-                        && psi.children[0].node.elementType != SAFE_ACCESS_EXPRESSION )) {
+                        && psi.children[0].node.elementType != SAFE_ACCESS_EXPRESSION)) {
+                            if (psi.children[0].node.elementType == POSTFIX_EXPRESSION)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:382]:
```suggestion
                            if (psi.firstChild.node.elementType == POSTFIX_EXPRESSION)
```
to not use explicit index access

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 11]
```diff
@@ -413,11 +416,11 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
                     getOrderedCallExpressions(psi, it)
                 }
             }
+            ?.takeIf { it.first() != this }
             ?.dropWhile { !it.treeParent.textContains('(') && !it.treeParent.textContains('{') }
-            // fixme: we can't distinguish fully qualified names (like java.lang) from chain of property accesses (like list.size) for now
-            ?.filter { it.getParentExpressions().count() > 1 }
-            ?.count()
-            ?.let { it > 1 }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:420]: Do you still count number of statements, or will we always trigger? I think we still need to count the number of statements and issue a warning only when there are >2. No need to split very short statements.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 12]
```diff
@@ -413,11 +416,11 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
+            ?.drop(1)
+            ?.any { !it.treePrev.isWhiteSpaceWithNewline() }
+    // fixme: we can't distinguish fully qualified names (like java.lang) from chain of property accesses (like list.size) for now
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:423]: Please move this comment upper. It corresponds to the line where we take only method calls.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt (hunk 3 above)
Comment (petertrr) [reply diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:248]: I mean, there already was a warning for this line, why convert negative test to positive?

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 13]
```diff
@@ -574,18 +577,15 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
                     |         }
                     |}
                 """.trimMargin(),
-                LintError(2, 22, ruleId,"${WRONG_NEWLINES.warnText()} should follow functional style at .", true),
-                LintError(6, 22, ruleId,"${WRONG_NEWLINES.warnText()} should follow functional style at ?.", true),
-                LintError(10, 13, ruleId,"${WRONG_NEWLINES.warnText()} should follow functional style at .", true),
-                LintError(19, 20, ruleId,"${WRONG_NEWLINES.warnText()} should follow functional style at .", true)
+                LintError(19,20, ruleId, "$functionalStyleWarn .", true)
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:580]: Please change this test's name

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 14]
```diff
@@ -413,11 +417,12 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
                     getOrderedCallExpressions(psi, it)
                 }
             }
-            ?.dropWhile { !it.treeParent.textContains('(') && !it.treeParent.textContains('{') }
+            ?.takeIf { it.first() != this }
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:420]: We should have an option in configuration to set minimum number of calls to start putting newlines.

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/test/resources/test/paragraph3/newlines/FunctionalStyleExpected.kt [hunk 15]
```diff
@@ -12,3 +12,20 @@ fun foo(list: List<Bar>?) {
...
 fun bar(x :Int,y:Int) = x+ y
+
+fun goo() {
+    x.map()
+.gro()
+            .gh()
+    t.map()
+.hg()
+.hg()
+    t
```
Comment (petertrr) [inline diktat-rules/src/test/resources/test/paragraph3/newlines/FunctionalStyleExpected.kt:23]: Please also add more tests with `!!`. I get strange results with
```kotlin
foo
    .bar()
    .baz()
    .qux()!!
```

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 16]
```diff
@@ -812,4 +819,43 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
...
         )
     }
+
+    @Test
+    @Tag(WarningNames.WRONG_NEWLINES)
+    fun `test configuration for calls in one line`() {
+        lintMethod(
+                """
+                |fun foo() {
+                |   /*z.goo().foo().qwe()
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:829]: Why commented code?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 17]
```diff
@@ -417,14 +417,17 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
-            ?.takeIf { !(it.size == 2 && it.first().elementType == POSTFIX_EXPRESSION) }
+            ?.takeIf { it.first() != this && it.isNotValidCalls(this) }
             // fixme: we can't distinguish fully qualified names (like java.lang) from chain of property accesses (like list.size) for now
             ?.dropWhile { !it.treeParent.textContains('(') && !it.treeParent.textContains('{') }
             ?.drop(1)
             ?.any { !it.treePrev.isWhiteSpaceWithNewline() }
             ?: false
 
+    private fun MutableList<ASTNode>.isNotValidCalls(node: ASTNode) =
+            !(this.size == 2 && this.first().elementType == POSTFIX_EXPRESSION) && this.indexOf(node) >= configuration.maxCallsInOneLine
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:428]: Shouldn't it be index + 1?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 18]
```diff
@@ -647,8 +653,209 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
...
+    @Test
+    @Tag(WarningNames.WRONG_NEWLINES)
+    fun `more test for prefix`() {
+        lintMethod(
+                """
+                |fun foo() {
+                |   foo
+                |       .bar()
+                |       .goo()
+                |       .qwe()!!
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:850]: Please add the test where `!!` is used in the middle of the chain:
```kotlin
foo
    .bar()
    .baz()!!
    .qwe()
```
It shouldn't emit warnings, but currently emits a very strange one (`should break a line before and not after foo...`).

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 19]
```diff
@@ -371,20 +372,23 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
     private fun ASTNode.getOrderedCallExpressions(psi: PsiElement, result: MutableList<ASTNode>) {
         // if statements here have the only right order - don't change it
 
-        if (psi.children.isNotEmpty() && (psi.children[0].node.elementType != DOT_QUALIFIED_EXPRESSION
-                        && psi.children[0].node.elementType != SAFE_ACCESS_EXPRESSION )) {
-            result.add(psi.children[0].node.siblings(true)
+        if (psi.children.isNotEmpty() && (psi.firstChild.node.elementType != DOT_QUALIFIED_EXPRESSION
+                        && psi.firstChild.node.elementType != SAFE_ACCESS_EXPRESSION)) { 
+                            if (psi.firstChild.node.elementType == POSTFIX_EXPRESSION) {
+                                result.add(psi.firstChild.node)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:383]: Doesn't calling `result.add` twice in some cases lead to some sort of data duplication?

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt (hunk 19 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt]: No, because in the second case it takes another node.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 20]
```diff
@@ -371,20 +378,27 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
 
-        if (psi.children.isNotEmpty() && (psi.children[0].node.elementType != DOT_QUALIFIED_EXPRESSION
-                        && psi.children[0].node.elementType != SAFE_ACCESS_EXPRESSION )) {
-            result.add(psi.children[0].node.siblings(true)
+        if (psi.children.isNotEmpty() && (psi.firstChild.node.elementType != DOT_QUALIFIED_EXPRESSION
+                        && psi.firstChild.node.elementType != SAFE_ACCESS_EXPRESSION)) {
+                            val firstChild = psi.firstChild
+                            if (firstChild.node.elementType == POSTFIX_EXPRESSION) {
+                                if (firstChild.firstChild.node.elementType == DOT_QUALIFIED_EXPRESSION
+                                        || firstChild.firstChild.node.elementType == SAFE_ACCESS_EXPRESSION)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:391]: You can extract this comparison to a separate method, it already occurs two times (`psi.firstChild.node.elementType ...`)

**Review by petertrr — CHANGES_REQUESTED** [review]

**Review by petertrr — CHANGES_REQUESTED** [review]
Also I've found that this example:
```kotlin
val x = foo
    .bar!!
    .baz
```
causes NPE in NewlinesRule fixer. I.e., case when there are properties inside `POSTFIX_EXPRESSION` and not function calls. And the warning is incorrect too: it suggest to break line `before and not after foo...` which I think means it uses the whole `POSTFIX_EXPRESSION` node in a warning message. Does it have something to do with postfix being added to `lineBreakBeforeOperators`?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 21]
```diff
@@ -170,19 +171,25 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
...
-                val isSingleLineIfElse = parent({ it.elementType == IF }, true)?.isSingleLineIfElse() ?: false
-                // to follow functional style these operators should be started by newline
-                (isFollowedByNewline() || !isBeginByNewline()) && !isSingleLineIfElse
-                        && (!isFirstCall() || !isMultilineLambda(treeParent))
-            } else {
-                // unless statement is simple and on single line, these operators cannot have newline after
-                isFollowedByNewline() && !isSingleDotStatementOnSingleLine()
+        val isIncorrect = (if (node.elementType == ELVIS) node.treeParent else node).run {
+            when (isCallsChain()) {
+                null -> {
```
[the remark this answers is not in the document]
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:176]: But according to our code style the `when` should have an `else` block

**Review by petertrr — COMMENTED** [review]
Please also unsuppress all "WRONG_NEWLINES" warnings in your pull request. After the fix is done, diktat snapshot check should become green again.

**Review by petertrr — COMMENTED** [review]
We probably need `maxCallsInOneLine` set to 2 or 3 in our self check.

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt [hunk 22]
```diff
@@ -653,4 +662,228 @@ class NewlinesRuleWarnTest : LintTestBase(::NewlinesRule) {
...
+                |}
+            """.trimMargin(),
+            LintError(4, 22, ruleId, "$functionalStyleWarn .", true),
+            LintError(9, 22, ruleId, "$functionalStyleWarn .", true)
+        )
+    }
+
+    @Test
+    @Tag(WarningNames.WRONG_NEWLINES)
+    fun `should warn dot qualified with save access`() {
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/chapter3/files/NewlinesRuleWarnTest.kt:721]:
```suggestion
    fun `should warn dot qualified with safe access`() {
```

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 23]
```diff
@@ -407,33 +415,59 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
         .takeWhile { it.elementType in expressionTypes }
         .singleOrNull()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:416]: I see a problem with this method now: it should return true, if statement is a single dot qualified expression on one line, but you wanted it to return `true` for property accesses too, I assume. I think it'll make more sense to check if list of parents here has no more that 1 element and return `true` in this case and `false` otherwise.

**Review by petertrr — APPROVED** [review]
LGTM

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt [hunk 24]
```diff
@@ -413,9 +413,10 @@ class NewlinesRule(private val configRules: List<RulesConfig>) : Rule("newlines"
 
     private fun ASTNode.isSingleDotStatementOnSingleLine() = parents()
         .takeWhile { it.elementType in expressionTypes }
-        .singleOrNull()
+        .takeIf { it.toList().size == 1 }
+        ?.single()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/files/NewlinesRule.kt:417]: This is basically same as before. I thought we need to check number of lines for case when `size == 0` too? If not, you can just leave `singleOrNull` and `?: false` at the end.
