### PR TITLE
Added fix in AnnotationNewLineRule

### LINKED ISSUE #657: `ANNOTATION_NEW_LINE` doesn't trigger if the annotation doesn't start on a new line
```
package example; @Annotation

class A { }
```

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
    Fixed bug
closes #657

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 1]
```diff
@@ -169,6 +170,19 @@ fun ASTNode.isBeginByNewline() =
                     (it.treePrev.elementType == IMPORT_LIST && it.treePrev.isLeaf() && it.treePrev.treePrev.isLeaf())
         } ?: false
 
+/**
+ * Checks if there is a newline before this element or before comment before. See [isBeginByNewline] for motivation on parents check.
+ */
+fun ASTNode.isBeginNewLineWithComment() =
+        isBeginByNewline() ||
+                if (this.treePrev?.treePrev?.isPartOfComment() ?: false) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:178]: Maybe, something like `siblings(forward = false).takeWhile { !it.textContains('\n') }.all { it.isWhiteSpace() || it.isPartOfComment() }`? This will allow not to hard-code checking only `treePrev` or `teePrev.treePrev`.

**Review by petertrr — CHANGES_REQUESTED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt [hunk 2]
```diff
@@ -169,6 +170,14 @@ fun ASTNode.isBeginByNewline() =
                     (it.treePrev.elementType == IMPORT_LIST && it.treePrev.isLeaf() && it.treePrev.treePrev.isLeaf())
         } ?: false
 
+/**
+ * Checks if there is a newline before this element or before comment before. See [isBeginByNewline] for motivation on parents check.
+ */
+fun ASTNode.isBeginNewLineWithComment() =
+        isBeginByNewline() || siblings(forward = false).takeWhile { !it.textContains('\n') }.run {
+            all { it.isWhiteSpace() || it.isPartOfComment() } && !toList().isEmpty()
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/AstNodeUtils.kt:178]:
```suggestion
        isBeginByNewline() || siblings(forward = false).takeWhile { !it.textContains('\n') }.toList().run {
            all { it.isWhiteSpace() || it.isPartOfComment() } && isNotEmpty()
```

**Review by petertrr — APPROVED** [review]
