### PR TITLE
Bugfix. Unhandled ArrayStoreException when string template has [] operator inside

### LINKED ISSUE #406: Unhandled ArrayStoreException when string template has [] operator inside
```kotlin
private fun foo() {
    val bar = "${arr[0]}"
}
```
causes
```
Caused by: java.lang.ArrayStoreException: org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.LeafPsiElement
    at org.jetbrains.kotlin.com.intellij.extapi.psi.StubBasedPsiElementBase.getStubOrPsiChildren (StubBasedPsiElementBase.java:470)
    at org.jetbrains.kotlin.psi.KtStringTemplateExpression.getEntries (KtStringTemplateExpression.java:59)
    at org.cqfn.diktat.ruleset.utils.PsiUtilsKt.containsOnlyConstants (PsiUtils.kt:30)
    at org.cqfn.diktat.ruleset.rules.identifiers.LocalVariablesRule$collectLocalPropertiesWithUsages$1.invoke (LocalVariablesRule.kt:78)
    at org.cqfn.diktat.ruleset.rules.identifiers.LocalVariablesRule$collectLocalPropertiesWithUsages$1.invoke (LocalVariablesRule.kt:37)
    at org.cqfn.diktat.ruleset.utils.search.VariablesSearch.collectVariables (VariablesSearch.kt:117)
    at org.cqfn.diktat.ruleset.utils.search.VariablesWithUsagesSearchKt.findAllVariablesWithUsages (VariablesWithUsagesSearch.kt:31)
    at org.cqfn.diktat.ruleset.rules.identifiers.LocalVariablesRule.collectLocalPropertiesWithUsages (LocalVariablesRule.kt:75)
    at org.cqfn.diktat.ruleset.rules.identifiers.LocalVariablesRule.visit (LocalVariablesRule.kt:58)
    at com.pinterest.ktlint.core.KtLint$format$1.invoke (KtLint.kt:271)
    at com.pinterest.ktlint.core.KtLint$format$1.invoke (KtLint.kt:23)
    at com.pinterest.ktlint.core.KtLint$visitor$2$2.invoke (KtLint.kt:212)
    at com.pinterest.ktlint.core.KtLint$visitor$2$2.invoke (KtLint.kt:23)
    at com.pinterest.ktlint.core.ast.PackageKt.visit (package.kt:224)
    at com.pinterest.ktlint.core.KtLint$visitor$2.invoke (KtLint.kt:211)
    at com.pinterest.ktlint.core.KtLint$visitor$2.invoke (KtLint.kt:23)
    at com.pinterest.ktlint.core.KtLint.format (KtLint.kt:264)
```

### Environment info
* diktat version: 0.1.3-SNAPSHOT
* kotlin version: 1.4.10

### PR DESCRIPTION
**Pull request by aktsay6**
### What's done:
  * Fixed bugs

This pull request closes #406

### CODE REVIEW

**Review by akuleshov7 — APPROVED** [review]
lgtm

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/StringTemplateFormatRule.kt [hunk 1]
```diff
@@ -93,12 +94,21 @@ class StringTemplateFormatRule(private val configRules: List<RulesConfig>) : Rul
...
+                ?.treeParent
+                ?.elementType == ARRAY_ACCESS_EXPRESSION
+
+        return if (onlyOneRefExpr && !isArrayAccessExpression) {
+            (!(node.treeNext.text.first().isLetterOrDigit() // checking if first letter is valid
                     || node.treeNext.text.startsWith("_"))
-                    || node.treeNext.elementType == CLOSING_QUOTE
-        } else {
+                    || node.treeNext.elementType == CLOSING_QUOTE)
+        } else if(!isArrayAccessExpression) {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/StringTemplateFormatRule.kt:108]: you will need to check for more corner cases -  this can be not the only problem here

**Review by akuleshov7 — APPROVED** [review]
lgtm
