### PR TITLE
Validate warning names in config file on startup

### LINKED ISSUE #58: Validate diktat-analysis.yml before start of analysis
If there are issues with user's json config, we should report it asap and fail without start of analysis. Possible issues:
* wrong warning names
~* wrong fields in configuration~ moved to #395 
~* wrong values in configuration (e.g. numbers in wrong format)~ same

### LINKED ISSUE #262: In case rules configuration is missing - diktat should raise warning/error
Some people will not like to use default configuration, but will not know that they should configure diktat.

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Added validation logic
* Added tests

This pull request closes #58 , closes #262

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt [hunk 1]
```diff
@@ -16,17 +19,27 @@ import org.cqfn.diktat.ruleset.rules.identifiers.LocalVariablesRule
...
  */
 const val DIKTAT_RULE_SET_ID = "diktat-ruleset"
 
 class DiktatRuleSetProvider(private val diktatConfigFile: String = "diktat-analysis.yml") : RuleSetProvider {
+    @Suppress("LongMethod")
     override fun get(): RuleSet {
         log.debug("Will run $DIKTAT_RULE_SET_ID with $diktatConfigFile (it can be placed to the run directory or the default file from resources will be used)")
-        val configRules = RulesConfigReader(javaClass.classLoader).readResource(diktatConfigFile) ?: listOf()
+        if (!File(diktatConfigFile).exists()) {
+            log.warn("File $diktatConfigFile not found in file system, the file included in jar will be used. " +
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt:36]: I guess we need explicitly say "Be careful! File $diktatConfiFile not found ... It should be placed in the directory where diktat binary is placed "

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt [hunk 2]
```diff
@@ -16,17 +19,27 @@ import org.cqfn.diktat.ruleset.rules.identifiers.LocalVariablesRule
...
+                    "Some configuration options will be disabled or substituted with defaults.")
+        }
+        val configRules = RulesConfigReader(javaClass.classLoader)
+            .readResource(diktatConfigFile)
+            ?.onEach(::validate)
+            ?: listOf()
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt:42]: emptyList()? :)

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt [hunk 3]
```diff
@@ -63,3 +64,32 @@ fun String.removePrefix(): String {
     if (this.isUpperSnakeCase()) return this.substring(2)
     return this
 }
+
+fun String.editorDistance(another: String): Int {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt:68]: there is no existing libs for it? :))
if no - at least add Kdoc

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt [hunk 4]
```diff
@@ -63,3 +64,32 @@ fun String.removePrefix(): String {
...
+    acc[0].indices.forEach {
+        acc[0][it] = it
+    }
+
+    acc.indices.forEach {
+        acc[it][0] = it
+    }
+
+    (1 until acc.size).forEach { row ->
+        (1 until acc[0].size).forEach { col ->
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt:82]: why acc[0] is here and not row?

File: diktat-rules/src/main/resources/diktat-analysis.yml [hunk 5]
```diff
@@ -40,13 +40,13 @@
   enabled: true
   configuration: {}
 - name: PACKAGE_NAME_INCORRECT_PREFIX
-  enabled: true
+  enabled: false
```
Comment (akuleshov7) [inline diktat-rules/src/main/resources/diktat-analysis.yml:43]: btw - need to add comment here for users
```
  configuration: { # configuration domainName is taken from DIKTAT_COMMON }
```

File: diktat-rules/src/main/resources/diktat-analysis.yml [hunk 6]
```diff
@@ -40,13 +40,13 @@
...
   configuration: {}
 - name: PACKAGE_NAME_INCORRECT_SYMBOLS
   enabled: true
   configuration: {}
 - name: PACKAGE_NAME_INCORRECT_PATH
-  enabled: true
+  enabled: false
```
Comment (akuleshov7) [inline diktat-rules/src/main/resources/diktat-analysis.yml:49]: same here

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt [hunk 7]
```diff
@@ -81,6 +94,12 @@ class DiktatRuleSetProvider(private val diktatConfigFile: String = "diktat-analy
         )
     }
 
+    private fun validate(config: RulesConfig) =
+        require(config.name == DIKTAT_COMMON || config.name in Warnings.names) {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt:98]: it will do procExit(1) and stop diktat (diktat should be stopped in this case I guess)
We do not handle this exception somehow accidentally?

**Review by akuleshov7 — APPROVED** [review]
basically looks good, I would think about the algorithm of detecting distance more may be. I am pretty sure we are inventing a bicycle. But if not - lgtm

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt (hunk 3 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt:68]: Guess I was just googling incorrectly. On the second attempt I found that it's implemented, for example, in Apache commons text. I'll try to use it then, wasn't happy about re-umplementing it either..

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt (hunk 4 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt:82]: Because all rows have the same size. Could've used string length here, though.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt (hunk 3 above)
Comment (akuleshov7) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt:68]: then nevermind, that is absolutely ok

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/utils/StringUtils.kt:68]: It's even funnier - `kotlin-compiler-embeddable` contains `jline` inside of it, and Levenstein distance is implemented there.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt:36]: Yes, I'll change warning message. Btw, for maven plugin user can specify arbitrary config location, not necessary WD.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt (hunk 7 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/DiktatRuleSetProvider.kt:98]: I think, when running via KtLint, this exception will be thrown all the way to ktlint, when it's loading discovered service providers. In `diktat-maven-plugin` it's not handled and will cause `MojoExecutionException`.
CLI exception will look like this:
```
Exception in thread "main" java.lang.IllegalArgumentException: Warning name <CLASS_NAME_INCORRECT__> in configuration file is invalid, did you mean <CLASS_NAME_INCORRECT>?
	at org.cqfn.diktat.ruleset.rules.DiktatRuleSetProvider.validate(DiktatRuleSetProvider.kt:101)
	at org.cqfn.diktat.ruleset.rules.DiktatRuleSetProvider.get(DiktatRuleSetProvider.kt:44)
	at com.pinterest.ktlint.KtlintCommandLine.loadRulesets(Main.kt:550)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:222)
	at com.pinterest.ktlint.Main.main(Main.kt:62)
```
