### PR TITLE
Lambda incorrect trigger

### LINKED ISSUE #992: LAMBDA_IS_NOT_LAST_PARAMETER: incorrectly treats argument with nullable functional type as not functional
## Describe the bug
```kotlin
fun foo(lambda1: () -> Unit,
             lambda2: (() -> Unit)?
) {}
```
emits warning `LAMBDA_IS_NOT_LAST_PARAMETER`, but if `lambda2` is non-nullable, there is no warning:
```kotlin
fun foo(lambda1: () -> Unit,
             lambda2: (() -> Unit)
) {}
```

## Environment information
* diktat version: 1.0.0-rc.2

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
- Fixed bug
- Closes #992

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter5/LambdaParameterOrder.kt [hunk 1]
```diff
@@ -28,7 +29,16 @@ class LambdaParameterOrder(configRules: List<RulesConfig>) : DiktatRule(
...
     private fun checkArguments(node: ASTNode) {
         val funArguments = (node.psi as KtFunction).valueParameters
-        val sortArguments = funArguments.sortedBy { it.typeReference?.node?.hasChildOfType(FUNCTION_TYPE) }
+        val sortArguments = funArguments
+            .sortedBy {
+                it
+                    .typeReference
+                    ?.node
+                    ?.let { astNode ->
+                        astNode.findChildByType(NULLABLE_TYPE) ?: astNode
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter5/LambdaParameterOrder.kt:38]: Kotlin best practices are to make outer lambda's argument named. It's strange, actually, that we still don't check it in diktat

**Review by petertrr — APPROVED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter5/LambdaParameterOrder.kt (hunk 1 above)
Comment (kentr0w) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter5/LambdaParameterOrder.kt]: #1009
